MERGE INTO ${catalog}.${gap_schema_transformation}.MEMBER AS TARGET
USING (
	SELECT
		MEMBER_BID, HOME_PLAN_ID_CD, MEMB_ID_CD, BHI_MEMB_ID, DEID_MEM_ID, PERSON_ID_CD, ALT_MEM_ID,
		MBRS_NM_LAST, MBRS_NM_MIDDLE, MBRS_NM_FIRST, MEMB_BRTH_DT, MEMB_DEATH_DT, MEMB_GENDER_CD,
		MEMB_CNFDNT_CD, MBRS_STREET1, MBRS_STREET2, MBRS_CITY, MBRS_STATE, MBRS_CRNT_COUNTY_CD,
		MBRS_CRNT_PRIM_ZIP_CD, MBRS_CRNT_PRIM_ZIP_PLUSFOUR, MBRS_PRIM_PHN, MBRS_PRIM_EMAIL,
		MBRS_PREF_CONTACT, MEMB_SMOKING_STS, SEG1_ID, SEG2_ID, SEG3_ID, SEG4_ID, SEG5_ID, SEG6_ID,
		SEG7_ID, SEG8_ID, SEG9_ID, SEG10_ID, SOURCE_LOAD_MONTH
	FROM (
		SELECT
			risk.BID AS MEMBER_BID, TRIM(stage.HOME_PLAN_ID_CD) AS HOME_PLAN_ID_CD,
			TRIM(stage.MEMB_ID_CD) AS MEMB_ID_CD, TRIM(stage.BHI_MEMB_ID) AS BHI_MEMB_ID,
			TRIM(stage.DEID_MEM_ID) AS DEID_MEM_ID, TRIM(stage.PERSON_ID_CD) AS PERSON_ID_CD,
			TRIM(stage.ALT_MEM_ID) AS ALT_MEM_ID, TRIM(stage.MBRS_NM_LAST) AS MBRS_NM_LAST,
			COALESCE(TRIM(stage.MBRS_NM_MIDDLE), '') AS MBRS_NM_MIDDLE,
			TRIM(stage.MBRS_NM_FIRST) AS MBRS_NM_FIRST,
			CASE
				WHEN TRIM(stage.MEMB_BRTH_DT) RLIKE '^[0-9]{8}$'
					THEN to_date(TRIM(stage.MEMB_BRTH_DT), 'yyyyMMdd')
				WHEN TRIM(stage.MEMB_BRTH_DT) RLIKE '^[0-9]{4}-[0-9]{2}-[0-9]{2}$'
					THEN to_date(TRIM(stage.MEMB_BRTH_DT), 'yyyy-MM-dd')
				WHEN TRIM(stage.MEMB_BRTH_DT) RLIKE '^[0-9]{1,2}/[0-9]{1,2}/[0-9]{4}$'
					THEN to_date(TRIM(stage.MEMB_BRTH_DT), 'M/d/yyyy')
				ELSE NULL
			END AS MEMB_BRTH_DT,
			CASE
				WHEN TRIM(stage.MEMB_DEATH_DT) RLIKE '^[0-9]{8}$'
					THEN to_date(TRIM(stage.MEMB_DEATH_DT), 'yyyyMMdd')
				WHEN TRIM(stage.MEMB_DEATH_DT) RLIKE '^[0-9]{4}-[0-9]{2}-[0-9]{2}$'
					THEN to_date(TRIM(stage.MEMB_DEATH_DT), 'yyyy-MM-dd')
				WHEN TRIM(stage.MEMB_DEATH_DT) RLIKE '^[0-9]{1,2}/[0-9]{1,2}/[0-9]{4}$'
					THEN to_date(TRIM(stage.MEMB_DEATH_DT), 'M/d/yyyy')
				ELSE NULL
			END AS MEMB_DEATH_DT,
			TRIM(stage.MEMB_GENDER_CD) AS MEMB_GENDER_CD, TRIM(stage.MEMB_CNFDNT_CD) AS MEMB_CNFDNT_CD,
			TRIM(stage.MBRS_STREET1) AS MBRS_STREET1, TRIM(stage.MBRS_STREET2) AS MBRS_STREET2,
			TRIM(stage.MBRS_CITY) AS MBRS_CITY, TRIM(stage.MBRS_STATE) AS MBRS_STATE,
			TRIM(stage.MBRS_CRNT_COUNTY_CD) AS MBRS_CRNT_COUNTY_CD,
			TRIM(stage.MBRS_CRNT_PRIM_ZIP_CD) AS MBRS_CRNT_PRIM_ZIP_CD,
			COALESCE(TRIM(stage.MBRS_CRNT_PRIM_ZIP_PLUSFOUR), '') AS MBRS_CRNT_PRIM_ZIP_PLUSFOUR,
			TRIM(stage.MBRS_PRIM_PHN) AS MBRS_PRIM_PHN, TRIM(stage.MBRS_PRIM_EMAIL) AS MBRS_PRIM_EMAIL,
			TRIM(stage.MBRS_PREF_CONTACT) AS MBRS_PREF_CONTACT,
			TRIM(stage.MEMB_SMOKING_STS) AS MEMB_SMOKING_STS,
			TRIM(stage.SEG1_ID) AS SEG1_ID, TRIM(stage.SEG2_ID) AS SEG2_ID, TRIM(stage.SEG3_ID) AS SEG3_ID,
			TRIM(stage.SEG4_ID) AS SEG4_ID, TRIM(stage.SEG5_ID) AS SEG5_ID, TRIM(stage.SEG6_ID) AS SEG6_ID,
			TRIM(stage.SEG7_ID) AS SEG7_ID, TRIM(stage.SEG8_ID) AS SEG8_ID,
			COALESCE(TRIM(stage.SEG9_ID), '') AS SEG9_ID, COALESCE(TRIM(stage.SEG10_ID), '') AS SEG10_ID,
			TRIM(stage.SOURCE_LOAD_MONTH) AS SOURCE_LOAD_MONTH,
			ROW_NUMBER() OVER (
				PARTITION BY TRIM(stage.HOME_PLAN_ID_CD), TRIM(stage.MEMB_ID_CD), TRIM(stage.SOURCE_LOAD_MONTH)
				ORDER BY COALESCE(stage.UPDATED_DATE, stage.CREATED_DATE, CURRENT_TIMESTAMP()) DESC
			) AS rn
		FROM (
			SELECT * FROM ${catalog}.${schema_ingestion}.STAGE_MEMBER
			WHERE SOURCE_LOAD_MONTH = ${SOURCE_LOAD_MONTH}
		) stage
		JOIN ${catalog}.${gap_schema_transformation}.MEMBER_ID risk ON risk.HOME_PLAN_ID_CD = stage.HOME_PLAN_ID_CD
		AND risk.PERSON_ID = stage.PERSON_ID_CD) ranked_source
	WHERE rn = 1
) AS SOURCE
ON SOURCE.HOME_PLAN_ID_CD = TARGET.HOME_PLAN_ID_CD
AND SOURCE.MEMB_ID_CD = TARGET.MEMB_ID_CD
WHEN MATCHED THEN
	UPDATE SET
		MEMBER_BID = SOURCE.MEMBER_BID, BHI_MEMB_ID = SOURCE.BHI_MEMB_ID, DEID_MEM_ID = SOURCE.DEID_MEM_ID,
		PERSON_ID_CD = SOURCE.PERSON_ID_CD, ALT_MEM_ID = SOURCE.ALT_MEM_ID,
		MBRS_NM_LAST = SOURCE.MBRS_NM_LAST, MBRS_NM_MIDDLE = SOURCE.MBRS_NM_MIDDLE,
		MBRS_NM_FIRST = SOURCE.MBRS_NM_FIRST, MEMB_BRTH_DT = SOURCE.MEMB_BRTH_DT,
		MEMB_DEATH_DT = SOURCE.MEMB_DEATH_DT, MEMB_GENDER_CD = SOURCE.MEMB_GENDER_CD,
		MEMB_CNFDNT_CD = SOURCE.MEMB_CNFDNT_CD, MBRS_STREET1 = SOURCE.MBRS_STREET1,
		MBRS_STREET2 = SOURCE.MBRS_STREET2, MBRS_CITY = SOURCE.MBRS_CITY, MBRS_STATE = SOURCE.MBRS_STATE,
		MBRS_CRNT_COUNTY_CD = SOURCE.MBRS_CRNT_COUNTY_CD,
		MBRS_CRNT_PRIM_ZIP_CD = SOURCE.MBRS_CRNT_PRIM_ZIP_CD,
		MBRS_CRNT_PRIM_ZIP_PLUSFOUR = SOURCE.MBRS_CRNT_PRIM_ZIP_PLUSFOUR,
		MBRS_PRIM_PHN = SOURCE.MBRS_PRIM_PHN, MBRS_PRIM_EMAIL = SOURCE.MBRS_PRIM_EMAIL,
		MBRS_PREF_CONTACT = SOURCE.MBRS_PREF_CONTACT, MEMB_SMOKING_STS = SOURCE.MEMB_SMOKING_STS,
		SEG1_ID = SOURCE.SEG1_ID, SEG2_ID = SOURCE.SEG2_ID, SEG3_ID = SOURCE.SEG3_ID,
		SEG4_ID = SOURCE.SEG4_ID, SEG5_ID = SOURCE.SEG5_ID, SEG6_ID = SOURCE.SEG6_ID,
		SEG7_ID = SOURCE.SEG7_ID, SEG8_ID = SOURCE.SEG8_ID, SEG9_ID = SOURCE.SEG9_ID, SEG10_ID = SOURCE.SEG10_ID,
		source_load_month = SOURCE.SOURCE_LOAD_MONTH,
		updated_date = current_timestamp(), updated_by = ${CURRENT_USER}
WHEN NOT MATCHED THEN
	INSERT (
		MEMBER_BID, HOME_PLAN_ID_CD, MEMB_ID_CD, BHI_MEMB_ID, DEID_MEM_ID, PERSON_ID_CD, ALT_MEM_ID,
		MBRS_NM_LAST, MBRS_NM_MIDDLE, MBRS_NM_FIRST, MEMB_BRTH_DT, MEMB_DEATH_DT, MEMB_GENDER_CD,
		MEMB_CNFDNT_CD, MBRS_STREET1, MBRS_STREET2, MBRS_CITY, MBRS_STATE, MBRS_CRNT_COUNTY_CD,
		MBRS_CRNT_PRIM_ZIP_CD, MBRS_CRNT_PRIM_ZIP_PLUSFOUR, MBRS_PRIM_PHN, MBRS_PRIM_EMAIL,
		MBRS_PREF_CONTACT, MEMB_SMOKING_STS, SEG1_ID, SEG2_ID, SEG3_ID, SEG4_ID, SEG5_ID, SEG6_ID,
		SEG7_ID, SEG8_ID, SEG9_ID, SEG10_ID, LOAD_DATE, SOURCE_LOAD_MONTH, CREATED_DATE, CREATED_BY
	)
	VALUES (
		SOURCE.MEMBER_BID, SOURCE.HOME_PLAN_ID_CD, SOURCE.MEMB_ID_CD, SOURCE.BHI_MEMB_ID,
		SOURCE.DEID_MEM_ID, SOURCE.PERSON_ID_CD, SOURCE.ALT_MEM_ID, SOURCE.MBRS_NM_LAST,
		SOURCE.MBRS_NM_MIDDLE, SOURCE.MBRS_NM_FIRST, SOURCE.MEMB_BRTH_DT, SOURCE.MEMB_DEATH_DT,
		SOURCE.MEMB_GENDER_CD, SOURCE.MEMB_CNFDNT_CD, SOURCE.MBRS_STREET1, SOURCE.MBRS_STREET2,
		SOURCE.MBRS_CITY, SOURCE.MBRS_STATE, SOURCE.MBRS_CRNT_COUNTY_CD, SOURCE.MBRS_CRNT_PRIM_ZIP_CD,
		SOURCE.MBRS_CRNT_PRIM_ZIP_PLUSFOUR, SOURCE.MBRS_PRIM_PHN, SOURCE.MBRS_PRIM_EMAIL,
		SOURCE.MBRS_PREF_CONTACT, SOURCE.MEMB_SMOKING_STS, SOURCE.SEG1_ID, SOURCE.SEG2_ID, SOURCE.SEG3_ID,
		SOURCE.SEG4_ID, SOURCE.SEG5_ID, SOURCE.SEG6_ID, SOURCE.SEG7_ID, SOURCE.SEG8_ID, SOURCE.SEG9_ID,
		SOURCE.SEG10_ID, CURRENT_TIMESTAMP(), SOURCE.SOURCE_LOAD_MONTH,
		current_timestamp(), ${CURRENT_USER}
	);

-- ================================================
-- Part 2: MEMBER_ENROLLMENT MERGE
-- ================================================
WITH base_data AS (
	SELECT
		HOME_PLAN_ID_CD, TRCBLT_FIELD_CD, ISSUER_ID, PLAN_ID, MEMBER_BID, MEMB_ID_CD,
		COVRG_BEGIN_DT AS COVRG_BEGIN_DT_ORIG, COVRG_END_DT AS COVRG_END_DT_ORIG,
		ACCT_CD, GRP_CD, SUBGRP_CD, PROD_ID_CD, PROD_TYPE_CD, GROUP_SIZE_CD, NATIONAL_ACCOUNT_IND,
		LINE_OF_BUSINESS_CD, MARKET_CD, PRODUCT_LINE_CD, EMPLOYEE_STATUS_CD, EMPLOYEE_TYPE_CD,
		FUNDING_ARRANGEMENT_CD, BARGAINING_STATUS_CD, CONTRACT_ID, CONTRACT_EFFECTIVE_DT, CONTRACT_END_DT,
		NAICS_CD, INDUSTRY, SUB_ID, MEMB_RLTNSHP_CD, PHRMCY_BNFT_IND, MED_BNFT_IND, HSPTL_BNFT_IND,
		MH_BNFT_IND, CD_BNFT_IND, DNT_BNFT_IND, POP_ID, EXCH_IND, RATING_AREA, PREM_AMT, CSR_INDICATOR,
		METAL, ENROLL_PERIOD_ACT, MEMB_MED_COB_CD, MEMB_PHRMCY_COB_CD, SEG5_ID, SEG6_ID, SEG7_ID, SEG8_ID,
		SEG5_ID, SEG6_ID, SEG7_ID, SEG8_ID, SEG9_ID, SEG10_ID, SEG11_ID, SEG12_ID, SEG13_ID, SEG14_ID,
		MA_MCD_IND, MA_OREC, MA_FRAILTY_IND, MA_LTI_FLAG, MA_DFLT_RISKFAC_CD, MA_RAFT_CD, MA_FRAILTY_FACTOR,
		LOAD_DATE, SOURCE_LOAD_MONTH
	FROM (
		SELECT
			TRIM(stage.HOME_PLAN_ID_CD) AS HOME_PLAN_ID_CD, TRIM(stage.TRCBLT_FIELD_CD) AS TRCBLT_FIELD_CD,
			coalesce(nullif(TRIM(stage.ISSUER_ID), ''), 0) AS ISSUER_ID, TRIM(stage.PLAN_ID) AS PLAN_ID,
			coalesce(risk.BID, 0) AS MEMBER_BID, TRIM(stage.MEMB_ID_CD) AS MEMB_ID_CD,
			CASE
				WHEN TRIM(stage.COVRG_BEGIN_DT) RLIKE '^[0-9]{8}$'
					THEN to_date(TRIM(stage.COVRG_BEGIN_DT), 'yyyyMMdd')
				WHEN TRIM(stage.COVRG_BEGIN_DT) RLIKE '^[0-9]{4}-[0-9]{2}-[0-9]{2}$'
					THEN to_date(TRIM(stage.COVRG_BEGIN_DT), 'yyyy-MM-dd')
				WHEN TRIM(stage.COVRG_BEGIN_DT) RLIKE '^[0-9]{1,2}/[0-9]{1,2}/[0-9]{4}$'
					THEN to_date(TRIM(stage.COVRG_BEGIN_DT), 'M/d/yyyy')
				ELSE NULL
			END AS COVRG_BEGIN_DT,
			CASE
				WHEN TRIM(stage.COVRG_END_DT) RLIKE '^[0-9]{8}$'
					THEN to_date(TRIM(stage.COVRG_END_DT), 'yyyyMMdd')
				WHEN TRIM(stage.COVRG_END_DT) RLIKE '^[0-9]{4}-[0-9]{2}-[0-9]{2}$'
					THEN to_date(TRIM(stage.COVRG_END_DT), 'yyyy-MM-dd')
				WHEN TRIM(stage.COVRG_END_DT) RLIKE '^[0-9]{1,2}/[0-9]{1,2}/[0-9]{4}$'
					THEN to_date(TRIM(stage.COVRG_END_DT), 'M/d/yyyy')
				ELSE NULL
			END AS COVRG_END_DT,
			TRIM(stage.ACCT_CD) AS ACCT_CD, TRIM(stage.GRP_CD) AS GRP_CD, TRIM(stage.SUBGRP_CD) AS SUBGRP_CD,
			TRIM(stage.PROD_ID_CD) AS PROD_ID_CD, TRIM(stage.PROD_TYPE_CD) AS PROD_TYPE_CD,
			coalesce(TRIM(stage.GROUP_SIZE_CD), 'UN') AS GROUP_SIZE_CD,
			coalesce(TRIM(stage.NATIONAL_ACCOUNT_IND), 'N') AS NATIONAL_ACCOUNT_IND,
			coalesce(TRIM(stage.LINE_OF_BUSINESS_CD), 'UN') AS LINE_OF_BUSINESS_CD,
			coalesce(TRIM(stage.MARKET_CD), 'UN') AS MARKET_CD,
			coalesce(TRIM(stage.PRODUCT_LINE_CD), 'UN') AS PRODUCT_LINE_CD,
			coalesce(TRIM(stage.EMPLOYEE_STATUS_CD), 'NA') AS EMPLOYEE_STATUS_CD,
			coalesce(TRIM(stage.EMPLOYEE_TYPE_CD), 'NA') AS EMPLOYEE_TYPE_CD,
			coalesce(TRIM(stage.FUNDING_ARRANGEMENT_CD), 'NA') AS FUNDING_ARRANGEMENT_CD,
			coalesce(TRIM(stage.BARGAINING_STATUS_CD), 'NA') AS BARGAINING_STATUS_CD,
			coalesce(TRIM(stage.CONTRACT_ID), '') AS CONTRACT_ID,
			CASE
				WHEN TRIM(stage.CONTRACT_EFFECTIVE_DT) RLIKE '^[0-9]{8}$'
					THEN to_date(TRIM(stage.CONTRACT_EFFECTIVE_DT), 'yyyyMMdd')
				WHEN TRIM(stage.CONTRACT_EFFECTIVE_DT) RLIKE '^[0-9]{4}-[0-9]{2}-[0-9]{2}$'
					THEN to_date(TRIM(stage.CONTRACT_EFFECTIVE_DT), 'yyyy-MM-dd')
				WHEN TRIM(stage.CONTRACT_EFFECTIVE_DT) RLIKE '^[0-9]{1,2}/[0-9]{1,2}/[0-9]{4}$'
					THEN to_date(TRIM(stage.CONTRACT_EFFECTIVE_DT), 'M/d/yyyy')
				ELSE NULL
			END AS CONTRACT_EFFECTIVE_DT,
			CASE
				WHEN TRIM(stage.CONTRACT_END_DT) RLIKE '^[0-9]{8}$'
					THEN to_date(TRIM(stage.CONTRACT_END_DT), 'yyyyMMdd')
				WHEN TRIM(stage.CONTRACT_END_DT) RLIKE '^[0-9]{4}-[0-9]{2}-[0-9]{2}$'
					THEN to_date(TRIM(stage.CONTRACT_END_DT), 'yyyy-MM-dd')
				WHEN TRIM(stage.CONTRACT_END_DT) RLIKE '^[0-9]{1,2}/[0-9]{1,2}/[0-9]{4}$'
					THEN to_date(TRIM(stage.CONTRACT_END_DT), 'M/d/yyyy')
				ELSE NULL
			END AS CONTRACT_END_DT,
			coalesce(TRIM(stage.NAICS_CD), '') AS NAICS_CD, coalesce(TRIM(stage.INDUSTRY), '') AS INDUSTRY,
			TRIM(stage.SUB_ID) AS SUB_ID, TRIM(stage.MEMB_RLTNSHP_CD) AS MEMB_RLTNSHP_CD,
			TRIM(stage.PHRMCY_BNFT_IND) AS PHRMCY_BNFT_IND, TRIM(stage.MED_BNFT_IND) AS MED_BNFT_IND,
			TRIM(stage.HSPTL_BNFT_IND) AS HSPTL_BNFT_IND, TRIM(stage.MH_BNFT_IND) AS MH_BNFT_IND,
			TRIM(stage.CD_BNFT_IND) AS CD_BNFT_IND, TRIM(stage.DNT_BNFT_IND) AS DNT_BNFT_IND,
			TRIM(stage.POP_ID) AS POP_ID,
			CASE WHEN TRIM(stage.POP_ID) = '04' AND TRIM(stage.EXCH_IND) NOT IN ('ON', 'OFF')
				THEN 'OFF' ELSE TRIM(stage.EXCH_IND) END AS EXCH_IND,
			TRIM(stage.RATING_AREA) AS RATING_AREA,
			CAST(CAST(stage.PREM_AMT AS DECIMAL(10,2))/100 AS DECIMAL(10,2)) AS PREM_AMT,
			coalesce(nullif(
				CASE WHEN TRIM(stage.POP_ID) = '04' THEN TRIM(csr.CSR_INDICATOR)
				ELSE coalesce(TRIM(csr.CSR_INDICATOR), TRIM(stage.CSR_INDICATOR)) END,
				''),
			'0') AS CSR_INDICATOR,
			coalesce(nullif(TRIM(CASE WHEN TRIM(stage.POP_ID) = '04' THEN TRIM(metal.METAL)
				ELSE TRIM(stage.METAL) END), ''), 'Silver') AS METAL,
			TRIM(stage.ENROLL_PERIOD_ACT) AS ENROLL_PERIOD_ACT, TRIM(stage.MEMB_MED_COB_CD) AS MEMB_MED_COB_CD,
			TRIM(stage.MEMB_PHRMCY_COB_CD) AS MEMB_PHRMCY_COB_CD,
			coalesce(TRIM(stage.SEG1_ID), '') AS SEG1_ID, coalesce(TRIM(stage.SEG2_ID), '') AS SEG2_ID,
			coalesce(TRIM(stage.SEG3_ID), '') AS SEG3_ID, coalesce(TRIM(stage.SEG4_ID), '') AS SEG4_ID,
			coalesce(TRIM(stage.SEG5_ID), '') AS SEG5_ID, coalesce(TRIM(stage.SEG6_ID), '') AS SEG6_ID,
			coalesce(TRIM(stage.SEG7_ID), '') AS SEG7_ID, coalesce(TRIM(stage.SEG8_ID), '') AS SEG8_ID,
			coalesce(TRIM(stage.SEG9_ID), '') AS SEG9_ID, coalesce(TRIM(stage.SEG10_ID), '') AS SEG10_ID,
			coalesce(TRIM(stage.SEG11_ID), '') AS SEG11_ID, coalesce(TRIM(stage.SEG12_ID), '') AS SEG12_ID,
			coalesce(TRIM(stage.SEG13_ID), '') AS SEG13_ID, coalesce(TRIM(stage.SEG14_ID), '') AS SEG14_ID,
			TRIM(stage.MA_MCD_IND) AS MA_MCD_IND, TRIM(stage.MA_OREC) AS MA_OREC,
			TRIM(stage.MA_FRAILTY_IND) AS MA_FRAILTY_IND, TRIM(stage.MA_LTI_FLAG) AS MA_LTI_FLAG,
			TRIM(stage.MA_DFLT_RISKFAC_CD) AS MA_DFLT_RISKFAC_CD, TRIM(stage.MA_RAFT_CD) AS MA_RAFT_CD,
			stage.MA_FRAILTY_FACTOR, current_timestamp() AS LOAD_DATE,
			TRIM(stage.SOURCE_LOAD_MONTH) AS SOURCE_LOAD_MONTH,
			ROW_NUMBER() OVER (
				PARTITION BY
					TRIM(stage.HOME_PLAN_ID_CD),
					TRIM(stage.MEMB_ID_CD),
					CASE
						WHEN TRIM(stage.COVRG_BEGIN_DT) RLIKE '^[0-9]{8}$'
							THEN to_date(TRIM(stage.COVRG_BEGIN_DT), 'yyyyMMdd')
						WHEN TRIM(stage.COVRG_BEGIN_DT) RLIKE '^[0-9]{4}-[0-9]{2}-[0-9]{2}$'
							THEN to_date(TRIM(stage.COVRG_BEGIN_DT), 'yyyy-MM-dd')
						WHEN TRIM(stage.COVRG_BEGIN_DT) RLIKE '^[0-9]{1,2}/[0-9]{1,2}/[0-9]{4}$'
							THEN to_date(TRIM(stage.COVRG_BEGIN_DT), 'M/d/yyyy')
						ELSE NULL
					END,
					TRIM(stage.PROD_ID_CD),
					TRIM(stage.PROD_TYPE_CD),
					TRIM(stage.SUB_ID)
				ORDER BY
					COALESCE(stage.UPDATED_DATE, stage.CREATED_DATE, CURRENT_TIMESTAMP()) DESC,
					-- Tie-breaker: when the same member/product has overlapping rows that
					-- share a begin date but differ on end date, keep the longest span
					-- (latest end date). Uses the parsed end date since COVRG_END_DT is not
					-- available as an alias inside this window.
					CASE
						WHEN TRIM(stage.COVRG_END_DT) RLIKE '^[0-9]{8}$'
							THEN to_date(TRIM(stage.COVRG_END_DT), 'yyyyMMdd')
						WHEN TRIM(stage.COVRG_END_DT) RLIKE '^[0-9]{4}-[0-9]{2}-[0-9]{2}$'
							THEN to_date(TRIM(stage.COVRG_END_DT), 'yyyy-MM-dd')
						WHEN TRIM(stage.COVRG_END_DT) RLIKE '^[0-9]{1,2}/[0-9]{1,2}/[0-9]{4}$'
							THEN to_date(TRIM(stage.COVRG_END_DT), 'M/d/yyyy')
						ELSE NULL
					END DESC
			) AS rn
		FROM (
			SELECT * FROM ${catalog}.${schema_ingestion}.STAGE_MEMBER_ENROLLMENT
			WHERE SOURCE_LOAD_MONTH = ${SOURCE_LOAD_MONTH}
			-- Exclude rows with a blank/null PLAN_ID. Some members are loaded with a
			-- duplicate enrollment carrying an empty (space-only) PLAN_ID alongside
			-- the valid one, so keeping only rows that have a real PLAN_ID prevents the
			-- blank duplicate from winning dedup and avoids merge ambiguity.
			AND COALESCE(TRIM(PLAN_ID), '') <> ''
		) stage
		LEFT JOIN ${catalog}.${gap_schema_transformation}.MEMBER_ID risk
			ON risk.HOME_PLAN_ID_CD = stage.HOME_PLAN_ID_CD
			AND risk.MEMBER_ID_CD = stage.MEMB_ID_CD
		LEFT JOIN ${catalog}.${schema_reference}.ref_risk_metal metal
			ON metal.METAL = stage.METAL
		LEFT JOIN ${catalog}.${schema_reference}.ref_risk_csr csr
			ON right(concat('0', csr.CSR_INDICATOR), 2) = right(concat('0', stage.CSR_INDICATOR), 2)
	) ranked_source
	WHERE rn = 1
),

sequence_dates AS (
	SELECT *,
		-- Only the open-ended / corrupt sentinel end date (9999-12-31) is
		-- collapsed to the current year so it does not explode a single
		-- enrollment into thousands of year-ly rows. Genuine future end dates
		-- (e.g. 2028-12-31) are kept as-is and split through their real end
		-- year. greatest(...) keeps the range ascending when a sentinel row
		-- has a begin year later than the current year. The true end date is
		-- preserved downstream: the final COVRG_END_DT is derived via
		-- least(COVRG_END_DT_ORIG, make_date(yr,12,31)), and COVRG_END_DT_ORIG
		-- is retained in SEG2_ID.
		sequence(
			year(COVRG_BEGIN_DT_ORIG),
			greatest(
				year(COVRG_BEGIN_DT_ORIG),
				CASE
					WHEN year(COVRG_END_DT_ORIG) >= 9999 THEN year(current_date())
					ELSE year(COVRG_END_DT_ORIG)
				END
			)
		) AS year_seq
	FROM base_data
	WHERE COVRG_BEGIN_DT_ORIG IS NOT NULL
		AND COVRG_END_DT_ORIG IS NOT NULL
		AND COVRG_BEGIN_DT_ORIG <= COVRG_END_DT_ORIG
),

sequence_dates_explode AS (
	SELECT *,
		'explode(year_seq) AS yr
	FROM sequence_dates
),

-- Two stage records with different COVRG_BEGIN_DT_ORIG can produce the same
-- computed COVRG_BEGIN_DT after year-splitting (e.g. a multi-year span clipped
-- to Jan 1 collides with a record that genuinely starts on Jan 1 of that year),
-- causing DELTA_MULTIPLE_SOURCE_ROW_MATCHING_TARGET_ROW_IN_MERGE.
-- COVRG_BEGIN_DT and COVRG_END_DT are computed here so the dedup join key
-- matches the final MERGE key exactly. QUALIFY filters without a subquery.
-- Prefer the record with the latest original begin date (most specific to the
-- year segment), then break ties by LOAD_DATE DESC.
sequence_dates_deduped AS (
	SELECT *,
		greatest(COVRG_BEGIN_DT_ORIG, make_date(yr, 1, 1)) AS COVRG_BEGIN_DT,
		least(COVRG_END_DT_ORIG, make_date(yr, 12, 31)) AS COVRG_END_DT,
		ROW_NUMBER() OVER (
			PARTITION BY
				HOME_PLAN_ID_CD,
				MEMB_ID_CD,
				greatest(COVRG_BEGIN_DT_ORIG, make_date(yr, 1, 1)),
				-- Keep concurrent product/subscriber segments distinct so they are not
				-- collapsed to one row per year. Must match the MERGE join key exactly.
				PROD_ID_CD,
				PROD_TYPE_CD,
				SUB_ID
			ORDER BY
				COVRG_BEGIN_DT_ORIG DESC,
				LOAD_DATE DESC
		) AS dedup_rn
	FROM sequence_dates_explode
	QUALIFY dedup_rn = 1
),
SOURCE AS (
	SELECT
		HOME_PLAN_ID_CD, TRCBLT_FIELD_CD, ISSUER_ID, PLAN_ID, MEMBER_BID, MEMB_ID_CD, COVRG_BEGIN_DT,
		COVRG_END_DT, ACCT_CD, GRP_CD, SUBGRP_CD, PROD_ID_CD, PROD_TYPE_CD, GROUP_SIZE_CD,
		NATIONAL_ACCOUNT_IND, LINE_OF_BUSINESS_CD, MARKET_CD, PRODUCT_LINE_CD, EMPLOYEE_STATUS_CD,
		EMPLOYEE_TYPE_CD, FUNDING_ARRANGEMENT_CD, BARGAINING_STATUS_CD, CONTRACT_ID, CONTRACT_EFFECTIVE_DT,
		CONTRACT_END_DT, NAICS_CD, INDUSTRY, SUB_ID, MEMB_RLTNSHP_CD, PHRMCY_BNFT_IND, MED_BNFT_IND,
		HSPTL_BNFT_IND, MH_BNFT_IND, CD_BNFT_IND, DNT_BNFT_IND, POP_ID, EXCH_IND, RATING_AREA, PREM_AMT,
		CSR_INDICATOR, METAL, ENROLL_PERIOD_ACT, MEMB_MED_COB_CD, MEMB_PHRMCY_COB_CD,
		COVRG_BEGIN_DT_ORIG
		AS SEG1_ID,
		COVRG_END_DT_ORIG
		AS SEG2_ID,
		year(COVRG_BEGIN_DT)
		AS SEG3_ID,
		datediff(COVRG_END_DT, COVRG_BEGIN_DT) AS SEG4_ID,
		SEG5_ID, SEG6_ID, SEG7_ID, SEG8_ID, SEG9_ID, SEG10_ID, SEG11_ID, SEG12_ID, SEG13_ID, SEG14_ID,
		MA_MCD_IND, MA_OREC, MA_FRAILTY_IND, MA_LTI_FLAG, MA_DFLT_RISKFAC_CD, MA_RAFT_CD, MA_FRAILTY_FACTOR,
		LOAD_DATE, SOURCE_LOAD_MONTH
	FROM sequence_dates_deduped
)
MERGE INTO ${catalog}.${gap_schema_transformation}.MEMBER_ENROLLMENT AS TARGET
USING SOURCE
ON TARGET.HOME_PLAN_ID_CD = SOURCE.HOME_PLAN_ID_CD
	AND TARGET.MEMB_ID_CD = SOURCE.MEMB_ID_CD
	AND TARGET.COVRG_BEGIN_DT = SOURCE.COVRG_BEGIN_DT
	AND TARGET.PROD_ID_CD = SOURCE.PROD_ID_CD
	AND TARGET.PROD_TYPE_CD = SOURCE.PROD_TYPE_CD
	AND TARGET.SUB_ID = SOURCE.SUB_ID
WHEN MATCHED THEN
	UPDATE SET
		TARGET.TRCBLT_FIELD_CD = SOURCE.TRCBLT_FIELD_CD, TARGET.ISSUER_ID = SOURCE.ISSUER_ID,
		TARGET.PLAN_ID = SOURCE.PLAN_ID, TARGET.MEMBER_BID = SOURCE.MEMBER_BID,
		TARGET.COVRG_END_DT = SOURCE.COVRG_END_DT, TARGET.ACCT_CD = SOURCE.ACCT_CD,
		TARGET.GRP_CD = SOURCE.GRP_CD, TARGET.SUBGRP_CD = SOURCE.SUBGRP_CD,
		TARGET.PROD_ID_CD = SOURCE.PROD_ID_CD, TARGET.PROD_TYPE_CD = SOURCE.PROD_TYPE_CD,
		TARGET.GROUP_SIZE_CD = SOURCE.GROUP_SIZE_CD, TARGET.NATIONAL_ACCOUNT_IND = SOURCE.NATIONAL_ACCOUNT_IND,
		TARGET.LINE_OF_BUSINESS_CD = SOURCE.LINE_OF_BUSINESS_CD, TARGET.MARKET_CD = SOURCE.MARKET_CD,
		TARGET.PRODUCT_LINE_CD = SOURCE.PRODUCT_LINE_CD, TARGET.EMPLOYEE_STATUS_CD = SOURCE.EMPLOYEE_STATUS_CD,
		TARGET.EMPLOYEE_TYPE_CD = SOURCE.EMPLOYEE_TYPE_CD,
		TARGET.FUNDING_ARRANGEMENT_CD = SOURCE.FUNDING_ARRANGEMENT_CD,
		TARGET.BARGAINING_STATUS_CD = SOURCE.BARGAINING_STATUS_CD,
		TARGET.CONTRACT_ID = SOURCE.CONTRACT_ID, TARGET.CONTRACT_EFFECTIVE_DT = SOURCE.CONTRACT_EFFECTIVE_DT,
		TARGET.CONTRACT_END_DT = SOURCE.CONTRACT_END_DT, TARGET.NAICS_CD = SOURCE.NAICS_CD,
		TARGET.INDUSTRY = SOURCE.INDUSTRY, TARGET.SUB_ID = SOURCE.SUB_ID,
		TARGET.MEMB_RLTNSHP_CD = SOURCE.MEMB_RLTNSHP_CD, TARGET.PHRMCY_BNFT_IND = SOURCE.PHRMCY_BNFT_IND,
		TARGET.MED_BNFT_IND = SOURCE.MED_BNFT_IND, TARGET.HSPTL_BNFT_IND = SOURCE.HSPTL_BNFT_IND,
		TARGET.MH_BNFT_IND = SOURCE.MH_BNFT_IND, TARGET.CD_BNFT_IND = SOURCE.CD_BNFT_IND,
		TARGET.DNT_BNFT_IND = SOURCE.DNT_BNFT_IND, TARGET.POP_ID = SOURCE.POP_ID,
		TARGET.EXCH_IND = SOURCE.EXCH_IND, TARGET.RATING_AREA = SOURCE.RATING_AREA,
		TARGET.PREM_AMT = SOURCE.PREM_AMT, TARGET.CSR_INDICATOR = SOURCE.CSR_INDICATOR,
		TARGET.METAL = SOURCE.METAL, TARGET.ENROLL_PERIOD_ACT = SOURCE.ENROLL_PERIOD_ACT,
		TARGET.MEMB_MED_COB_CD = SOURCE.MEMB_MED_COB_CD, TARGET.MEMB_PHRMCY_COB_CD = SOURCE.MEMB_PHRMCY_COB_CD,
		TARGET.SEG1_ID = SOURCE.SEG1_ID, TARGET.SEG2_ID = SOURCE.SEG2_ID, TARGET.SEG3_ID = SOURCE.SEG3_ID,
		TARGET.SEG4_ID = SOURCE.SEG4_ID, TARGET.SEG5_ID = SOURCE.SEG5_ID, TARGET.SEG6_ID = SOURCE.SEG6_ID,
		TARGET.SEG7_ID = SOURCE.SEG7_ID, TARGET.SEG8_ID = SOURCE.SEG8_ID, TARGET.SEG9_ID = SOURCE.SEG9_ID,
		TARGET.SEG10_ID = SOURCE.SEG10_ID, TARGET.SEG11_ID = SOURCE.SEG11_ID, TARGET.SEG12_ID = SOURCE.SEG12_ID,
		TARGET.SEG13_ID = SOURCE.SEG13_ID, TARGET.SEG14_ID = SOURCE.SEG14_ID,
		TARGET.MA_MCD_IND = SOURCE.MA_MCD_IND, TARGET.MA_OREC = SOURCE.MA_OREC,
		TARGET.MA_FRAILTY_IND = SOURCE.MA_FRAILTY_IND, TARGET.MA_LTI_FLAG = SOURCE.MA_LTI_FLAG,
		TARGET.MA_DFLT_RISKFAC_CD = SOURCE.MA_DFLT_RISKFAC_CD, TARGET.MA_RAFT_CD = SOURCE.MA_RAFT_CD,
		TARGET.MA_FRAILTY_FACTOR = SOURCE.MA_FRAILTY_FACTOR, TARGET.LOAD_DATE = SOURCE.LOAD_DATE,
		TARGET.SOURCE_LOAD_MONTH = SOURCE.SOURCE_LOAD_MONTH, TARGET.UPDATED_DATE = current_timestamp(),
		TARGET.UPDATED_BY = ${CURRENT_USER}
WHEN NOT MATCHED BY TARGET THEN
	INSERT (
		HOME_PLAN_ID_CD, TRCBLT_FIELD_CD, ISSUER_ID, PLAN_ID, MEMBER_BID, MEMB_ID_CD, COVRG_BEGIN_DT,
		COVRG_END_DT, ACCT_CD, GRP_CD, SUBGRP_CD, PROD_ID_CD, PROD_TYPE_CD, GROUP_SIZE_CD,
		NATIONAL_ACCOUNT_IND, LINE_OF_BUSINESS_CD, MARKET_CD, PRODUCT_LINE_CD, EMPLOYEE_STATUS_CD,
		EMPLOYEE_TYPE_CD, FUNDING_ARRANGEMENT_CD, BARGAINING_STATUS_CD, CONTRACT_ID, CONTRACT_EFFECTIVE_DT,
		CONTRACT_END_DT, NAICS_CD, INDUSTRY, SUB_ID, MEMB_RLTNSHP_CD, PHRMCY_BNFT_IND, MED_BNFT_IND,
		HSPTL_BNFT_IND, MH_BNFT_IND, CD_BNFT_IND, DNT_BNFT_IND, POP_ID, EXCH_IND, RATING_AREA, PREM_AMT,
		CSR_INDICATOR, METAL, ENROLL_PERIOD_ACT, MEMB_MED_COB_CD, MEMB_PHRMCY_COB_CD, SEG1_ID, SEG2_ID,
		SEG3_ID, SEG4_ID, SEG5_ID, SEG6_ID, SEG7_ID, SEG8_ID, SEG9_ID, SEG10_ID, SEG11_ID, SEG12_ID,
		SEG13_ID, SEG14_ID, MA_MCD_IND, MA_OREC, MA_FRAILTY_IND, MA_LTI_FLAG, MA_DFLT_RISKFAC_CD,
		MA_RAFT_CD, MA_FRAILTY_FACTOR, LOAD_DATE, SOURCE_LOAD_MONTH, CREATED_DATE, CREATED_BY
	)
	VALUES (
		SOURCE.HOME_PLAN_ID_CD, SOURCE.TRCBLT_FIELD_CD, SOURCE.ISSUER_ID, SOURCE.PLAN_ID, SOURCE.MEMBER_BID,
		SOURCE.MEMB_ID_CD, SOURCE.COVRG_BEGIN_DT, SOURCE.COVRG_END_DT, SOURCE.ACCT_CD, SOURCE.GRP_CD,
		SOURCE.SUBGRP_CD, SOURCE.PROD_ID_CD, SOURCE.PROD_TYPE_CD, SOURCE.GROUP_SIZE_CD,
		SOURCE.NATIONAL_ACCOUNT_IND, SOURCE.LINE_OF_BUSINESS_CD, SOURCE.MARKET_CD, SOURCE.PRODUCT_LINE_CD,
		SOURCE.EMPLOYEE_TYPE_CD, SOURCE.FUNDING_ARRANGEMENT_CD, SOURCE.BARGAINING_STATUS_CD,
		SOURCE.CONTRACT_ID, SOURCE.CONTRACT_EFFECTIVE_DT, SOURCE.CONTRACT_END_DT, SOURCE.NAICS_CD,
		SOURCE.INDUSTRY, SOURCE.SUB_ID, SOURCE.MEMB_RLTNSHP_CD, SOURCE.PHRMCY_BNFT_IND, SOURCE.MED_BNFT_IND,
		SOURCE.HSPTL_BNFT_IND, SOURCE.MH_BNFT_IND, SOURCE.CD_BNFT_IND, SOURCE.DNT_BNFT_IND, SOURCE.POP_ID,
		SOURCE.EXCH_IND, SOURCE.RATING_AREA, SOURCE.PREM_AMT, SOURCE.CSR_INDICATOR, SOURCE.METAL,
		SOURCE.ENROLL_PERIOD_ACT, SOURCE.MEMB_MED_COB_CD, SOURCE.MEMB_PHRMCY_COB_CD, SOURCE.SEG1_ID,
		SOURCE.SEG2_ID, SOURCE.SEG3_ID, SOURCE.SEG4_ID, SOURCE.SEG5_ID, SOURCE.SEG6_ID, SOURCE.SEG7_ID,
		SOURCE.SEG8_ID, SOURCE.SEG9_ID, SOURCE.SEG10_ID, SOURCE.SEG11_ID, SOURCE.SEG12_ID, SOURCE.SEG13_ID,
		SOURCE.SEG14_ID, SOURCE.MA_MCD_IND, SOURCE.MA_OREC, SOURCE.MA_FRAILTY_IND, SOURCE.MA_LTI_FLAG,
		SOURCE.MA_DFLT_RISKFAC_CD, SOURCE.MA_RAFT_CD, SOURCE.MA_FRAILTY_FACTOR, SOURCE.LOAD_DATE,
		SOURCE.SOURCE_LOAD_MONTH, CURRENT_TIMESTAMP(), ${CURRENT_USER}
	);

-- ================================================
-- Part 3: MEMBER_ENROLLEE_HISTORY Processing
-- ================================================

-- Step 1: Create comprehensive view with all transformations
CREATE OR REPLACE TEMPORARY VIEW current_batch_member_enrollee AS
SELECT
	TRIM(stage.HOME_PLAN_ID_CD) AS HOME_PLAN_ID_CD, COALESCE(risk.BID, 0) AS MEMBER_BID,
	TRIM(stage.MEMB_ID_CD) AS MEMB_ID_CD, TRIM(stage.BHI_MEMB_ID) AS BHI_MEMB_ID,
	CASE
		WHEN TRIM(stage.CONTRACT_BEGIN_DT) RLIKE '^[0-9]{8}$'
			THEN to_date(TRIM(stage.CONTRACT_BEGIN_DT), 'yyyyMMdd')
		WHEN TRIM(stage.CONTRACT_BEGIN_DT) RLIKE '^[0-9]{4}-[0-9]{2}-[0-9]{2}$'
			THEN to_date(TRIM(stage.CONTRACT_BEGIN_DT), 'yyyy-MM-dd')
		WHEN TRIM(stage.CONTRACT_BEGIN_DT) RLIKE '^[0-9]{1,2}/[0-9]{1,2}/[0-9]{4}$'
			THEN to_date(TRIM(stage.CONTRACT_BEGIN_DT), 'M/d/yyyy')
		ELSE NULL
	END AS CONTRACT_BEGIN_DT,
	CASE
		WHEN TRIM(stage.CONTRACT_END_DT) RLIKE '^[0-9]{8}$'
			THEN to_date(TRIM(stage.CONTRACT_END_DT), 'yyyyMMdd')
		WHEN TRIM(stage.CONTRACT_END_DT) RLIKE '^[0-9]{4}-[0-9]{2}-[0-9]{2}$'
			THEN to_date(TRIM(stage.CONTRACT_END_DT), 'yyyy-MM-dd')
		WHEN TRIM(stage.CONTRACT_END_DT) RLIKE '^[0-9]{1,2}/[0-9]{1,2}/[0-9]{4}$'
			THEN to_date(TRIM(stage.CONTRACT_END_DT), 'M/d/yyyy')
		ELSE NULL
	END AS CONTRACT_END_DT,
	TRIM(stage.POP_ID) AS POP_ID, TRIM(stage.ACCT_CD) AS ACCT_CD, TRIM(stage.GRP_CD) AS GRP_CD,
	TRIM(stage.SUBGRP_CD) AS SUBGRP_CD, TRIM(stage.PROD_ID_CD) AS PROD_ID_CD,
	TRIM(stage.SOURCE_LOAD_MONTH) AS SOURCE_LOAD_MONTH,
	ROW_NUMBER() OVER (
		PARTITION BY
			TRIM(stage.HOME_PLAN_ID_CD),
			TRIM(stage.MEMB_ID_CD),
			TRIM(stage.BHI_MEMB_ID),
			CASE
				WHEN TRIM(stage.CONTRACT_BEGIN_DT) RLIKE '^[0-9]{8}$'
					THEN to_date(TRIM(stage.CONTRACT_BEGIN_DT), 'yyyyMMdd')
				WHEN TRIM(stage.CONTRACT_BEGIN_DT) RLIKE '^[0-9]{4}-[0-9]{2}-[0-9]{2}$'
					THEN to_date(TRIM(stage.CONTRACT_BEGIN_DT), 'yyyy-MM-dd')
				WHEN TRIM(stage.CONTRACT_BEGIN_DT) RLIKE '^[0-9]{1,2}/[0-9]{1,2}/[0-9]{4}$'
					THEN to_date(TRIM(stage.CONTRACT_BEGIN_DT), 'M/d/yyyy')
				ELSE NULL
			END,
			CASE
				WHEN TRIM(stage.CONTRACT_END_DT) RLIKE '^[0-9]{8}$'
					THEN to_date(TRIM(stage.CONTRACT_END_DT), 'yyyyMMdd')
				WHEN TRIM(stage.CONTRACT_END_DT) RLIKE '^[0-9]{4}-[0-9]{2}-[0-9]{2}$'
					THEN to_date(TRIM(stage.CONTRACT_END_DT), 'yyyy-MM-dd')
				WHEN TRIM(stage.CONTRACT_END_DT) RLIKE '^[0-9]{1,2}/[0-9]{1,2}/[0-9]{4}$'
					THEN to_date(TRIM(stage.CONTRACT_END_DT), 'M/d/yyyy')
				ELSE NULL
			END,
			TRIM(stage.POP_ID), TRIM(stage.ACCT_CD), TRIM(stage.GRP_CD), TRIM(stage.SUBGRP_CD),
			TRIM(stage.PROD_ID_CD), TRIM(stage.SOURCE_LOAD_MONTH)
		ORDER BY COALESCE(stage.UPDATED_DATE, stage.CREATED_DATE, CURRENT_TIMESTAMP()) DESC
	) rn
FROM (
	SELECT * FROM ${catalog}.${schema_ingestion}.STAGE_MEMBER_ENROLLEE_HISTORY
	WHERE SOURCE_LOAD_MONTH = ${SOURCE_LOAD_MONTH}
) stage
LEFT OUTER JOIN ${catalog}.${gap_schema_transformation}.MEMBER_ID risk
	ON risk.HOME_PLAN_ID_CD = stage.HOME_PLAN_ID_CD
	AND risk.MEMBER_ID_CD = stage.MEMB_ID_CD;

-- Step 2: MERGE INTO MEMBER_ENROLLEE_HISTORY
MERGE INTO ${catalog}.${gap_schema_transformation}.MEMBER_ENROLLEE_HISTORY AS TARGET
USING (
	SELECT
		HOME_PLAN_ID_CD, MEMBER_BID, MEMB_ID_CD, BHI_MEMB_ID, CONTRACT_BEGIN_DT, CONTRACT_END_DT,
		POP_ID, ACCT_CD, GRP_CD, SUBGRP_CD, PROD_ID_CD, SOURCE_LOAD_MONTH
	FROM current_batch_member_enrollee
	WHERE rn = 1
) AS SOURCE
ON SOURCE.HOME_PLAN_ID_CD = TARGET.HOME_PLAN_ID_CD
	AND SOURCE.MEMB_ID_CD = TARGET.MEMB_ID_CD
	AND SOURCE.BHI_MEMB_ID = TARGET.BHI_MEMB_ID
	AND SOURCE.CONTRACT_BEGIN_DT = TARGET.CONTRACT_BEGIN_DT
WHEN MATCHED THEN
	UPDATE SET
		TARGET.CONTRACT_END_DT = SOURCE.CONTRACT_END_DT, TARGET.POP_ID = SOURCE.POP_ID,
		TARGET.ACCT_CD = SOURCE.ACCT_CD, TARGET.GRP_CD = SOURCE.GRP_CD,
		TARGET.SUBGRP_CD = SOURCE.SUBGRP_CD, TARGET.PROD_ID_CD = SOURCE.PROD_ID_CD,
		TARGET.LOAD_DATE = CURRENT_TIMESTAMP(), TARGET.UPDATED_DATE = CURRENT_TIMESTAMP(),
		TARGET.UPDATED_BY = ${CURRENT_USER}
WHEN NOT MATCHED BY TARGET THEN
	INSERT (
		HOME_PLAN_ID_CD, MEMBER_BID, MEMB_ID_CD, BHI_MEMB_ID, CONTRACT_BEGIN_DT, CONTRACT_END_DT,
		POP_ID, ACCT_CD, GRP_CD, SUBGRP_CD, PROD_ID_CD, LOAD_DATE, SOURCE_LOAD_MONTH, CREATED_DATE,
		CREATED_BY
	)
	VALUES (
		SOURCE.HOME_PLAN_ID_CD, SOURCE.MEMBER_BID, SOURCE.MEMB_ID_CD, SOURCE.BHI_MEMB_ID,
		SOURCE.CONTRACT_BEGIN_DT, SOURCE.CONTRACT_END_DT, SOURCE.POP_ID, SOURCE.ACCT_CD,
		SOURCE.GRP_CD, SOURCE.SUBGRP_CD, SOURCE.PROD_ID_CD, SOURCE.LOAD_DATE, SOURCE.SOURCE_LOAD_MONTH,
		CURRENT_TIMESTAMP(), ${CURRENT_USER}
	);

-- Step 3: Clean up
DROP VIEW IF EXISTS current_batch_member_enrollee;
