MEMBERS_COLUMNS:
  - HOME_PLAN_ID_CD
  - MEMB_ID_CD
  - BHT_MEMB_ID
  - PERSON_ID_CD
  - PERSON_ID_CD
  - MBRS_STATE
  - MEMB_BRTH_DT
  - MEMB_GENDER_CD
  - MEMB_DEATH_DT
  - SOURCE_LOAD_MONTH

MEMBER_ENROLLMENT_COLUMNS:
  - HOME_PLAN_ID_CD
  - MEMB_ID_CD
  - POP_ID
  - COVG_BEGIN_DT
  - COVG_END_DT
  - ACCT_CD
  - GRP_CD
  - SUBSCR_CD
  - ISSUER_ID
  - PROC_TYPE_CD
  - PHRM_PNFF_IND
  - MED_PNFF_IND
  - METALL
  - PRODUCT_ID
  - MEMBER_BID
  - SEGM_ID
  - SEGM_ID
  - SEGM_ID
  - SEGM_ID

MEMBER_ENROLLED_ID_HISTORY_COLUMNS:
  - MEMB_ID_CD
  - POP_ID

SUPPLEMENTAL_MAR_COLUMNS:
  - MERCH_BENEFICIARY_ID
  - OREC
  - ESR_STATUS
  - LIS_STATUS_PART_D

FACILITY_DETAIL_COLUMNS:
  - CIM_ID_CD
  - FACILITY_ID
  - SERV_END_DT
  - CPT_AND_HCPCS_CD
  - ALIMD_AMT

FACILITY_DIAG_COLUMNS:
  - FACILITY_BID
  - DIAG_TYPE_CD
  - DIAG_NUM
  - DIAG_CD
  - ICD_VER

FACILITY_HEADER_COLUMNS:
  - ADJ_SEQ_NUM
  - PLAN_ID
  - HOME_PLAN_ID_CD
  - CIM_ID_CD
  - MEMB_ID_CD
  - CLM_TP_CD
  - POS_ID
  - BIL_PROV_ID
  - FIRST_SERV_DT
  - LAST_SERV_DT
  - PROD_ID_CD
  - STMT_THRU_DT
  - STMT_FROM_DT
  - CLM_PMT_STS_CD
  - MEMBER_BID
  - SOURCE_LOAD_MONTH

PROFESSIONAL_DIAG_COLUMNS:
  - PROFESSIONAL_BID
  - DIAG_TYPE_CD
  - DIAG_NUM
  - DIAG_CD
  - ICD_VER

PROFESSIONAL_DIAG_SUPPLEMENTAL_COLUMNS:
  - PROFESSIONAL_BID
  - DIAG_CD
  - ICD_VER
  - SUPPLEMENTAL_CODE

FACILITY_DIAG_SUPPLEMENTAL_COLUMNS:
  - FACILITY_BID
  - DIAG_CD
  - ICD_VER
  - SUPPLEMENTAL_CODE

MEDICARE_MAO_DIAG_SUPPLEMENTAL_COLUMNS:
  - SUPPLEMENTAL_BID
  - DIAG_CODE
  - ICD_VERSION
  - DIAG_FLAG

PROFESSIONAL_COLUMNS:
  - ADJ_SEQ_NUM
  - CIM_ID_CD
  - PLAN_ID
  - PROD_ID_CD
  - CLM_PMT_STS_CD
  - CPT_AND_HCPCS_CD
  - MEMB_ID_CD
  - SERV_END_DT
  - SERV_FROM_DT
  - CLM_IND_NUM
  - POP_ID
  - HOME_PLAN_ID_CD
  - SOURCE_LOAD_MONTH

RISK_MEMBER_DIAG_COLUMNS:
  - RISK_MEMBER_ID
  - HOME_PLAN_ID_CD
  - MEMB_ID_CD
  - CLAIM_BID
  - CLM_ID_CD
  - ADJ_SEQ_NUM
  - CLM_IP_CD
  - SUPPLEMENTAL_DIAG_FLAG
  - DIAG_CD
  - FIRST_SERV_DT
  - LAST_SERV_DT
  - PROD_ID_CD
  - DIAG_TYPE_CD
  - DIAG_NUM
  - DIAG_CD
  - ICD_VER
  - DX_SOURCE_TYPE
  - SOURCE_LOAD_MONTH
  - CLAIM_NAME

RISK_MEMBER_COLUMNS:
  - RISK_MEMBER_ID
  - HOME_PLAN_ID_CD
  - MEMB_ID_CD
  - BHT_MEMB_ID
  - BRID_MEM_ID
  - PERSON_ID_CD
  - PERSON_ABSTRACT_ID
  - MBSS_STATE
  - MEMB_BRTH_DT
  - MEMB_GENDER_CD
  - MEMB_DEATH_DT
  - PLAN_ID
  - POP_ID
  - COVG_BEGIN_DT
  - COVG_END_DT
  - ACCT_CD
  - GRP_CD
  - SUBSCR_CD
  - ISSUER_ID
  - PROD_TYPE_CD
  - PHRM_PNFF_IND

LIS_STATUS_PART_D:
  - INSTITUTIONAL_STATUS_PART_C
  - INSTITUTIONAL_STATUS_PART_D
  - MEDICAID_STATUS
  - CSNP_STATUS
  - MEDICARE_NEMENROLLER_STATUS
  - AGE_GROUP
  - MODEL_SEGMENT_PART_C
  - MODEL_SEGMENT_PART_D

RISK_MEMBER_DIAG_MDS_COLUMNS:
  - MEMB_ID_CD
  - HOME_PLAN_ID_CD
  - PLAN_NAME

RISK_MEMBER_MDS_COLUMNS:
  - MEMB_ID_CD
  - HOME_PLAN_ID_CD
  - PLAN_NAME

SUPPLEMENTAL_MAR_RENAME_MAP:
  ESRD: ESRD_STATUS
  HBV: HBV_HOSPICE_MEDICAID_STATUS_FLAG: MEDICARE_NEMENROLLER_STATUS
  LTI_FLAG: INSTITUTIONAL_STATUS_PART_C
  RISK_ADJUSTMENT_AGE_GROUP_RANG: AGE_GROUP
  PART_D_LOW_INCOME_INDICATOR: LIS_STATUS_PART_D
  PART_D_LONG_TERM_INSTITUTIONAL_INDICATOR: INSTITUTIONAL_STATUS_PART_D
  #MEDICAID_DUAL_STATUS_CODE: MEDICAID_STATUS
  PART_D_LIS_ADJUSTMENT_FACTOR_TYPE: MODEL_SEGMENT_PART_D
  RISK_ADJUSTMENT_FACTOR_TYPE_CODE: MODEL_SEGMENT_PART_C
  ORIGINAL_REASON_FOR_ENTITLEMENT_CODE_OREC: OREC

RISK_MEMBER_OUTPUT_COLUMNS:
  - RISK_MEMBER_ID
  - HOME_PLAN_ID_CD
  - MEMB_ID_CD
  - MEMBER_AGE
  - MEMBER_GENDER
  - ISSUED_ID
  - CONTRACT_ID
  - INCL_PERF_RATE_CLAIM
  - INCL_PSRED_CLAIM
  - INCL_PHRM_CLAIM
  - RISK_MODEL_VERSION
  - RISK_MODEL_YEAR
  - RISK_MODEL_SEGMENT
  - YEAR_MONTH
  - DEMOG_SCORE
  - DIAG_CD_TO_HCC_JSON_LIST
  - HCC_TO_SCORE_JSON_LIST
  - HCC_SCORE
  - CLINICAL_PAYMENT_SCORE
  - INTERACTION_SCORE
  - NORMALIZATION_FACTOR
  - RISK_SCORE_RAW
  - RISK_SCORE_NORMALIZED
  - RISK_SCORE_PAYMENT_HCC
  - WEIGHTAGE
  - WEIGHTED_RISK_SCORE
  - TIME_PERIOD
  - SAS_MODEL_VERSION
  - CYCLE_RUN_DATE
  - CREATED_BY
  - CREATED_DATE

STAGE_LOAD_TABLES:
  - MEMBER
  - FACILITY
  - HEALTH_EVENTS
  - LAB
  - LOCATION
  - PHARMACY
  - PROFESSIONAL
  - PROFESSIONAL
  - QUALITY_EVENTS
  - DESIGNATED_PRIMARY_PROVIDER
  - VAS

PREREQUISITE_TABLES:
  - MEMBER_ID
  - RISK_PROV
  - RISK_LOCATION

QUALIFIED_FACILITY_COLUMNS:
  - CLAIM_BID
  - CIM_ID
  - CPT_AND_HCPCS_CD
  - PROC_MOD_CD
  - PROC_MOD_CD2
  - PROC_MOD_CD3
  - PROC_MOD_CD4
  - REIMB_TP_CD
  - TOT_UNITS_CNT
  - REV_CD
  - TOT_UNITS_VAL
  - ALIMD_AMT
  - COPAY_AMT
  - MEMBER_BID
  - POP_ID
  - ADMIT_SRC_CD
  - BRTHMG_CD
  - CLM_PMT_STS_CD
  - CLM_TP_CD
  - DISCH_STUS_CD
  - ITS_CLM_IND
  - TP_DF_BILL_CD
  - HOME_PLAN_ID_CD
  - MEMB_ID_CD
  - CIM_ID_CD
  - ADJ_SEQ_NUM
  - PROD_ID_CD
  - PLAN_NAME
  - DRG_CD
  - PLACE_OF_SERV_CD
  - FIRST_SERV_DT
  - LAST_SERV_DT
  - STMT_FROM_DT
  - STMT_THRU_DT
  - COIN_AMT
  - COPAY_AMT
  - DED_AMT
  - COB_TFL_AMT
  - PMT_AMT
  - QUALIFI_CLAIMS
  - INVALID_CPT_HCPCS
  - BUNDLED
  - PROGRAM
  - RISK_YEAR
  - LOAD_DATE
  - SOURCE_LOAD_MONTH
  - CREATED_DATE
  - CREATED_BY
  - UPDATED_DATE
  - UPDATED_BY

QUALIFIED_PROFFESIONAL_COLUMNS:
  - CLAIM_BID
  - CIM_IN_NUM
  - MEMBER_BID
  - POP_ID
  - CLM_PMT_STS_CD
  - CLM_TP_CD
  - DISCH_STUS_CD
  - ITS_CLM_IND
  - TP_DF_BILL_CD
  - HOME_PLAN_ID_CD
  - MEMB_ID_CD
  - CLM_ID_CD
  - ADJ_SEQ_NUM
  - PROD_ID_CD
  - PLAN_NAME
  - DRG_CD
  - PLACE_OF_SERV_CD
  - CPT_AND_HCPCS_CD
  - PROC_MOD_CD
  - PROC_MOD_CD2
  - PROC_MOD_CD3
  - PROC_MOD_CD4
  - REIMB_TP_CD
  - TOT_UNITS_CNT
  - REV_CD
  - ADMIT_SRC_CD
  - BRTHMG_CD
  - TOT_UNITS_VAL
  - FIRST_SERV_DT
  - LAST_SERV_DT
  - STMT_FROM_DT
  - STMT_THRU_DT
  - ALIMD_AMT
  - COIN_AMT
  - COPAY_AMT
  - DED_AMT
  - COB_TFL_AMT
  - PMT_AMT
  - QUALIFI_CLAIMS
  - INVALID_CPT_HCPCS
  - BUNDLED
  - PROGRAM
  - RISK_YEAR
  - LOAD_DATE
  - SOURCE_LOAD_MONTH
  - CREATED_DATE
  - CREATED_BY
  - UPDATED_DATE
  - UPDATED_BY

QUALIFIED_SUPPLEMENTAL_MAD_COLUMNS:
  - CLAIM_BID
  - CIM_IN_NUM
  - MEMBER_BID
  - POP_ID
  - CLM_TP_CD
  - MEMBER_BID
  - POP_ID
  - PSEUDO_CLAIM_TYPE
  - CLM_PMT_STS_CD
  - CLM_TP_CD
  - DISCH_STUS_CD
  - ITS_CLM_IND
  - TP_DF_BILL_CD
  - HOME_PLAN_ID_CD
  - MEMB_ID_CD
  - CIM_ID_CD
  - ADJ_SEQ_NUM
  - PROD_ID_CD
  - PLAN_NAME
  - DRG_CD
  - PLACE_OF_SERV_CD
  - CPT_AND_HCPCS_CD
  - PROC_MOD_CD
  - PROC_MOD_CD2
  - PROC_MOD_CD3
  - PROC_MOD_CD4
  - REIMB_TP_CD
  - TOT_UNITS_CNT
  - REV_CD
  - ADMIT_SRC_CD
  - BRTHMG_CD
  - TOT_UNITS_VAL
  - FIRST_SERV_DT
  - LAST_SERV_DT
  - STMT_FROM_DT
  - STMT_THRU_DT
  - ALIMD_AMT
  - COIN_AMT
  - COPAY_AMT
  - DED_AMT
  - COB_TFL_AMT
  - PMT_AMT
  - QUALIFI_CLAIMS
  - INVALID_CPT_HCPCS
  - BUNDLED
  - PROGRAM
  - RISK_YEAR
  - LOAD_DATE
  - SOURCE_LOAD_MONTH
  - CREATED_DATE
  - CREATED_BY
  - UPDATED_DATE
  - UPDATED_BY

REP_VISIT_TYPE_RBCS_COLUMNS:
  - VISIT_TYPE_ID
  - HCPCS_CD
  - HCPCS_CD_ADJ_DT
  - HCPCS_CD_END_DT

REP_PLACE_OF_SERVICE_TUB_COLUMNS:
  - TYPE_OF_BILL_CD
  - PLACE_OF_SERVICE_CD

MEMBER_PERSISTENCE_HCC_COLUMNS:
  - MEMBER_BID
  - HOME_PLAN_ID_CD
  - RISK_MODEL_IYEAR
  - RISK_MODEL_TYPE
  - RISK_MODEL_VERSION
  - SAS_MODEL_VERSION
  - CC_DESCRIPTION
  - CHRONIC_HCC
  - DX_SOURCE
  - CLAIM_TYPE
  - CLAIM_BID
  - CLAIM_DATE
  - DIAG_CD
  - RISK_YEAR
  - HRA
  - HOME_HRA
  - CYCLE_RUN
  - ACTIVE_IND
  - CREATED_DATE
  - CREATED_BY
  - UPDATED_DATE
  - UPDATED_BY

RISK_MEMBER_HCC_COLUMNS:
  - MEMBER_BID
  - HOME_PLAN_ID_CD
  - RISK_MODEL_IYEAR
  - RISK_MODEL_TYPE
  - RISK_MODEL_VERSION
  - RISK_MODEL_SEGMENT
  - SAS_MODEL_VERSION
  - MEMBER_AGE
  - MEMBER_GENDER
  - RISK_TYPE_ID
  - RISK_TYPE_DETAIL_ID
  - SUPPRESSION_IND
  - METHOD_ID
  - ADJ_COEFF_SCORE
  - COEFF_SCORE
  - CONFIDENCE_FACTOR
  - COMBINED_CONFIDENCE_FACTOR
  - CHRONIC_HCC
  - DX_SOURCE
  - GAF_STATUS
  - CLAIM_TYPE
  - CLAIM_BID
  - CLAIM_DATE
  - DIAG_CD
  - RISK_YEAR
  - HRA
  - CYCLE_RUN
  - ACTIVE_IND
  - CREATED_DATE
  - CREATED_BY
  - UPDATED_DATE
  - UPDATED_BY

RISK_MEMBER_HCC_SUMMARY_COLUMNS:
  - MEMBER_BID
  - HOME_PLAN_ID_CD
  - RISK_MODEL_IYEAR
  - RISK_MODEL_TYPE
  - RISK_MODEL_VERSION
  - RISK_MODEL_SEGMENT
  - SAS_MODEL_VERSION
  - MEMBER_GENDER
  - MEMBER_AGE
  - RISK_TYPE_ID
  - RISK_TYPE_DETAIL_ID
  - RISK_TYPE_DETAIL_DESC
  - SUPPRESSION_IND
  - METHOD_ID
  - ADJ_COEFF_SCORE
  - COEFF_SCORE
  - METHOD_CONFIDENCE_FACTOR
  - COMBINED_CONFIDENCE_FACTOR
  - CHRONIC_HCC
  - DX_SOURCE
  - GAF_STATUS
  - RISK_YEAR
  - HRA
  - HOME_HRA
  - CYCLE_RUN
  - ACTIVE_IND
  - CREATED_DATE
  - CREATED_BY
  - UPDATED_DATE
  - UPDATED_BY

RISK_MEMBER_HCC_SUMMARY_COLUMNS:
  - MEMBER_BID
  - HOME_PLAN_ID_CD
  - RISK_MODEL_YEAR
  - RISK_MODEL_TYPE
  - RISK_MODEL_VERSION
  - RISK_MODEL_SEGMENT
  - SAS_MODEL_VERSION
  - MEMBER_GENDER
  - MEMBER_AGE
  - RISK_TYPE_ID
  - RISK_TYPE_DETAIL_ID
  - RISK_TYPE_DETAIL_DESC
  - SUPPRESSION_IND
  - METHOD_ID
  - ADJ_COEFF_SCORE
  - COEFF_SCORE
  - METHOD_CONFIDENCE_FACTOR
  - COMBINED_CONFIDENCE_FACTOR
  - CHRONIC_HCC
  - DX_SOURCE
  - GAF_STATUS
  - RISK_YEAR
  - HRA
  - HOME_HRA
  - CYCLE_RUN
  - ACTIVE_IND
  - CREATED_DATE
  - CREATED_BY
  - UPDATED_DATE
  - UPDATED_BY

METHODID_ICD_PROC_COLUMNS:
  - PRIM_PROC_CD
  - ICD_SURG_PROC_1
  - ICD_SURG_PROC_2
  - ICD_SURG_PROC_3
  - ICD_SURG_PROC_4
  - ICD_SURG_PROC_5
