-- Ingestion Layer Tables
-- These tables receive raw data from source systems

CREATE TABLE IF NOT EXISTS $[catalog].$[schema].ingestion_stage_member (
    HOME_PLAN_ID_CD STRING,
    MEMB_ID_CD STRING,
    DEID_MEM_ID STRING,
    PERSON_ID_CD STRING,
    ALT_MEM_ID STRING,
    MBRS_HM_LAST STRING,
    MBRS_HM_FIRST STRING,
    MBRS_STREET1 STRING,
    MBRS_STREET2 STRING,
    MBRS_CITY STRING,
    MBRS_STATE STRING,
    MBRS_CNHI_COUNTY_CD STRING,
    MBRS_CNHI_PRIM_ZIP_CD STRING,
    MBRS_PRIM_PHN_NUM STRING,
    MBRS_PRIM_EMAIL STRING,
    MBRS_PREF_CONTACT_CD STRING,
    MEMB_BRTH_DT STRING,
    MEMB_GENDER_CD STRING,
    MEMB_CNFRMT_CD STRING,
    MEMB_SMOKNG_STS STRING,
    MEMB_DEATH_DT STRING,
    SEG1_ID STRING,
    SEG2_ID STRING,
    SEG3_ID STRING,
    SEG4_ID STRING,
    SEG5_ID STRING,
    SEG6_ID STRING,
    SEG7_ID STRING,
    SEG8_ID STRING,
    SEG9_ID STRING,
    SEG10_ID STRING,
    MBRS_IM_PHOILE STRING,
    MBRS_CNHI_PRIM_ZIP_PUSHOUR STRING,
    PLAN_ID STRING,
    CREATED_DATE TIMESTAMP,
    CREATED_BY STRING,
    UPDATED_DATE TIMESTAMP,
    UPDATED_BY STRING,
    VALIDATED_TIMESTAMP TIMESTAMP
)
USING DELTA;

CREATE TABLE IF NOT EXISTS $[catalog].$[schema].ingestion_stage_member_enrollment (
    HOME_PLAN_ID_CD STRING,
    MEMB_ID_CD STRING,
    COVRG_BEGIN_DT DATE,
    COVRG_END_DT DATE,
    PROD_TYPE STRING,
    PLAN_NAME STRING,
    SOURCE_LOAD_MONTH STRING,
    CREATED_DATE TIMESTAMP,
    CREATED_BY STRING,
    UPDATED_DATE TIMESTAMP,
    UPDATED_BY STRING
)
USING DELTA;

CREATE TABLE IF NOT EXISTS $[catalog].$[schema].ingestion_stage_medical_claims (
    HOME_PLAN_ID_CD STRING,
    MEMB_ID_CD STRING,
    CLAIM_BID BIGINT,
    CLM_ID_CD STRING,
    CLM_TP_CD STRING,
    FIRST_SERV_DT DATE,
    LAST_SERV_DT DATE,
    PROD_ID_CD STRING,
    SOURCE_LOAD_MONTH STRING,
    CREATED_DATE TIMESTAMP,
    CREATED_BY STRING,
    UPDATED_DATE TIMESTAMP,
    UPDATED_BY STRING
)
USING DELTA;

CREATE TABLE IF NOT EXISTS $[catalog].$[schema].ingestion_stage_professional_diag (
    CLAIM_BID BIGINT,
    CLM_ID_CD STRING,
    DIAG_CD STRING,
    DIAG_TYPE STRING,
    DIAG_NUM INT,
    ICD_VER INT,
    SOURCE_LOAD_MONTH STRING,
    CREATED_DATE TIMESTAMP,
    CREATED_BY STRING,
    UPDATED_DATE TIMESTAMP,
    UPDATED_BY STRING
)
USING DELTA;

CREATE TABLE IF NOT EXISTS $[catalog].$[schema].ingestion_stage_facility_diag (
    CLAIM_BID BIGINT,
    CLM_ID_CD STRING,
    DIAG_CD STRING,
    DIAG_TYPE STRING,
    DIAG_NUM INT,
    ICD_VER INT,
    SOURCE_LOAD_MONTH STRING,
    CREATED_DATE TIMESTAMP,
    CREATED_BY STRING,
    UPDATED_DATE TIMESTAMP,
    UPDATED_BY STRING
)
USING DELTA;

CREATE TABLE IF NOT EXISTS $[catalog].$[schema].ingestion_stage_mmr (
    HOME_PLAN_ID_CD STRING,
    MEMB_ID_CD STRING,
    OREC STRING,
    ESRD_STATUS STRING,
    LIS_STATUS_PART_D STRING,
    INSTITUTIONAL_STATUS_PART_C STRING,
    INSTITUTIONAL_STATUS_PART_D STRING,
    MEDICAID_STATUS STRING,
    CSNP_STATUS STRING,
    MEDICARE_NEWENROLLEE_STATUS STRING,
    SOURCE_LOAD_MONTH STRING,
    CREATED_DATE TIMESTAMP,
    CREATED_BY STRING,
    UPDATED_DATE TIMESTAMP,
    UPDATED_BY STRING
)
USING DELTA;
