-- Transformation and Curation Layer Tables
-- These tables contain transformed and curated business data
-- Tables are organized in alphabetical order

CREATE TABLE IF NOT EXISTS ${catalog}.${schema_transformation}.designated_primary_provider (
    DESIGNATED_PRIMARY_PROVIDER_BID BIGINT GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1) NOT NULL,
    HOME_PLAN_ID_CD VARCHAR(3) NOT NULL,
    MEMBER_BID BIGINT NOT NULL,
    START_DATE DATE NOT NULL,
    END_DATE DATE NOT NULL,
    PROVIDER_BID BIGINT NOT NULL,
    PROV_ID VARCHAR(),
    SES1_ID VARCHAR(),
    SES2_ID VARCHAR(),
    LOAD_DATE TIMESTAMP NOT NULL,
    SOURCE_LOAD_MONTH VARCHAR() NOT NULL,
    CREATED_DATE TIMESTAMP,
    CREATED_BY VARCHAR(::),
    UPDATED_DATE TIMESTAMP,
    UPDATED_BY VARCHAR(::)
)
USING DELTA
WITH SERDEPROPERTIES(
    'delta.columnMapping.mode' = 'name',
    'delta.enableIcebergCompat2' = 'true',
    'delta.universalFormat.enabledFormat' = 'iceberg')
PARTITIONED BY (SOURCE_LOAD_MONTH, HOME_PLAN_ID_CD);

CREATE TABLE IF NOT EXISTS ${catalog}.${schema_transformation}.facility_detail (
    FACILITY_BID BIGINT NOT NULL,
    CLM_ID_CD VARCHAR(:) NOT NULL,
    CLM_LN_NUM DECIMAL(::,),
    ADJ_SEQ_NUM DECIMAL(::,),
    HOME_PLAN_ID_CD VARCHAR(::) NOT NULL,
    SHI_PROV_ID VARCHAR(),
    PROC_MOD_CD1 VARCHAR(),
    PROC_MOD_CD2 VARCHAR(),
    PROC_MOD_CD3 VARCHAR(),
    PROC_MOD_CD4 VARCHAR(),
    REEMP_FX_CD VARCHAR(),
    REV_CD VARCHAR(),
    REV_DESC VARCHAR(::),
    SERV_FROM_DT DATE,
    SERV_END_DT DATE,
    ALSMD_AMT DECIMAL(::,::),
    PMT_AMT DECIMAL(::,::),
    QTY_AMT VARCHAR(),
    LOAD_DATE TIMESTAMP NOT NULL,
    SOURCE_LOAD_MONTH VARCHAR() NOT NULL,
    CREATED_DATE TIMESTAMP,
    CREATED_BY VARCHAR(::),
    UPDATED_DATE TIMESTAMP,
    UPDATED_BY VARCHAR(::),
    VALIDATED_TIMESTAMP TIMESTAMP
)
USING DELTA
WITH SERDEPROPERTIES(
    'delta.columnMapping.mode' = 'name',
    'delta.enableIcebergCompat2' = 'true',
    'delta.universalFormat.enabledFormat' = 'iceberg')
PARTITIONED BY (SOURCE_LOAD_MONTH, HOME_PLAN_ID_CD);

CREATE TABLE IF NOT EXISTS ${catalog}.${schema_transformation}.facility_diag (
    FACILITY_BID BIGINT NOT NULL,
    CLM_ID_CD VARCHAR() NOT NULL,
    ADJ_SEQ_NUM DECIMAL(::,),
    HOME_PLAN_ID_CD VARCHAR(::) NOT NULL,
    DIAG_TYPE_CD VARCHAR(),
    DIAG_NUM VARCHAR() NOT NULL,
    DIAG_CD VARCHAR(),
    LOAD_DATE TIMESTAMP NOT NULL,
    SOURCE_LOAD_MONTH VARCHAR() NOT NULL,
    CREATED_DATE TIMESTAMP,
    CREATED_BY VARCHAR(::),
    UPDATED_DATE TIMESTAMP,
    UPDATED_BY VARCHAR(::),
    VALIDATED_TIMESTAMP TIMESTAMP
)
USING DELTA
WITH SERDEPROPERTIES(
    'delta.columnMapping.mode' = 'name',
    'delta.enableIcebergCompat2' = 'true',
    'delta.universalFormat.enabledFormat' = 'iceberg')
PARTITIONED BY (SOURCE_LOAD_MONTH, HOME_PLAN_ID_CD);

CREATE TABLE IF NOT EXISTS ${catalog}.${schema_transformation}.facility_header (
    FACILITY_BID BIGINT NOT NULL,
    MEMBERS_BID BIGINT NOT NULL,
    INSRER_ID DECIMAL(::,),
    CLM_TP_CD VARCHAR(),
    CLM_ID_CD VARCHAR(),
    TRCBLE_FIELD_CD VARCHAR(),
    HOME_PLAN_ID_CD VARCHAR(::) NOT NULL,
    ICD_CLM_IND_IND VARCHAR(),
    CLM_BID_IND VARCHAR(),
    TP_OF_BILL_CD VARCHAR(),
    FIRST_SERV_DT DATE,
    LAST_SERV_DT DATE,
    STMF_FROM_DT DATE,
    STMF_TO_DT DATE,
    CLM_PATD_DT DATE,
    CLM_PMT_STS_CD VARCHAR(),
    LOCATION_ID VARCHAR(),
    BILL_PROV_ID_CD VARCHAR(::),
    BILL_PLAN_PROV_SPLC_CD VARCHAR(::),
    BNDRNG_PROV_ID_CD VARCHAR(::),
    BNDRNG_PROV_SPLC_CD VARCHAR(),
    BNDRNG_PLAN_PROV_SPLC_CD VARCHAR(::),
    BNDRNG_PROV_ZIP_CD VARCHAR(),
    BNDRNG_PROV_SIP_CD VARCHAR(),
    AGE_YR DECIMAL(::,),
    HEMD_SENDER_CD VARCHAR(),
    PROC_ID_CD VARCHAR(::),
    POP_ID VARCHAR(),
    CLAIM_CD_VER VARCHAR(),
    ICD_BURQ_PROC_1 VARCHAR(),
    ICD_VER_1 VARCHAR(),
    ICD_BURQ_PROC_2 VARCHAR(),
    ICD_VER_2 VARCHAR(),
    ICD_BURQ_PROC_3 VARCHAR(),
    ICD_VER_3 VARCHAR(),
    ICD_BURQ_PROC_4 VARCHAR(),
    ICD_VER_4 VARCHAR(),
    ICD_BURQ_PROC_5 VARCHAR(),
    ICD_VER_5 VARCHAR(),
    ICD_BURQ_PROC_6 VARCHAR(),
    ICD_VER_6 VARCHAR(),
    DISCH_STUS_CD VARCHAR(),
    BRTHWMD_CD VARCHAR(),
    ALSMD_AMT DECIMAL(::,::),
    COTN_AMT DECIMAL(::,::),
    DDCTN_AMT DECIMAL(::,),
    DED_AMT DECIMAL(::,::),
    OOB_FYI_AMT DECIMAL(::,::),
    PMT_AMT DECIMAL(::,::),
    VOID_IND VARCHAR(),
    ADVNC_ST DATE,
    HA_PROV_TYPE VARCHAR(),
    BILL_PROV_CD VARCHAR(),
    LOAD_DATE TIMESTAMP NOT NULL,
    SOURCE_LOAD_MONTH VARCHAR() NOT NULL,
    CREATED_DATE TIMESTAMP,
    CREATED_BY VARCHAR(::),
    UPDATED_DATE TIMESTAMP,
    UPDATED_BY VARCHAR(::),
    VALIDATED_TIMESTAMP TIMESTAMP,
    CONSTRAINT PK_FACILITY PRIMARY KEY (FACILITY_BID)
)
USING DELTA
WITH SERDEPROPERTIES(
    'delta.columnMapping.mode' = 'name',
    'delta.enableIcebergCompat2' = 'true',
    'delta.universalFormat.enabledFormat' = 'iceberg')
PARTITIONED BY (SOURCE_LOAD_MONTH, HOME_PLAN_ID_CD);

CREATE TABLE IF NOT EXISTS ${catalog}.${schema_transformation}.health_events (
    HEALTH_EVENT_BID BIGINT GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1) NOT NULL,
    HOME_PLAN_ID_CD VARCHAR(3) NOT NULL,
    MEMBER_BID BIGINT NOT NULL,
    MEMB_ID_CD VARCHAR(22) NOT NULL,
    PROGRAM_TYPE VARCHAR(3) NOT NULL,
    PROGRAM_NAME VARCHAR(50) NOT NULL,
    PROGRAM_DESC VARCHAR(150) NOT NULL,
    COND_CAT VARCHAR(50) NOT NULL,
    COND_VER VARCHAR(10) NOT NULL,
    PROCESS_DATE DATE NOT NULL,
    PROC_START_DT DATE,
    PROC_END_DT DATE,
    RECORD_ID VARCHAR(50) NOT NULL,
    RECORD_SUB_ID VARCHAR(50) NOT NULL,
    PERCENT_HEIGHT DECIMAL(7,5) NOT NULL,
    LOAD_DATE TIMESTAMP NOT NULL,
    SOURCE_LOAD_MONTH VARCHAR(7) NOT NULL,
    CREATED_DATE TIMESTAMP,
    CREATED_BY VARCHAR(255),
    UPDATED_DATE TIMESTAMP,
    UPDATED_BY VARCHAR(255)
)
USING DELTA;

CREATE TABLE IF NOT EXISTS ${catalog}.${schema_transformation}.lab (
    LAB_BID BIGINT GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1),
    HOME_PLAN_ID_CD VARCHAR(3) NOT NULL,
    CLM_ID_CD VARCHAR() NOT NULL,
    MEMBER_BID BIGINT NOT NULL,
    MEMB_ID_CD VARCHAR(22) NOT NULL,
    ORDERING_PROV_NPI VARCHAR(),
    ORDERING_PROV_NM_LAST VARCHAR(),
    ORDERING_PROV_NM_FIRST VARCHAR(),
    ORDERING_PROV_ZIP VARCHAR(),
    PERFORM_PROV_NPI VARCHAR(),
    DX_CD VARCHAR(6) NOT NULL,
    SERV_DT DATE,
    LAB_RESULT_CD VARCHAR(::),
    LAB_RESULT_VAL VARCHAR() NOT NULL,
    LAB_RESULT_FLAG_CD CHAR(),
    LOAD_DATE TIMESTAMP NOT NULL,
    SOURCE_LOAD_MONTH VARCHAR() NOT NULL,
    CREATED_DATE TIMESTAMP,
    CREATED_BY VARCHAR(::),
    UPDATED_DATE TIMESTAMP,
    UPDATED_BY VARCHAR(::)
)
USING DELTA
WITH SERDEPROPERTIES(
    'delta.columnMapping.mode' = 'name',
    'delta.enableIcebergCompat2' = 'true',
    'delta.universalFormat.enabledFormat' = 'iceberg')
PARTITIONED BY (SOURCE_LOAD_MONTH, HOME_PLAN_ID_CD);

CREATE TABLE IF NOT EXISTS ${catalog}.${schema_transformation}.location (
    LOCATION_BID BIGINT NOT NULL,
    HOME_PLAN_ID_CD VARCHAR(3) NOT NULL,
    BILL_PROVIDER_ID BIGINT NOT NULL,
    LOCATION_ADDRESS_ID SMALLINT NOT NULL,
    LOCATION_ADDRESS VARCHAR(),
    LOCATION_NAME VARCHAR(100),
    LOCATION_USER_GROUP VARCHAR(),
    LOCATION_STREET1 VARCHAR(),
    LOCATION_STREET2 VARCHAR(),
    LOCATION_CITY VARCHAR(35),
    LOCATION_COUNTY_CD VARCHAR(),
    LOCATION_STATE VARCHAR(2),
    LOCATION_ZIP VARCHAR(9),
    LOCATION_ZIP_PLUS4 VARCHAR(),
    LOCATION_PHONE VARCHAR(9),
    LOCATION_FAX VARCHAR(),
    SES1_ID VARCHAR(),
    SES2_ID VARCHAR(),
    SES3_ID VARCHAR(),
    SES4_ID VARCHAR(),
    SES5_ID VARCHAR(),
    SES6_ID VARCHAR(),
    SES7_ID VARCHAR(),
    SES8_ID VARCHAR(),
    SES9_ID VARCHAR(),
    SES10_ID VARCHAR(),
    LOAD_DATE TIMESTAMP NOT NULL,
    SOURCE_LOAD_MONTH VARCHAR() NOT NULL,
    CREATED_DATE TIMESTAMP,
    CREATED_BY VARCHAR(::),
    UPDATED_DATE TIMESTAMP,
    UPDATED_BY VARCHAR(::),
    CONSTRAINT PK_LOCATION PRIMARY KEY (LOCATION_BID, HOME_PLAN_ID_CD, BILL_PROVIDER_ID, LOCATION_ADDRESS_ID)
)
USING DELTA
WITH SERDEPROPERTIES(
    'delta.columnMapping.mode' = 'name',
    'delta.enableIcebergCompat2' = 'true',
    'delta.universalFormat.enabledFormat' = 'iceberg')
PARTITIONED BY (SOURCE_LOAD_MONTH, HOME_PLAN_ID_CD);

CREATE TABLE IF NOT EXISTS ${catalog}.${schema_transformation}.mao_id (
    SUPPLEMENTAL_BID BIGINT GENERATED ALWAYS AS IDENTITY (START WITH 9900000000000001 INCREMENT BY 1),
    MBT VARCHAR(11) NOT NULL,
    MEMBER_ID VARCHAR(2) NOT NULL,
    ICD_VER VARCHAR(1) NOT NULL
)
USING DELTA;

CREATE TABLE IF NOT EXISTS ${catalog}.${schema_transformation}.medicare_mbi_xwalk (
    MBI VARCHAR(11) NOT NULL,
    MEMBER_ID BIGINT NOT NULL,
    MEMB_ID_CD VARCHAR(22),
    HOME_PLAN_PRO_ID VARCHAR(14),
    HOME_PLAN_ID_CD VARCHAR(1),
    CREATED_DATE TIMESTAMP,
    CREATED_BY VARCHAR(255),
    UPDATED_DATE TIMESTAMP,
    UPDATED_BY VARCHAR(255)
)
USING DELTA;

CREATE TABLE IF NOT EXISTS ${catalog}.${schema_transformation}.medicare_mor_part1_type0 (
    MBI VARCHAR(11) NOT NULL,
    MEMBER_ID BIGINT NOT NULL,
    MEMB_ID_CD VARCHAR(22),
    HOME_PLAN_PRO_ID VARCHAR(14),
    HOME_PLAN_ID_CD VARCHAR(1),
    CREATED_DATE TIMESTAMP,
    CREATED_BY VARCHAR(255),
    UPDATED_DATE TIMESTAMP,
    UPDATED_BY VARCHAR(255)
)
USING DELTA
TBLPROPERTIES(
    'delta.columnMapping.mode' = 'name',
    'delta.enableIcebergCompatV2' = 'true',
    'delta.universalFormat.enableFormats' = 'iceberg');

CREATE TABLE IF NOT EXISTS ${catalog}.${schema_transformation}.medicare_mor_part1_type2 (
    MBI VARCHAR(11) NOT NULL,
    MEMBER_ID BIGINT NOT NULL,
    MEMB_ID_CD VARCHAR(22),
    HOME_PLAN_PRO_ID VARCHAR(14),
    HOME_PLAN_ID_CD VARCHAR(1),
    CREATED_DATE TIMESTAMP,
    CREATED_BY VARCHAR(255),
    UPDATED_DATE TIMESTAMP,
    UPDATED_BY VARCHAR(255)
)
USING DELTA;

CREATE TABLE IF NOT EXISTS ${catalog}.${schema_transformation}.member (
    BHI_MEMB_ID VARCHAR(22) NOT NULL,
    DEID_MEM_ID VARCHAR(80),
    PERSON_ID_CD VARCHAR(22) NOT NULL,
    ALT_MEM_ID VARCHAR(22),
    MBRS_HC_LAST VARCHAR(25),
    MBRS_HM_INTIALE VARCHAR(25),
    MEMB_BIRTH_DT DATE NOT NULL,
    MEMB_DEATH_DT DATE,
    MEMB_GENDER_CD CHAR(1) NOT NULL,
    MEMB_CHFMFT_CD VARCHAR(3) NOT NULL,
    MBRS_STREET1 VARCHAR(70),
    MBRS_STREET2 VARCHAR(70),
    MBRS_CITY VARCHAR(35),
    MBRS_STATE VARCHAR(2),
    MBRS_ZIP VARCHAR(5),
    MBRS_CRMT_PRIM_ZIP_CD VARCHAR(5),
    MBRS_CRMT_PRIM_ZIP_PLUS4 VARCHAR(4),
    MBRS_PRIM_PHN VARCHAR(10),
    MBRS_PRIM_EMAIL VARCHAR(70),
    MBRS_PREF_CONTACT_CD VARCHAR(2),
    MEMB_SMOKNG_STS CHAR(1),
    SEG1_ID VARCHAR(60),
    SEG2_ID VARCHAR(60),
    SEG3_ID VARCHAR(60),
    SEG4_ID VARCHAR(60),
    SEG5_ID VARCHAR(60),
    SEG6_ID VARCHAR(60),
    SEG7_ID VARCHAR(60),
    SEG8_ID VARCHAR(60),
    SEG9_ID VARCHAR(60),
    SEG10_ID VARCHAR(60),
    LOAD_DATE TIMESTAMP NOT NULL,
    SOURCE_LOAD_MONTH VARCHAR(7) NOT NULL,
    CREATED_DATE TIMESTAMP,
    CREATED_BY VARCHAR(255),
    UPDATED_DATE TIMESTAMP,
    UPDATED_BY VARCHAR(255),
    CONSTRAINT pk_member_primary KEY (HOME_PLAN_ID_CD, MEMB_ID_CD, DEID_MEM_ID)
)
USING DELTA;

CREATE TABLE IF NOT EXISTS ${catalog}.${schema_transformation}.member_eligibility (
    HMEMB_FILO_BID BIGINT GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1) NOT NULL,
    HOME_PLAN_ID_CD VARCHAR(3) NOT NULL,
    MEMBER_BID BIGINT NOT NULL,
    MEMB_ID_CD VARCHAR(22) NOT NULL,
    MEMB_IP_CD VARCHAR(22) NOT NULL,
    ENR_MEMB_ID_CD VARCHAR(),
    COVPRG_BEGIN_DT DATE NOT NULL,
    COVPRG_END_DT DATE NOT NULL,
    ACCT_CD VARCHAR(14) NOT NULL,
    PROD_CD VARCHAR(::),
    SUBGRP_CD VARCHAR(),
    PROD_ID_CD VARCHAR(15),
    PROD_TYPE_CD VARCHAR(3) NOT NULL,
    GROUP_SIZE_CD VARCHAR(2) NOT NULL,
    LINE_OF_BUSINESS_CD VARCHAR(2) NOT NULL,
    MARKET_CD VARCHAR() NOT NULL,
    PRODUCT_LINE_CD VARCHAR(2) NOT NULL,
    EMPLOYEE_STATUS_CD VARCHAR(2) NOT NULL,
    EMPLOYEE_TYPE_CD VARCHAR(::) NOT NULL,
    FUNDING_ARRANGEMENT_CD VARCHAR(2) NOT NULL,
    BARGAINING_STATUS_CD VARCHAR() NOT NULL,
    BARGAINING_STATUS_EFF_DATE DATE NOT NULL,
    CONTRACT_ID VARCHAR(),
    CONTRACT_EFFECTIVE_DT DATE NOT NULL,
    CONTRACT_END_DT_DATE DATE NOT NULL,
    NAICS_CD VARCHAR(),
    SUB_ID VARCHAR(::) NOT NULL,
    MEMB_BLTHRSRY_CD VARCHAR(2) NOT NULL,
    PRIMARY_BRFT_IND CHAR() NOT NULL,
    MED_BRFT_IND CHAR() NOT NULL,
    CHD_BRFT_IND CHAR() NOT NULL,
    MLB_BRFT_IND CHAR() NOT NULL,
    CD_BRFT_IND CHAR() NOT NULL,
    DWP_BRFT_IND CHAR() NOT NULL,
    POP_ID VARCHAR() NOT NULL,
    EXPCT_IND VARCHAR(3) NOT NULL,
    RATING_AREA VARCHAR(),
    PFEM_AMT DECIMAL(::,::) NOT NULL,
    CBR_INDICATOR VARCHAR() NOT NULL,
    METAL VARCHAR() NOT NULL,
    EMROLL_PERIOD_ACT VARCHAR(),
    MEMB_MED_COL_CD CHAR() NOT NULL,
    MEMB_MED_CDR_CD CHAR() NOT NULL,
    SES1_ID VARCHAR(::),
    SES2_ID VARCHAR(::),
    SES3_ID VARCHAR(::),
    SES4_ID VARCHAR(::),
    SES5_ID VARCHAR(::),
    SES6_ID VARCHAR(::),
    SES7_ID VARCHAR(::),
    SES8_ID VARCHAR(::),
    SES9_ID VARCHAR(::),
    SES10_ID VARCHAR(::),
    SES11_ID VARCHAR(::),
    SES12_ID VARCHAR(::),
    SES13_ID VARCHAR(::),
    SES14_ID VARCHAR(::),
    HA_MCD_IND VARCHAR(),
    HA_DAF3 VARCHAR(),
    HA_DAF4 VARCHAR(),
    HA_LIT_FLAG VARCHAR(),
    HA_DP5_RISPRFQ_CD VARCHAR(),
    HA_RAPP_CD VARCHAR(),
    HA_FRAILTY_FACTOR VARCHAR(),
    HA_HCC_INDICATOR VARCHAR(),
    LOAD_DATE TIMESTAMP NOT NULL,
    SOURCE_LOAD_MONTH VARCHAR() NOT NULL,
    CREATED_DATE TIMESTAMP,
    CREATED_BY VARCHAR(::),
    UPDATED_DATE TIMESTAMP,
    UPDATED_BY VARCHAR(::),
    VALIDATED_TIMESTAMP TIMESTAMP
)
USING DELTA
WITH SERDEPROPERTIES(
    'delta.columnMapping.mode' = 'name',
    'delta.enableIcebergCompat2' = 'true',
    'delta.universalFormat.enabledFormat' = 'iceberg')
PARTITIONED BY (SOURCE_LOAD_MONTH, HOME_PLAN_ID_CD);

CREATE TABLE IF NOT EXISTS ${catalog}.${schema_transformation}.member_enrollment (
    ACCT_CD VARCHAR(14) NOT NULL,
    GRP_CD VARCHAR(14),
    SUBGRP_CD VARCHAR(10),
    PROD_ID_CD VARCHAR(15),
    PROD_TYPE_CD VARCHAR(3) NOT NULL,
    GROUP_SIZE_CD VARCHAR(2) NOT NULL,
    NATIONAL_ACCOUNT_IND CHAR(1) NOT NULL,
    LINE_OF_BUSINESS_CD VARCHAR(2) NOT NULL,
    MEMBER_STATE_FIPS_CD VARCHAR(2) NOT NULL,
    PRODUCT_LINE_CD VARCHAR(2) NOT NULL,
    EMPLOYEE_STATUS_CD VARCHAR(2) NOT NULL,
    EMPLOYEE_TYPE_CD VARCHAR(2) NOT NULL,
    FUNDING_ARRANGEMENT_CD VARCHAR(2) NOT NULL,
    BARGAINING_STATUS_CD VARCHAR(2) NOT NULL,
    BARGAINING_STATUS_EFF_DT VARCHAR(2) NOT NULL,
    CONTRACT_ID VARCHAR(9),
    CONTRACT_EFFECTIVE_DT DATE NOT NULL,
    CONTRACT_END_DT DATE NOT NULL,
    NAICS_CD VARCHAR(6),
    INQBSTRY VARCHAR(4),
    SUB_ID VARCHAR(22) NOT NULL,
    MEMB_HIERARCHY_CD VARCHAR(2) NOT NULL,
    PRIMARY_BRFT_IND CHAR(1) NOT NULL,
    CDHF_BRFT_IND CHAR(1) NOT NULL,
    HSPLI_BRFT_IND CHAR(1) NOT NULL,
    MLI_BRFT_IND CHAR(1) NOT NULL,
    CD_BRFT_IND CHAR(1) NOT NULL,
    DENT_BRFT_IND CHAR(1) NOT NULL,
    POP_ID VARCHAR(2) NOT NULL,
    EXPCT_IND VARCHAR(3) NOT NULL,
    RATING_AREA VARCHAR(15),
    PMEM_AMT DECIMAL(8,2) NOT NULL,
    PMEM_AMT_OFFSET DECIMAL(8,2) NOT NULL,
    METAL VARCHAR(12) NOT NULL,
    EHROLL_PERIOD_ACT VARCHAR(6),
    MEMB_MED_CDR_CD CHAR(1) NOT NULL,
    MEMB_PHARMACY_CDR_CD CHAR(1) NOT NULL,
    SEG1_ID VARCHAR(60),
    SEG2_ID VARCHAR(60),
    SEG3_ID VARCHAR(60),
    SEG4_ID VARCHAR(60),
    SEG5_ID VARCHAR(60),
    SEG6_ID VARCHAR(60),
    SEG7_ID VARCHAR(60),
    SEG8_ID VARCHAR(60),
    SEG9_ID VARCHAR(60),
    SEG10_ID VARCHAR(60),
    LOAD_DATE TIMESTAMP NOT NULL,
    SOURCE_LOAD_MONTH VARCHAR(7) NOT NULL,
    CREATED_DATE TIMESTAMP,
    CREATED_BY VARCHAR(255),
    UPDATED_DATE TIMESTAMP,
    UPDATED_BY VARCHAR(255),
    CONSTRAINT pk_member PRIMARY KEY (HOME_PLAN_ID_CD, MEMB_ID_CD, ACCT_CD, ALT_MEM_ID)
)
USING DELTA;

CREATE TABLE IF NOT EXISTS ${catalog}.${schema_transformation}.member_enrollment_history (
    MEMB_ENROLLEE_HISTORY_BID BIGINT GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1) NOT NULL,
    HOME_PLAN_ID_CD VARCHAR(3) NOT NULL,
    MEMBER_BID BIGINT NOT NULL,
    MEMB_ID_CD VARCHAR(22) NOT NULL,
    ENR_MEMB_ID_CD VARCHAR() NOT NULL,
    CONTRACT_BEGIN_DT DATE NOT NULL,
    CONTRACT_END_DATE DATE NOT NULL,
    CONTRACT_END_REASON VARCHAR(),
    POP_ID VARCHAR(),
    ACCT_CD VARCHAR(::) NOT NULL,
    PROD_CD VARCHAR(),
    SES1_ID VARCHAR(),
    SES2_ID VARCHAR(),
    LOAD_DATE TIMESTAMP NOT NULL,
    SOURCE_LOAD_MONTH VARCHAR() NOT NULL,
    CREATED_DATE TIMESTAMP,
    CREATED_BY VARCHAR(::),
    UPDATED_DATE TIMESTAMP,
    UPDATED_BY VARCHAR(::),
    CONSTRAINT PK_MEMBER_ENROLLMENT PRIMARY KEY (HMEMB_ID, HOME_PLAN_ID_CD)
)
USING DELTA
WITH SERDEPROPERTIES(
    'delta.columnMapping.mode' = 'name',
    'delta.enableIcebergCompat2' = 'true',
    'delta.universalFormat.enabledFormat' = 'iceberg')
PARTITIONED BY (SOURCE_LOAD_MONTH, HOME_PLAN_ID_CD);

CREATE TABLE IF NOT EXISTS ${catalog}.${schema_transformation}.pharmacy (
    PRESCRIBD_DT DATE,
    PRDICARE_CVRD_CD VARCHAR(2),
    GENERIC_IND VARCHAR(1),
    SPCLTY_DRUG_IND VARCHAR(1),
    MAIL_ORDER_IND VARCHAR(1),
    LOAD_DATE TIMESTAMP NOT NULL,
    CREATED_DATE TIMESTAMP,
    CREATED_BY VARCHAR(255),
    UPDATED_DATE TIMESTAMP,
    UPDATED_BY VARCHAR(255),
    VALIDATED_TIMESTAMP TIMESTAMP
)
USING DELTA
TBLPROPERTIES(
    'delta.columnMapping.mode' = 'name',
    'delta.enableIcebergCompatV2' = 'true',
    'delta.universalFormat.enableFormats' = 'iceberg')
PARTITIONED BY (SOURCE_LOAD_MONTH, HOME_PLAN_ID_CD);

CREATE TABLE IF NOT EXISTS ${catalog}.${schema_transformation}.provider (
    PROVIDER_ID BIGINT,
    HOME_PLAN_ID_CD VARCHAR(3) NOT NULL,
    PROVIDER_ID_CD VARCHAR(9),
    SHI_PROV_ID VARCHAR(),
    CON_PROV_ID VARCHAR(),
    PROV_TAX_ID VARCHAR(),
    MEDICARE_PROV_ID VARCHAR(),
    PROV_TAXONOMY_CD VARCHAR() NOT NULL,
    PROV_NAME VARCHAR() NOT NULL,
    PLAN_PROV_ID INT,
    OOA_IND_GRP VARCHAR() NOT NULL,
    PROV_ORG_NM VARCHAR(),
    PROV_NM_LAST VARCHAR(),
    PROV_NM_FIRST VARCHAR(),
    PROV_STREET2 VARCHAR(),
    PROV_CITY VARCHAR(),
    PROV_COUNTY_CD VARCHAR(),
    PROV_STATE VARCHAR(),
    PROV_ZIP VARCHAR(),
    PROV_PHONE VARCHAR(),
    PROV_EMAIL VARCHAR(),
    PROV_NPI VARCHAR(),
    PROV_DEA VARCHAR(),
    SES1_ID VARCHAR(),
    SES2_ID VARCHAR(),
    SES3_ID VARCHAR(),
    SES4_ID VARCHAR(),
    SES5_ID VARCHAR(),
    SES6_ID VARCHAR(),
    SES7_ID VARCHAR(),
    SES8_ID VARCHAR(),
    SES9_ID VARCHAR(),
    SES10_ID VARCHAR(),
    PROV_ARRANGEMENT_ID_1 VARCHAR(),
    PROV_ARRANGEMENT_NM_1 VARCHAR(),
    PROV_ARRANGEMENT_START_DT_1 DATE,
    PROV_ARRANGEMENT_ENC_DT_1 DATE,
    PROV_ARRANGEMENT_ID_2 VARCHAR(),
    PROV_ARRANGEMENT_NM_2 VARCHAR(),
    PROV_ARRANGEMENT_TYPE_CD_2 VARCHAR(),
    PROV_ARRANGEMENT_START_DT_2 DATE,
    LOAD_DATE TIMESTAMP NOT NULL,
    SOURCE_LOAD_MONTH VARCHAR() NOT NULL,
    CREATED_DATE TIMESTAMP,
    CREATED_BY VARCHAR(::),
    UPDATED_DATE TIMESTAMP,
    UPDATED_BY VARCHAR(::),
    CONSTRAINT PK_PROVIDER PRIMARY KEY (PROVIDER_ID, HOME_PLAN_ID_CD)
)
USING DELTA
WITH SERDEPROPERTIES(
    'delta.columnMapping.mode' = 'name',
    'delta.enableIcebergCompat2' = 'true',
    'delta.universalFormat.enabledFormat' = 'iceberg')
PARTITIONED BY (SOURCE_LOAD_MONTH, HOME_PLAN_ID_CD);

CREATE TABLE IF NOT EXISTS ${catalog}.${schema_transformation}.quality_events (
    QUALITY_EVENT_BID BIGINT GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1) NOT NULL,
    HOME_PLAN_ID_CD VARCHAR(3) NOT NULL,
    MEMB_ID_CD VARCHAR(22) NOT NULL,
    EVENT_CD VARCHAR() NOT NULL,
    EVENT_DT DATE NOT NULL,
    EVENT_PROVIDER_BID BIGINT,
    CLM_LN_NUM SMALLINT,
    TRBNLE_FIELD_CD VARCHAR() NOT NULL,
    LOAD_DATE TIMESTAMP NOT NULL,
    SOURCE_LOAD_MONTH VARCHAR() NOT NULL,
    CREATED_DATE TIMESTAMP,
    CREATED_BY VARCHAR(::),
    UPDATED_DATE TIMESTAMP,
    UPDATED_BY VARCHAR(::)
)
USING DELTA
WITH SERDEPROPERTIES(
    'delta.columnMapping.mode' = 'name',
    'delta.enableIcebergCompat2' = 'true',
    'delta.universalFormat.enabledFormat' = 'iceberg')
PARTITIONED BY (SOURCE_LOAD_MONTH, HOME_PLAN_ID_CD);

CREATE TABLE IF NOT EXISTS ${catalog}.${schema_curation}.risk_member (
    RISK_MEMBER_ID BIGINT,
    HOME_PLAN_ID_CD VARCHAR(3) NOT NULL,
    MEMB_ID_CD VARCHAR(22) NOT NULL,
    MEM_ID_CD VARCHAR(22) NOT NULL,
    DEID_MEM_ID VARCHAR(80),
    ISSUER_CONTRACT_ID VARCHAR(5),
    MMBRS_STATE VARCHAR(2),
    MEMB_SRCH_DT DATE,
    MEMB_GENDER_CD VARCHAR(),
    PLAN_ID VARCHAR(5),
    POP_ID VARCHAR(),
    COVPRG_BEGIN_DT DATE,
    COVPRG_END_DT DATE,
    ACTIVE_IND VARCHAR(),
    GRP_CD VARCHAR(),
    SUBGRP_CD VARCHAR(),
    PROD_ID_CD VARCHAR(15),
    PROD_TYPE_CD VARCHAR(3),
    PROD_SIZE_CD VARCHAR(2),
    PROD_LINE_CD VARCHAR(),
    PROD_CD_VER VARCHAR(),
    PRODCD_VER VARCHAR(),
    PROC_ID_CD VARCHAR(15),
    PROC_TYPE_CD VARCHAR(),
    PROD_EMFG_IND VARCHAR(1),
    MED_EMFG_IND VARCHAR(),
    MMBRS_CITY VARCHAR(),
    SOURCE_LOAD_MONTH VARCHAR() NOT NULL,
    RISK_MODEL VARCHAR(),
    OBECT VARCHAR(),
    ERRD_STATUS VARCHAR(),
    ERRD_DESC VARCHAR(),
    INSTITUTIONAL_STATUS_PART_0 VARCHAR(),
    INSTITUTIONAL_STATUS_PART_D VARCHAR(),
    MEDICAID_STATUS VARCHAR(),
    CHMP_STATUS VARCHAR(),
    MEDICAID_CARE_STATUS VARCHAR(),
    AGE_GROUP VARCHAR(),
    MODEL_SEGMENT_PART_D VARCHAR(),
    PLAN_ENAME VARCHAR(::),
    TIME_PERIOD INT,
    CREATED_DATE TIMESTAMP,
    CREATED_BY VARCHAR(::),
    UPDATED_DATE TIMESTAMP,
    UPDATED_BY VARCHAR(::)
)
USING DELTA
WITH SERDEPROPERTIES(
    'delta.columnMapping.mode' = 'name',
    'delta.enableIcebergCompat2' = 'true',
    'delta.universalFormat.enabledFormat' = 'iceberg')
PARTITIONED BY (SOURCE_LOAD_MONTH, HOME_PLAN_ID_CD);

CREATE TABLE IF NOT EXISTS ${catalog}.${schema_curation}.risk_member_diag (
    RISK_MEMBER_ID BIGINT,
    HOME_PLAN_ID_CD VARCHAR(3) NOT NULL,
    MEMB_ID_CD VARCHAR(22) NOT NULL,
    CLAIM_BID BIGINT,
    CLM_TP_CD VARCHAR(2) NOT NULL,
    CLAIM_DT DATE,
    ICD_VER VARCHAR(),
    DX_SOURCE VARCHAR(),
    DIAG_MMBM VARCHAR(),
    DIAG_CD VARCHAR(),
    IOD_VER VARCHAR(),
    SOURCE_LOAD_MONTH VARCHAR() NOT NULL,
    TIME_PERIOD INT,
    CREATED_DATE TIMESTAMP,
    CREATED_BY VARCHAR(::),
    UPDATED_DATE TIMESTAMP,
    UPDATED_BY VARCHAR(::)
)
USING DELTA
WITH SERDEPROPERTIES(
    'delta.columnMapping.mode' = 'name',
    'delta.enableIcebergCompat2' = 'true',
    'delta.universalFormat.enabledFormat' = 'iceberg')
PARTITIONED BY (SOURCE_LOAD_MONTH, HOME_PLAN_ID_CD);

CREATE TABLE IF NOT EXISTS ${catalog}.${schema_curation}.risk_member_hcc (
    MEMBER_BID BIGINT NOT NULL,
    HOME_PLAN_ID_CD VARCHAR(3) NOT NULL,
    RISK_MODEL_YEAR INT,
    RISK_MODEL_TYPE VARCHAR(20),
    RISK_MODEL_VERSION VARCHAR(10),
    RISK_MODEL_SEGMENT VARCHAR(25),
    SAS_MODEL_VERSION VARCHAR(50),
    METHOD_ID SMALLINT,
    CC_CODE VARCHAR(50),
    CC_DESCRIPTION VARCHAR(200),
    CLAIM_BID BIGINT,
    CLAIM_DT DATE,
    DIAG_CD VARCHAR(8),
    GAP_STATUS VARCHAR(50),
    CLAIM_TYPE CHAR(30),
    SUPPRESSION_IND VARCHAR(1),
    ADJ_COEFF_SCORE DOUBLE,
    COEFF_SCORE DOUBLE,
    METHOD_CONFIDENCE_FACTOR DOUBLE,
    COMBINED_CONFIDENCE_FACTOR DOUBLE,
    CHRONIC_HCC CHAR(1),
    DX_SOURCE VARCHAR(20),
    RISK_YEAR INT,
    HRA CHAR(1),
    HRME_HRA CHAR(1),
    CYCLE_RUN VARCHAR(7),
    CREATED_DATE TIMESTAMP,
    CREATED_BY VARCHAR(100),
    UPDATED_DATE TIMESTAMP,
    UPDATED_BY VARCHAR(100)
)
USING DELTA
TBLPROPERTIES(
    'delta.columnMapping.mode' = 'name',
    'delta.enableIcebergCompatV2' = 'true',
    'delta.universalFormat.enableFormats' = 'iceberg',
    'delta.autoOptimize.optimizeWrite' = 'true',
    'delta.autoOptimize.autoCompact' = 'true'
)
PARTITIONED BY (HOME_PLAN_ID_CD,RISK_MODEL_VERSION, CYCLE_RUN);

CREATE TABLE IF NOT EXISTS ${catalog}.${schema_curation}.risk_member_hcc_summary (
    MEMBER_BID BIGINT NOT NULL,
    HOME_PLAN_ID_CD VARCHAR(3) NOT NULL,
    RISK_MODEL_YEAR INT,
    RISK_MODEL_TYPE VARCHAR(20),
    RISK_MODEL_VERSION VARCHAR(10),
    RISK_MODEL_SEGMENT VARCHAR(25),
    SAS_MODEL_VERSION VARCHAR(50),
    METHOD_ID SMALLINT,
    ADJ_COEFF_SCORE DOUBLE,
    COEFF_SCORE DOUBLE,
    METHOD_CONFIDENCE_FACTOR DOUBLE,
    COMBINED_CONFIDENCE_FACTOR DOUBLE,
    CHRONIC_HCC CHAR(1),
    DX_SOURCE VARCHAR(20),
    GAP_STATUS VARCHAR(50),
    RISK_YEAR INT,
    HRA CHAR(1),
    HRME_HRA CHAR(1),
    CYCLE_RUN VARCHAR(7),
    CREATED_DATE TIMESTAMP,
    CREATED_BY VARCHAR(100),
    UPDATED_DATE TIMESTAMP,
    UPDATED_BY VARCHAR(100)
)
USING DELTA
TBLPROPERTIES(
    'delta.columnMapping.mode' = 'name',
    'delta.enableIcebergCompatV2' = 'true',
    'delta.universalFormat.enableFormats' = 'iceberg')
PARTITIONED BY (HOME_PLAN_ID_CD,RISK_MODEL_VERSION, CYCLE_RUN);

CREATE TABLE IF NOT EXISTS ${catalog}.${gap_schema_curation}.risk_member_hcc_suppressed (
    MEMBER_BID BIGINT NOT NULL,
    HOME_PLAN_ID_CD VARCHAR(3) NOT NULL,
    RISK_MODEL_YEAR INT,
    RISK_MODEL_TYPE VARCHAR(20),
    RISK_MODEL_VERSION VARCHAR(10),
    RISK_MODEL_SEGMENT VARCHAR(25),
    SAS_MODEL_VERSION VARCHAR(50),
    METHOD_ID SMALLINT,
    CC_CODE VARCHAR(50),
    CC_DESCRIPTION VARCHAR(200),
    CLAIM_BID BIGINT,
    CLAIM_DT DATE,
    DIAG_CD VARCHAR(8),
    GAP_STATUS VARCHAR(50),
    GAP_REASON VARCHAR(50),
    CONFIDENCE_FACTOR DECIMAL(7,6),
    FREQUENCY INT,
    CHRONIC_HCC CHAR(1),
    DX_SOURCE VARCHAR(20),
    METHOD_CONFIDENCE_FACTOR DOUBLE,
    COMBINED_CONFIDENCE_FACTOR DOUBLE,
    CLAIM_TYPE CHAR(30),
    RISK_YEAR INT,
    HRA CHAR(1),
    HRME_HRA CHAR(1),
    CYCLE_RUN VARCHAR(7),
    ACTIVE_IND CHAR(1),
    CREATED_DATE TIMESTAMP,
    CREATED_BY VARCHAR(255),
    UPDATED_DATE TIMESTAMP,
    UPDATED_BY VARCHAR(255)
)
USING DELTA
TBLPROPERTIES(
    'delta.columnMapping.mode' = 'name',
    'delta.enableIcebergCompatV2' = 'true',
    'delta.universalFormat.enableFormats' = 'iceberg',
    'delta.autoOptimize.optimizeWrite' = 'true',
    'delta.autoOptimize.autoCompact' = 'true'
)
PARTITIONED BY (HOME_PLAN_ID_CD,RISK_MODEL_VERSION, CYCLE_RUN);

CREATE TABLE IF NOT EXISTS ${catalog}.${schema_curation}.risk_member_output (
    RISC_MEMBER_ID BIGINT,
    HOME_PLAN_ID_CD VARCHAR(3) NOT NULL,
    MEMB_ID_CD VARCHAR(22) NOT NULL,
    MEMBER_AGE INT,
    MEMBER_GENDER VARCHAR(1),
    MEMBERASURE_CONTRACT_ID VARCHAR(5),
    INCL_SUPP_HMM VARCHAR(1),
    INCL_PSUEDO_CLAIM VARCHAR(1),
    RISK_MODEL_TYPE VARCHAR(20),
    RISK_MODEL_VERSION VARCHAR(4),
    RISK_MODEL_YEAR INT,
    RISK_MODEL_SEGMENT VARCHAR(25),
    YEAR_MONTH VARCHAR(7),
    DEMOG_SCORE DOUBLE,
    DIAG_CD_TO_HCC_JSON_LIST ARRAY<STRING>,
    HCC_TO_SCORE_JSON_LIST ARRAY<STRING>,
    HCC_SCORE DOUBLE,
    HCC_COUNT_PAYMENT_SCORE DOUBLE,
    INTERACTION_SCORE DOUBLE,
    ORIGDS_SCORE DOUBLE,
    RISK_SCORE_RAW DOUBLE,
    RISK_SCORE_NORMALIZED DOUBLE,
    RISK_SCORE_PAYMENT_HCC DOUBLE,
    WEIGHTED_RISK_SCORE DOUBLE,
    TIME_PERIOD INT,
    SAS_MODEL_VERSION VARCHAR(50),
    CYCLE_RUN_DATE TIMESTAMP,
    CREATED_BY VARCHAR(255),
    CREATED_DATE TIMESTAMP
)
USING DELTA
CLUSTERED BY (HOME_PLAN_ID_CD,RISK_MODEL_VERSION, CYCLE_RUN)
PARTITIONED BY (YEAR_MONTH, TIME_PERIOD);

CREATE TABLE IF NOT EXISTS ${catalog}.${gap_schema_curation}.suspected_gaps (
    CLAIM_BID BIGINT,
    MEMBER_BID BIGINT,
    CLM_PMT_STS_CD VARCHAR(1),
    CLM_TP_CD VARCHAR(2),
    TP_OF_BILL_CD VARCHAR(3),
    CLAIM_DT DATE,
    DIAG_CD VARCHAR(8),
    SOURCE_LOAD_MONTH VARCHAR(7),
    CLM_LN_NUM DECIMAL(3,0),
    CPPT_AND_HCPCS_CD VARCHAR(6),
    DIAG_TYPE_CD VARCHAR(1),
    DIAG_NUM VARCHAR(2),
    PDIMC_PROC_CD VARCHAR(8),
    QUALIFY_CLAIMS VARCHAR(1),
    FREQUENCY_IND VARCHAR(2),
    GAP_ID VARCHAR(10),
    GAP_REASON VARCHAR(50),
    GAP_STATUS VARCHAR(50),
    MATCHED_CODE VARCHAR(10),
    MATCHED_DATE VARCHAR(10),
    SCENARIO_TYPE VARCHAR(50),
    MODEL_VERSION VARCHAR(20),
    MATCHING_YN VARCHAR(1),
    CE_CODE VARCHAR(50),
    SUPPRESSION_YN VARCHAR(1),
    SUPP_SUPP_BY_PARENT VARCHAR(1),
    SUPPRESSION2_YN VARCHAR(1),
    CREATE_GAP VARCHAR(1),
    HOME_PLAN_ID_CD VARCHAR(3),
    FREQUENCY INT,
    CHRONIC_HCC VARCHAR(1),
    CONFIDENCE_FACTOR DECIMAL(7,6),
    CREATED_DATE TIMESTAMP,
    CREATED_BY VARCHAR(255),
    UPDATED_DATE TIMESTAMP,
    UPDATED_BY VARCHAR(255)
)
USING DELTA;

-- Additional tables from images 10, 11, 12

CREATE TABLE IF NOT EXISTS ${catalog}.${schema_transformation}.facility_id (
    FACILITY_BID BIGINT GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1),
    HOME_PLAN_ID_CD VARCHAR(3) NOT NULL,
    CLM_ID_CD VARCHAR() NOT NULL,
    CREATED_DATE TIMESTAMP,
    CREATED_BY VARCHAR(::),
    UPDATED_DATE TIMESTAMP,
    UPDATED_BY VARCHAR(::)
)
USING DELTA
WITH SERDEPROPERTIES(
    'delta.columnMapping.mode' = 'name',
    'delta.enableIcebergCompat2' = 'true',
    'delta.universalFormat.enabledFormat' = 'iceberg');

CREATE TABLE IF NOT EXISTS ${catalog}.${schema_transformation}.mao_claim_diag (
    SUPPLEMENTAL_BID BIGINT NOT NULL,
    ICD_VERSION INT,
    DIAG_CODE VARCHAR(),
    DIAG_FLAG VARCHAR(),
    SOURCE_LOAD_MONTH VARCHAR(),
    LOAD_DATE TIMESTAMP,
    DATA_CYCLE_ID VARCHAR() NOT NULL,
    HOME_PLAN_ID_CD VARCHAR() NOT NULL,
    DTRN_BID BIGINT NOT NULL,
    PROCESS_IND_VM VARCHAR(),
    CREATED_BY VARCHAR(::),
    UPDATED_DATE TIMESTAMP,
    UPDATED_BY VARCHAR(::)
)
USING DELTA
WITH SERDEPROPERTIES(
    'delta.columnMapping.mode' = 'name',
    'delta.enableIcebergCompat2' = 'true',
    'delta.universalFormat.enabledFormat' = 'iceberg')
PARTITIONED BY (SOURCE_LOAD_MONTH, HOME_PLAN_ID_CD);

CREATE TABLE IF NOT EXISTS ${catalog}.${schema_transformation}.mao_claims (
    SUPPLEMENTAL_BID BIGINT NOT NULL,
    MEMBER_BID BIGINT,
    REPORT_ID VARCHAR(),
    CONTRACT_ID VARCHAR() NOT NULL,
    BID_CD VARCHAR(),
    POP_ID VARCHAR(),
    HOME_PLAN_ID_CD VARCHAR(),
    ENCOUNTER_TYPE VARCHAR() NOT NULL,
    ENCOUNTER_ICN VARCHAR(),
    ALLOWED_STATUS VARCHAR(),
    SUBMIT_DATE DATE,
    DOS_SBMT DATE,
    SERVICE_TYPE VARCHAR(),
    ALLOWED_FLAG VARCHAR(),
    REASON_CODE VARCHAR(),
    DIAGNOSIS_CD VARCHAR(),
    SOURCE_LOAD_MONTH VARCHAR(),
    DATA_CYCLE_ID VARCHAR() NOT NULL,
    HOME_PLAN_ID_CD VARCHAR() NOT NULL,
    DTRN_BID BIGINT NOT NULL,
    GEN_CD VARCHAR(),
    PROC_ID_CD VARCHAR(),
    PLAN_NAME VARCHAR() NOT NULL,
    DRG_CD VARCHAR(),
    PLACE_OF_SERV_CD VARCHAR(),
    FIRST_SERV_DT DATE,
    LAST_SERV_DT DATE,
    STMF_THRU_DT DATE,
    COTN_AMT DECIMAL(::,::),
    COPAY_AMT DECIMAL(::,::),
    DED_AMT DECIMAL(::,::),
    ICTRA_AMT DECIMAL(::,::),
    QUALITY_CLAIMS VARCHAR() NOT NULL,
    INVALID_CPT_HCPCS VARCHAR() NOT NULL,
    BUNDLED_VARCHAR() NOT NULL,
    PROGRAM VARCHAR() NOT NULL,
    LOAD_DATE TIMESTAMP NOT NULL,
    SOURCE_LOAD_MONTH VARCHAR() NOT NULL,
    CREATED_DATE TIMESTAMP NOT NULL,
    CREATED_BY VARCHAR(::) NOT NULL,
    UPDATED_DATE TIMESTAMP NOT NULL,
    UPDATED_BY VARCHAR(::) NOT NULL
)
USING DELTA
WITH SERDEPROPERTIES(
    'delta.columnMapping.mode' = 'name',
    'delta.enableIcebergCompat2' = 'true',
    'delta.universalFormat.enabledFormat' = 'iceberg')
PARTITIONED BY (SOURCE_LOAD_MONTH, HOME_PLAN_ID_CD);

CREATE TABLE IF NOT EXISTS ${catalog}.${schema_transformation}.medical_claims (
    CLAIM_BID BIGINT,
    CLM_LN_NUMB DECIMAL(::,) NOT NULL,
    VISIO_TYPE_ID SMALLINT,
    CPT_AND_HCPCS_CD VARCHAR(),
    PROC_MOD_CD1 VARCHAR(),
    PROC_MOD_CD2 VARCHAR(),
    PROC_MOD_CD3 VARCHAR(),
    PROC_MOD_CD4 VARCHAR(),
    REIMG_TP_CD VARCHAR(),
    TOD_UNITS_CNT DECIMAL(::,),
    TOD_UNITS_VAL DECIMAL(::,),
    ALSMD_AMT DECIMAL(::,::),
    PMT_AMT DECIMAL(::,::),
    MEMBER_BID BIGINT,
    POP_ID VARCHAR(),
    PSEUDO_CLAIM_TYPE VARCHAR(),
    QUALITY_CD VARCHAR(),
    RATERNG_CD VARCHAR(),
    CLM_PMT_STS_CD VARCHAR(),
    CLM_TP_CD VARCHAR(),
    DISDB_STUS_CD VARCHAR(),
    TP_OF_BILL_CD VARCHAR(),
    HOME_PLAN_ID_CD VARCHAR() NOT NULL,
    MEMB_ID_CD VARCHAR(::),
    CLM_ID_CD VARCHAR(::) NOT NULL,
    RLS_ID_CB VARCHAR(),
    PROC_ID_CD VARCHAR(),
    PLAN_NAME VARCHAR(::) NOT NULL,
    DRG_CD VARCHAR(),
    PLACE_OF_SERV_CD VARCHAR(),
    FIRST_SERV_DT DATE,
    LAST_SERV_DT DATE,
    STMF_THRU_DT DATE,
    COTN_AMT DECIMAL(::,::),
    COPAY_AMT DECIMAL(::,::),
    DED_AMT DECIMAL(::,::),
    ICTRA_AMT DECIMAL(::,::),
    SOURCE_LOAD_MONTH VARCHAR(),
    DATA_CYCLE_ID VARCHAR() NOT NULL,
    HOME_PLAN_ID_CD VARCHAR() NOT NULL,
    DTRN_BID BIGINT NOT NULL,
    CREATED_DATE TIMESTAMP NOT NULL,
    CREATED_BY VARCHAR(::),
    UPDATED_DATE TIMESTAMP NOT NULL,
    UPDATED_BY VARCHAR(::)
)
USING DELTA
WITH SERDEPROPERTIES(
    'delta.columnMapping.mode' = 'name',
    'delta.enableIcebergCompat2' = 'true',
    'delta.universalFormat.enabledFormat' = 'iceberg')
PARTITIONED BY (SOURCE_LOAD_MONTH, HOME_PLAN_ID_CD);

CREATE TABLE IF NOT EXISTS ${catalog}.${schema_transformation}.member_id (
    BID BIGINT, HOME_PLAN_ID_CD VARCHAR(3) NOT NULL,
    MEMBER_ID_CD VARCHAR(::), PERSON_ID VARCHAR(::) NOT NULL,
    CREATED_DATE TIMESTAMP, CREATED_BY VARCHAR(::), UPDATED_DATE TIMESTAMP,
    UPDATED_BY VARCHAR(::), CONSTRAINT member_id_pk PRIMARY KEY (BID, HOME_PLAN_ID_CD, MEMBER_ID_CD, PERSON_ID)
)
USING DELTA TBLPROPERTIES(
    'delta.columnMapping.mode' = 'name',
    'delta.enableIcebergCompat2' = 'true',
    'delta.universalFormat.enabledFormat' = 'iceberg');

INSERT INTO ${catalog}.${schema_transformation}.member_id
(BID, HOME_PLAN_ID_CD, MEMBER_ID_CD, PERSON_ID, CREATED_DATE, CREATED_BY, UPDATED_DATE, UPDATED_BY)
SELECT * FROM ${catalog}.${schema_transformation}.member_id ;

CREATE TABLE IF NOT EXISTS ${catalog}.${schema_transformation}.unn (
    BID BIGINT, HOME_PLAN_ID_CD VARCHAR(3) NOT NULL,
    MEMBER_ID_CD VARCHAR(::), PERSON_ID VARCHAR(::) NOT NULL,
    CREATED_DATE TIMESTAMP, CREATED_BY VARCHAR(::), UPDATED_DATE TIMESTAMP,
    UPDATED_BY VARCHAR(::), CONSTRAINT unn_id_pk PRIMARY KEY (BID, HOME_PLAN_ID_CD, MEMBER_ID_CD, PERSON_ID)
)
USING delta TBLPROPERTIES(
    'delta.columnMapping.mode' = 'name',
    'delta.enableIcebergCompat2' = 'true',
    'delta.universalFormat.enabledFormat' = 'iceberg')
PARTITIONED BY (SOURCE_LOAD_MONTH, HOME_PLAN_ID_CD);
