-- Transformation and Curation Layer Tables
-- These tables contain transformed and curated business data

CREATE TABLE IF NOT EXISTS $[catalog].$[schema_curation].risk_member_hcc_suppressed (
    MEMBER_BID BIGINT NOT NULL,
    HOME_PLAN_ID_CD VARCHAR(3) NOT NULL,
    RISK_MODEL_YEAR INT,
    RISK_MODEL_TYPE VARCHAR(20),
    RISK_MODEL_VERSION VARCHAR(10),
    RISK_MODEL_SEGMENT VARCHAR(25),
    SAS_MODEL_VERSION VARCHAR(50),
    METHOD_ID SMALLINT,
    CC_CODE VARCHAR(50),
    CC_DESCRIPTION VARCHAR(200),
    CLAIM_BID BIGINT,
    CLAIM_DT DATE,
    DIAG_CD VARCHAR(8),
    GAP_STATUS VARCHAR(50),
    GAP_REASON VARCHAR(50),
    CONFIDENCE_FACTOR DECIMAL(7,6),
    FREQUENCY INT,
    CHRONIC_HCC CHAR(1),
    DX_SOURCE VARCHAR(20),
    METHOD_CONFIDENCE_FACTOR DOUBLE,
    COMBINED_CONFIDENCE_FACTOR DOUBLE,
    CHRONIC_HCC CHAR(1),
    DX_SOURCE VARCHAR(20),
    GAP_STATUS VARCHAR(50),
    CLAIM_TYPE CHAR(30),
    CLAIM_BID BIGINT,
    CLAIM_DT DATE,
    DIAG_CD VARCHAR(10),
    RISK_YEAR INT,
    HRA CHAR(1),
    HRME_HRA CHAR(1),
    CYCLE_RUN VARCHAR(7),
    ACTIVE_IND CHAR(1),
    CREATED_DATE TIMESTAMP,
    CREATED_BY VARCHAR(255),
    UPDATED_DATE TIMESTAMP,
    UPDATED_BY VARCHAR(255)
)
USING DELTA
TBLPROPERTIES(
    'delta.columnMapping.mode' = 'name',
    'delta.enableIcebergCompatV2' = 'true',
    'delta.universalFormat.enableFormats' = 'iceberg',
    'delta.autoOptimize.optimizeWrite' = 'true',
    'delta.autoOptimize.autoCompact' = 'true'
)
PARTITIONED BY (HOME_PLAN_ID_CD,RISK_MODEL_VERSION, CYCLE_RUN);

CREATE TABLE IF NOT EXISTS $[catalog].$[schema_curation].risk_member_hcc_summary (
    MEMBER_BID BIGINT NOT NULL,
    HOME_PLAN_ID_CD VARCHAR(3) NOT NULL,
    RISK_MODEL_YEAR INT,
    RISK_MODEL_TYPE VARCHAR(20),
    RISK_MODEL_VERSION VARCHAR(10),
    RISK_MODEL_SEGMENT VARCHAR(25),
    SAS_MODEL_VERSION VARCHAR(50),
    METHOD_ID SMALLINT,
    ADJ_COEFF_SCORE DOUBLE,
    COEFF_SCORE DOUBLE,
    METHOD_CONFIDENCE_FACTOR DOUBLE,
    COMBINED_CONFIDENCE_FACTOR DOUBLE,
    CHRONIC_HCC CHAR(1),
    DX_SOURCE VARCHAR(20),
    GAP_STATUS VARCHAR(50),
    RISK_YEAR INT,
    HRA CHAR(1),
    HRME_HRA CHAR(1),
    CYCLE_RUN VARCHAR(7),
    CREATED_DATE TIMESTAMP,
    CREATED_BY VARCHAR(100),
    UPDATED_DATE TIMESTAMP,
    UPDATED_BY VARCHAR(100)
)
USING DELTA
TBLPROPERTIES(
    'delta.columnMapping.mode' = 'name',
    'delta.enableIcebergCompatV2' = 'true',
    'delta.universalFormat.enableFormats' = 'iceberg')
PARTITIONED BY (HOME_PLAN_ID_CD,RISK_MODEL_VERSION, CYCLE_RUN);

CREATE TABLE IF NOT EXISTS $[catalog].$[schema_curation].risk_member_hcc (
    MEMBER_BID BIGINT NOT NULL,
    HOME_PLAN_ID_CD VARCHAR(3) NOT NULL,
    RISK_MODEL_YEAR INT,
    RISK_MODEL_TYPE VARCHAR(20),
    RISK_MODEL_VERSION VARCHAR(10),
    RISK_MODEL_SEGMENT VARCHAR(25),
    SAS_MODEL_VERSION VARCHAR(50),
    METHOD_ID SMALLINT,
    CC_CODE VARCHAR(50),
    CC_DESCRIPTION VARCHAR(200),
    CLAIM_BID BIGINT,
    CLAIM_DT DATE,
    DIAG_CD VARCHAR(8),
    GAP_STATUS VARCHAR(50),
    CLAIM_TYPE CHAR(30),
    SUPPRESSION_IND VARCHAR(1),
    METHOD_ID SMALLINT,
    ADJ_COEFF_SCORE DOUBLE,
    COEFF_SCORE DOUBLE,
    METHOD_CONFIDENCE_FACTOR DOUBLE,
    COMBINED_CONFIDENCE_FACTOR DOUBLE,
    CHRONIC_HCC CHAR(1),
    DX_SOURCE VARCHAR(20),
    GAP_STATUS VARCHAR(50),
    RISK_YEAR INT,
    HRA CHAR(1),
    HRME_HRA CHAR(1),
    CYCLE_RUN VARCHAR(7),
    CREATED_DATE TIMESTAMP,
    CREATED_BY VARCHAR(100),
    UPDATED_DATE TIMESTAMP,
    UPDATED_BY VARCHAR(100)
)
USING DELTA
TBLPROPERTIES(
    'delta.columnMapping.mode' = 'name',
    'delta.enableIcebergCompatV2' = 'true',
    'delta.universalFormat.enableFormats' = 'iceberg',
    'delta.autoOptimize.optimizeWrite' = 'true',
    'delta.autoOptimize.autoCompact' = 'true'
)
PARTITIONED BY (HOME_PLAN_ID_CD,RISK_MODEL_VERSION, CYCLE_RUN);

CREATE TABLE IF NOT EXISTS $[catalog].$[schema_curation].suspected_gaps (
    CLAIM_BID BIGINT,
    MEMBER_BID BIGINT,
    CLM_PMT_STS_CD VARCHAR(1),
    CLM_TP_CD VARCHAR(2),
    TP_OF_BILL_CD VARCHAR(3),
    CLAIM_DT DATE,
    DIAG_CD VARCHAR(8),
    SOURCE_LOAD_MONTH VARCHAR(7),
    CLM_LN_NUM DECIMAL(3,0),
    CPPT_AND_HCPCS_CD VARCHAR(6),
    DIAG_TYPE_CD VARCHAR(1),
    DIAG_NUM VARCHAR(2),
    DIAG_CD VARCHAR(8),
    PDIMC_PROC_CD VARCHAR(8),
    QUALIFY_CLAIMS VARCHAR(1),
    FREQUENCY_IND VARCHAR(2),
    GAP_ID VARCHAR(10),
    GAP_REASON VARCHAR(50),
    GAP_STATUS VARCHAR(50),
    MATCHED_CODE VARCHAR(10),
    MATCHED_DATE VARCHAR(10),
    SCENARIO_TYPE VARCHAR(50),
    MODEL_VERSION VARCHAR(20),
    MATCHING_YN VARCHAR(1),
    CE_CODE VARCHAR(50),
    SUPPRESSION_YN VARCHAR(1),
    SUPP_SUPP_BY_PARENT VARCHAR(1),
    SUPPRESSION2_YN VARCHAR(1),
    CREATE_GAP VARCHAR(1),
    HOME_PLAN_ID_CD VARCHAR(3),
    FREQUENCY INT,
    CHRONIC_HCC VARCHAR(1),
    CONFIDENCE_FACTOR DECIMAL(7,6),
    CREATED_DATE TIMESTAMP,
    CREATED_BY VARCHAR(255),
    UPDATED_DATE TIMESTAMP,
    UPDATED_BY VARCHAR(255)
)
USING DELTA;

CREATE TABLE IF NOT EXISTS $[catalog].$[schema_curation].medicare_mor_part1_type0 (
    MBI VARCHAR(11) NOT NULL,
    MEMBER_ID BIGINT NOT NULL,
    MEMB_ID_CD VARCHAR(22),
    HOME_PLAN_PRO_ID VARCHAR(14),
    HOME_PLAN_ID_CD VARCHAR(1),
    CREATED_DATE TIMESTAMP,
    CREATED_BY VARCHAR(255),
    UPDATED_DATE TIMESTAMP,
    UPDATED_BY VARCHAR(255)
)
USING DELTA
TBLPROPERTIES(
    'delta.columnMapping.mode' = 'name',
    'delta.enableIcebergCompatV2' = 'true',
    'delta.universalFormat.enableFormats' = 'iceberg');

CREATE TABLE IF NOT EXISTS $[catalog].$[schema_curation].medicare_mor_part1_type2 (
    MBI VARCHAR(11) NOT NULL,
    MEMBER_ID BIGINT NOT NULL,
    MEMB_ID_CD VARCHAR(22),
    HOME_PLAN_PRO_ID VARCHAR(14),
    HOME_PLAN_ID_CD VARCHAR(1),
    CREATED_DATE TIMESTAMP,
    CREATED_BY VARCHAR(255),
    UPDATED_DATE TIMESTAMP,
    UPDATED_BY VARCHAR(255)
)
USING DELTA;

CREATE TABLE IF NOT EXISTS $[catalog].$[schema_curation].medicare_mbi_xwalk (
    MBI VARCHAR(11) NOT NULL,
    MEMBER_ID BIGINT NOT NULL,
    MEMB_ID_CD VARCHAR(22),
    HOME_PLAN_PRO_ID VARCHAR(14),
    HOME_PLAN_ID_CD VARCHAR(1),
    CREATED_DATE TIMESTAMP,
    CREATED_BY VARCHAR(255),
    UPDATED_DATE TIMESTAMP,
    UPDATED_BY VARCHAR(255)
)
USING DELTA;

CREATE TABLE IF NOT EXISTS $[catalog].$[schema_curation].ma_id (
    SUPPLEMENTAL_BID BIGINT GENERATED ALWAYS AS IDENTITY (START WITH 9900000000000001 INCREMENT BY 1),
    MBT VARCHAR(11) NOT NULL,
    MEMBER_ID VARCHAR(2) NOT NULL,
    ICD_VER VARCHAR(1) NOT NULL
)
USING DELTA;

CREATE TABLE IF NOT EXISTS $[catalog].$[schema_curation].pharmacy (
    PRESCRIBD_DT DATE,
    PRDICARE_CVRD_CD VARCHAR(2),
    GENERIC_IND VARCHAR(1),
    SPCLTY_DRUG_IND VARCHAR(1),
    MAIL_ORDER_IND VARCHAR(1),
    LOAD_DATE TIMESTAMP NOT NULL -- e.g., '202507' for July 2025
    CREATED_DATE TIMESTAMP,
    CREATED_BY VARCHAR(255),
    UPDATED_DATE TIMESTAMP,
    UPDATED_BY VARCHAR(255),
    VALIDATED_TIMESTAMP TIMESTAMP
)
USING DELTA
TBLPROPERTIES(
    'delta.columnMapping.mode' = 'name',
    'delta.enableIcebergCompatV2' = 'true',
    'delta.universalFormat.enableFormats' = 'iceberg')
PARTITIONED BY (SOURCE_LOAD_MONTH, HOME_PLAN_ID_CD);

CREATE TABLE IF NOT EXISTS $[catalog].$[schema_curation].health_events (
    HEALTH_EVENT_BID BIGINT GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1) NOT NULL,
    HOME_PLAN_ID_CD VARCHAR(3) NOT NULL,
    MEMBER_BID BIGINT NOT NULL,
    MEMB_ID_CD VARCHAR(22) NOT NULL,
    PROGRAM_TYPE VARCHAR(3) NOT NULL,
    PROGRAM_NAME VARCHAR(50) NOT NULL,
    PROGRAM_DESC VARCHAR(150) NOT NULL,
    COND_CAT VARCHAR(50) NOT NULL,
    COND_VER VARCHAR(10) NOT NULL,
    PROCESS_DATE DATE NOT NULL,
    PROC_START_DT DATE,
    PROC_END_DT DATE,
    RECORD_ID VARCHAR(50) NOT NULL,
    RECORD_SUB_ID VARCHAR(50) NOT NULL,
    PERCENT_HEIGHT_DECIMAL(7,5) NOT NULL,
    LOAD_DATE TIMESTAMP NOT NULL,
    -- Additional columns
    SOURCE_LOAD_MONTH VARCHAR(7) NOT NULL,
    CREATED_DATE TIMESTAMP,
    CREATED_BY VARCHAR(255),
    UPDATED_DATE TIMESTAMP,
    UPDATED_BY VARCHAR(255)
)
USING DELTA;

CREATE TABLE IF NOT EXISTS $[catalog].$[schema_curation].member_enrollment (
    ACCT_CD VARCHAR(14) NOT NULL,
    GRP_CD VARCHAR(14),
    SUBGRP_CD VARCHAR(10),
    PROD_ID_CD VARCHAR(15),
    PROD_TYPE_CD VARCHAR(3) NOT NULL,
    GROUP_SIZE_CD VARCHAR(2) NOT NULL,
    NATIONAL_ACCOUNT_IND CHAR(1) NOT NULL,
    LINE_OF_BUSINESS_CD VARCHAR(2) NOT NULL,
    MEMBER_STATE_FIPS_CD VARCHAR(2) NOT NULL,
    PRODUCT_LINE_CD VARCHAR(2) NOT NULL,
    EMPLOYEE_STATUS_CD VARCHAR(2) NOT NULL,
    EMPLOYEE_TYPE_CD VARCHAR(2) NOT NULL,
    FUNDING_ARRANGEMENT_CD VARCHAR(2) NOT NULL,
    BARGAINING_STATUS_CD VARCHAR(2) NOT NULL,
    BARGAINING_STATUS_EFF_DT VARCHAR(2) NOT NULL,
    CONTRACT_ID VARCHAR(9),
    CONTRACT_EFFECTIVE_DT DATE NOT NULL,
    CONTRACT_END_DT DATE NOT NULL,
    NAICS_CD VARCHAR(6),
    INQBSTRY VARCHAR(4),
    SUB_ID VARCHAR(22) NOT NULL,
    MEMB_HIERARCHY_CD VARCHAR(2) NOT NULL,
    PRIMARY_BRFT_IND CHAR(1) NOT NULL,
    CDHF_BRFT_IND CHAR(1) NOT NULL,
    HSPLI_BRFT_IND CHAR(1) NOT NULL,
    MLI_BRFT_IND CHAR(1) NOT NULL,
    CD_BRFT_IND CHAR(1) NOT NULL,
    DENT_BRFT_IND CHAR(1) NOT NULL,
    POP_ID VARCHAR(2) NOT NULL,
    EXPCT_IND VARCHAR(3) NOT NULL,
    RATING_AREA VARCHAR(15),
    PMEM_AMT DECIMAL(8,2) NOT NULL,
    PMEM_AMT_OFFSET DECIMAL(8,2) NOT NULL,
    METAL VARCHAR(12) NOT NULL,
    EHROLL_PERIOD_ACT VARCHAR(6),
    MEMB_MED_CDR_CD CHAR(1) NOT NULL,
    MEMB_PHARMACY_CDR_CD CHAR(1) NOT NULL,
    SEG1_ID VARCHAR(60),
    SEG2_ID VARCHAR(60),
    SEG3_ID VARCHAR(60),
    SEG4_ID VARCHAR(60),
    SEG5_ID VARCHAR(60),
    SEG6_ID VARCHAR(60),
    SEG7_ID VARCHAR(60),
    SEG8_ID VARCHAR(60),
    SEG9_ID VARCHAR(60),
    SEG10_ID VARCHAR(60),
    LOAD_DATE TIMESTAMP NOT NULL,
    -- Additional columns
    SOURCE_LOAD_MONTH VARCHAR(7) NOT NULL,
    CREATED_DATE TIMESTAMP,
    CREATED_BY VARCHAR(255),
    UPDATED_DATE TIMESTAMP,
    UPDATED_BY VARCHAR(255),
    -- Primary key constraint (matches original clustered primary key)
    CONSTRAINT pk_member PRIMARY KEY (HOME_PLAN_ID_CD, MEMB_ID_CD, ACCT_CD, ALT_MEM_ID)
)
USING DELTA;

CREATE TABLE IF NOT EXISTS $[catalog].$[schema_curation].member (
    BHI_MEMB_ID VARCHAR(22) NOT NULL,
    DEID_MEM_ID VARCHAR(80),
    PERSON_ID_CD VARCHAR(22) NOT NULL,
    ALT_MEM_ID VARCHAR(22),
    MBRS_HC_LAST VARCHAR(25),
    MBRS_HM_INTIALE VARCHAR(25),
    MEMB_BIRTH_DT DATE NOT NULL,
    MEMB_DEATH_DT DATE,
    MEMB_GENDER_CD CHAR(1) NOT NULL,
    MEMB_CHFMFT_CD VARCHAR(3) NOT NULL,
    MBRS_STREET1 VARCHAR(70),
    MBRS_STREET2 VARCHAR(70),
    MBRS_CITY VARCHAR(35),
    MBRS_STATE VARCHAR(2),
    MBRS_ZIP VARCHAR(5),
    MBRS_CRMT_PRIM_ZIP_CD VARCHAR(5),
    MBRS_CRMT_PRIM_ZIP_PLUS4 VARCHAR(4),
    MBRS_PRIM_PHN VARCHAR(10),
    MBRS_PRIM_EMAIL VARCHAR(70),
    MBRS_PREF_CONTACT_CD VARCHAR(2),
    MEMB_SMOKNG_STS CHAR(1),
    SEG1_ID VARCHAR(60),
    SEG2_ID VARCHAR(60),
    SEG3_ID VARCHAR(60),
    SEG4_ID VARCHAR(60),
    SEG5_ID VARCHAR(60),
    SEG6_ID VARCHAR(60),
    SEG7_ID VARCHAR(60),
    SEG8_ID VARCHAR(60),
    SEG9_ID VARCHAR(60),
    SEG10_ID VARCHAR(60),
    LOAD_DATE TIMESTAMP NOT NULL,
    -- Additional columns
    SOURCE_LOAD_MONTH VARCHAR(7) NOT NULL,
    CREATED_DATE TIMESTAMP,
    CREATED_BY VARCHAR(255),
    UPDATED_DATE TIMESTAMP,
    UPDATED_BY VARCHAR(255),
    -- Primary key constraint (matches original clustered primary key)
    CONSTRAINT pk_member_primary KEY (HOME_PLAN_ID_CD, MEMB_ID_CD, DEID_MEM_ID)
)
USING DELTA;

CREATE TABLE IF NOT EXISTS $[catalog].$[schema_curation].risk_member_output (
    RISC_MEMBER_ID BIGINT,
    HOME_PLAN_ID_CD VARCHAR(3) NOT NULL,
    MEMB_ID_CD VARCHAR(22) NOT NULL,
    MEMBER_AGE INT,
    MEMBER_GENDER VARCHAR(1),
    MEMBERASURE_CONTRACT_ID VARCHAR(5),
    INCL_SUPP_HMM VARCHAR(1),
    INCL_PSUEDO_CLAIM VARCHAR(1),
    RISK_MODEL_TYPE VARCHAR(20),
    RISK_MODEL_VERSION VARCHAR(4),
    RISK_MODEL_YEAR INT,
    RISK_MODEL_SEGMENT VARCHAR(25),
    YEAR_MONTH VARCHAR(7),
    DEMOG_SCORE DOUBLE,
    DIAG_CD_TO_HCC_JSON_LIST ARRAY<STRING>,
    HCC_TO_SCORE_JSON_LIST ARRAY<STRING>,
    HCC_SCORE DOUBLE,
    HCC_COUNT_PAYMENT_SCORE DOUBLE,
    INTERACTION_SCORE DOUBLE,
    ORIGDS_SCORE DOUBLE,
    RISK_SCORE_RAW DOUBLE,
    RISK_SCORE_NORMALIZED DOUBLE,
    RISK_SCORE_PAYMENT_HCC DOUBLE,
    WEIGHTED_RISK_SCORE DOUBLE,
    TIME_PERIOD INT,
    SAS_MODEL_VERSION VARCHAR(50),
    CYCLE_RUN_DATE TIMESTAMP,
    CREATED_BY VARCHAR(255),
    CREATED_DATE TIMESTAMP
)
USING DELTA
-- Liquid clustering on the columns the read-back in
-- -- WHERE (YEAR_MONTH = X AND TIME_PERIOD = Z
-- -- this appended only table is (read via
-- -- schema_curation.risk_member_output filters on (YEAR_MONTH + TIME_PERIOD).
-- -- so clustering lets Delta skip files for other months/periods instead of
-- -- scanning the whole (ever-growing) table run.
CLUSTERED BY (HOME_PLAN_ID_CD,RISK_MODEL_VERSION, CYCLE_RUN)
PARTITIONED BY (YEAR_MONTH + TIME_PERIOD);
