CREATE OR REPLACE TABLE ${catalog}.${schema_ingestion}.stage_member (
    HOME_PLAN_ID_CD STRING, MEMB_ID_CD STRING, BHI_MEMB_ID STRING, DEID_MEM_ID STRING,
    PERSON_ID_CD STRING, ALT_MEM_ID STRING, MBRS_NM_LAST STRING, MBRS_NM_FIRST STRING,
    MBRS_STREET1 STRING, MBRS_STREET2 STRING, MBRS_CITY STRING, MBRS_STATE STRING,
    MBRS_CRNT_COUNTY_CD STRING, MBRS_CRNT_PRIM_ZIP_CD STRING, MBRS_PRIM_PHN STRING,
    MBRS_PRIM_EMAIL STRING, MBRS_PREF_CONTACT STRING, MEMB_BRTH_DT STRING, MEMB_GENDER_CD STRING, MEMB_CNFDT_CD STRING,
    MEMB_SMOKING_STS STRING, MEMB_DEATH_DT STRING,
    SEG1_ID STRING, SEG2_ID STRING, SEG3_ID STRING, SEG4_ID STRING, SEG5_ID STRING,
    SEG6_ID STRING, SEG7_ID STRING, SEG8_ID STRING, SEG9_ID STRING,
    MBRS_NM_MIDDLE STRING, MBRS_CRNT_PRIM_ZIP_PLUSFOUR STRING, SOURCE_LOAD_MONTH STRING, CREATED_DATE TIMESTAMP,
    CREATED_BY STRING, UPDATED_DATE TIMESTAMP, UPDATED_BY STRING, VALIDATED_TIMESTAMP TIMESTAMP)
USING DELTA TBLPROPERTIES( 'delta.columnMapping.mode' = 'name') PARTITIONED BY (SOURCE_LOAD_MONTH);

CREATE OR REPLACE TABLE ${catalog}.${schema_ingestion}.stage_member_enrollment_history (
    HOME_PLAN_ID_CD STRING, MEMB_ID_CD STRING, BHT_MEMB_ID STRING, CONTRACT_BEGIN_DT STRING,
    CONTRACT_END_DT STRING, POD_ID STRING, ACCT_CD STRING, GRP_CD STRING,
    SUBGRP_CD STRING, PROD_ID_CD STRING, SOURCE_LOAD_MONTH STRING, CREATED_DATE TIMESTAMP,
    CREATED_BY STRING, UPDATED_DATE TIMESTAMP, UPDATED_BY STRING, VALIDATED_TIMESTAMP TIMESTAMP)
USING DELTA
TBLPROPERTIES(
    'delta.columnMapping.mode' = 'name') PARTITIONED BY (SOURCE_LOAD_MONTH);

CREATE OR REPLACE TABLE ${catalog}.${schema_ingestion}.stage_member_enrollment (
    ISSUER_ID STRING,
    PLAN_ID STRING,
    MEMB_ID_CD STRING,
    HOME_PLAN_ID_CD STRING,
    TRCBLT_FIELD_CD STRING,
    COVRG_BEGIN_DT STRING,
    COVRG_END_DT STRING,
    ACCT_CD STRING,
    GRP_CD STRING,
    SUBGRP_CD STRING,
    PROD_ID_CD STRING,
    PROD_TYPE_CD STRING,
    SUB_ID STRING,
    MEMB_RITNSHP_CD STRING,
    PHRMCY_BNFT_IND STRING,
    MED_BNFT_IND STRING,
    HSPTL_BNFT_IND STRING,
    MH_BNFT_IND STRING,
    CD_BNFT_IND STRING,
    DENT_BNFT_IND STRING,
    POP_ID STRING,
    EXCH_IND STRING,
    RATING_AREA STRING,
    PREM_AMT STRING,
    CSR_INDICATOR STRING,
    METAL STRING,
    ENROLL_PERIOD_ACT STRING,
    MEMB_MED_COB_CD STRING,
    MEMB_PHRMCY_COB_CD STRING,
    SEG1_ID STRING, SEG2_ID STRING, SEG3_ID STRING, SEG4_ID STRING, SEG5_ID STRING,
    SEG6_ID STRING, SEG7_ID STRING, SEG8_ID STRING, SEG9_ID STRING, SEG10_ID STRING,
    MA_MCD_IND STRING,
    MA_OREC STRING,
    MA_FRAILTY_IND STRING,
    MA_LTI_FLAG STRING,
    MA_DELF_RISKFAC_CD STRING,
    MA_RAFT_CD STRING,
    MA_FRAILTY_FACTOR STRING,
    GROUP_SIZE_CD STRING,
    NATIONAL_ACCOUNT_IND STRING,
    LINE_OF_BUSINESS_CD STRING,
    MARKET_CD STRING,
    PRODUCT_LINE_CD STRING,
    EMPLOYEE_STATUS_CD STRING,
    EMPLOYEE_TYPE_CD STRING,
    FUNDING_ARRANGEMENT_CD STRING,
    BARGAINING_STATUS_CD STRING,
    CONTRACT_ID STRING,
    CONTRACT_EFFECTIVE_DT STRING,
    CONTRACT_END_DT STRING,
    NAICS_CD STRING,
    INDUSTRY STRING,
    SEG11_ID STRING, SEG12_ID STRING, SEG13_ID STRING, SEG14_ID STRING,
    SOURCE_LOAD_MONTH STRING, CREATED_DATE TIMESTAMP, CREATED_BY STRING, UPDATED_DATE TIMESTAMP,
    UPDATED_BY STRING, VALIDATED_TIMESTAMP TIMESTAMP)
USING DELTA
TBLPROPERTIES(
    'delta.columnMapping.mode' = 'name',
    'delta.enableIcebergCompatV2' = 'true',
    'delta.universalFormat.enabledFormats' = 'iceberg')
    PARTITIONED BY (SOURCE_LOAD_MONTH);

CREATE OR REPLACE TABLE ${catalog}.${schema_ingestion}.stage_facility_detail (
    CLM_ID_CD STRING, ADJ_SEQ_NUM STRING, CLM_LN_NUM STRING, HOME_PLAN_ID_CD STRING,
    CPT_AND_HCPCS_CD STRING, PROC_MOD_CD STRING, PROC_MOD_CD2 STRING, PROC_MOD_CD3 STRING,
    PROC_MOD_CD4 STRING, REIMB_TP_CD STRING, REV_CD STRING, TOT_UNITS_VAL STRING,
    SERV_FROM_DT STRING, SERV_END_DT STRING, ALLWD_AMT STRING, PMT_AMT STRING,
    SOURCE_LOAD_MONTH STRING, CREATED_DATE TIMESTAMP, CREATED_BY STRING, UPDATED_DATE TIMESTAMP,
    UPDATED_BY STRING, VALIDATED_TIMESTAMP TIMESTAMP)
USING DELTA TBLPROPERTIES( 'delta.columnMapping.mode' = 'name', 'delta.enableIcebergCompatV2' = 'true',
    'delta.universalFormat.enabledFormats' = 'iceberg') PARTITIONED BY (SOURCE_LOAD_MONTH);

CREATE OR REPLACE TABLE ${catalog}.${schema_ingestion}.stage_facility_diag (
    CLM_ID_CD STRING, ADJ_SEQ_NUM STRING, HOME_PLAN_ID_CD STRING, DIAG_TYPE_CD STRING,
    DIAG_NUM STRING, DIAG_CD STRING, ICD_VER STRING, SOURCE_LOAD_MONTH STRING,
    CREATED_DATE TIMESTAMP, CREATED_BY STRING, UPDATED_DATE TIMESTAMP, UPDATED_BY STRING,
    VALIDATED_TIMESTAMP TIMESTAMP)
USING DELTA TBLPROPERTIES(
    'delta.columnMapping.mode' = 'name',
    'delta.enableIcebergCompatV2' = 'true',
    'delta.universalFormat.enabledFormats' = 'iceberg')
PARTITIONED BY (SOURCE_LOAD_MONTH)
;

CREATE OR REPLACE TABLE ${catalog}.${schema_ingestion}.stage_facility_header (
    ISSUER_ID STRING, PLAN_ID STRING, CLM_ID_CD STRING, ADJ_SEQ_NUM STRING,
    CLM_TP_CD STRING, TRCBLT_FIELD_CD STRING, HOME_PLAN_ID_CD STRING, ITS_CLM_IND STRING,
    HOST_PLAN_ID_CD STRING, TP_OF_BILL_CD STRING, FIRST_SERV_DT STRING, LAST_SERV_DT STRING,
    STMT_FROM_DT STRING, STMT_END_DT STRING, CLM_PAID_DT STRING, CLM_PMT_STS_CD STRING,
    LOCATION_ID STRING, BILL_PROV_ID_CD STRING, BILL_PROV_SPCLT_CD STRING, BILL_PLAN_PROV_SPCLT_CD STRING,
    BILL_PROV_ZIP_CD STRING, RNDRNG_PROV_ID_CD STRING, RNDRNG_PROV_SPCLT_CD STRING, RNDRNG_PLAN_PROV_SPCLT_CD STRING,
    RNDRNG_PROV_ZIP_CD STRING, MEMB_ID_CD STRING, AGE_YR STRING, MEMB_GENDER_CD STRING,
    PROD_ID_CD STRING, POP_ID STRING, PRINC_PROC_CD STRING, PROC_CD_VER STRING,
    ICD_SURG_PROC_1 STRING, ICD_VER_1 STRING, ICD_SURG_PROC_2 STRING, ICD_VER_2 STRING,
    ICD_SURG_PROC_3 STRING, ICD_VER_3 STRING, ICD_SURG_PROC_4 STRING, ICD_VER_4 STRING,
    ICD_SURG_PROC_5 STRING, ICD_VER_5 STRING, ADMIT_SRC_CD STRING, DISCH_STUS_CD STRING,
    BRTHWG_CD STRING, ALLWD_AMT STRING, COIN_AMT STRING, COPAY_AMT STRING,
    DED_AMT STRING, COB_TPL_AMT STRING, PMT_AMT STRING, VOID_IND STRING,
    ADJDCT_DT STRING, MA_PROV_TYPE STRING, DRG_CD STRING, SOURCE_LOAD_MONTH STRING,
    CREATED_DATE TIMESTAMP, CREATED_BY STRING, UPDATED_DATE TIMESTAMP, UPDATED_BY STRING,
    VALIDATED_TIMESTAMP TIMESTAMP)
USING DELTA TBLPROPERTIES( 'delta.columnMapping.mode' = 'name',
    'delta.enableIcebergCompatV2' = 'true', 'delta.universalFormat.enabledFormats' = 'iceberg')
PARTITIONED BY (SOURCE_LOAD_MONTH);

CREATE OR REPLACE TABLE ${catalog}.${schema_ingestion}.stage_professional (
    ISSUER_ID STRING, PLAN_ID STRING, CLM_ID_CD STRING, ADJ_SEQ_NUM STRING,
    CLM_LN_NUM STRING, TRCBLT_FIELD_CD STRING, HOME_PLAN_ID_CD STRING, ITS_CLM_IND STRING,
    HOST_PLAN_ID_CD STRING, SERV_FROM_DT STRING, SERV_END_DT STRING, CLM_PAID_DT STRING,
    CLM_PMT_STS_CD STRING, LOCATION_ID STRING, BILL_PROV_ID_CD STRING, BILL_PROV_SPCLT_CD STRING,
    BILL_PLAN_PROV_SPCLT_CD STRING, BILL_PROV_ZIP_CD STRING, RNDRNG_PROV_ID_CD STRING, RNDRNG_PROV_SPCLT_CD STRING,
    RNDRNG_PLAN_PROV_SPCLT_CD STRING, RNDRNG_PROV_ZIP_CD STRING, MEMB_ID_CD STRING, AGE_YR STRING,
    MEMB_GENDER_CD STRING, PROD_ID_CD STRING, POP_ID STRING, CPT_AND_HCPCS_CD STRING,
    PROC_MOD_CD STRING, PROC_MOD_CD2 STRING, PROC_MOD_CD3 STRING, PROC_MOD_CD4 STRING,
    PLACE_OF_SERV_CD STRING, REIMB_TP_CD STRING, TOT_UNITS_CNT STRING, ALLWD_AMT STRING,
    COIN_AMT STRING, COPAY_AMT STRING, DED_AMT STRING, COB_TPL_AMT STRING,
    PMT_AMT STRING, VOID_IND STRING, ADJDCT_DT STRING, MA_PROV_TYPE STRING,
    SOURCE_LOAD_MONTH STRING, CREATED_DATE TIMESTAMP, CREATED_BY STRING, UPDATED_DATE TIMESTAMP,
    UPDATED_BY STRING, VALIDATED_TIMESTAMP TIMESTAMP)
USING DELTA
TBLPROPERTIES(
    'delta.columnMapping.mode' = 'name',
    'delta.enableIcebergCompatV2' = 'true',
    'delta.universalFormat.enabledFormats' = 'iceberg')
PARTITIONED BY (SOURCE_LOAD_MONTH);

CREATE OR REPLACE TABLE ${catalog}.${schema_ingestion}.stage_professional_diag (
    CLM_ID_CD STRING, ADJ_SEQ_NUM STRING, HOME_PLAN_ID_CD STRING, DIAG_TYPE_CD STRING,
    DIAG_NUM STRING, DIAG_CD STRING, ICD_VER STRING, SOURCE_LOAD_MONTH STRING,
    CREATED_DATE TIMESTAMP, CREATED_BY STRING, UPDATED_DATE TIMESTAMP, UPDATED_BY STRING,
    VALIDATED_TIMESTAMP TIMESTAMP)
USING DELTA
TBLPROPERTIES( 'delta.columnMapping.mode' = 'name', 'delta.enableIcebergCompatV2' = 'true',
    'delta.universalFormat.enabledFormats' = 'iceberg')PARTITIONED BY (SOURCE_LOAD_MONTH);

CREATE OR REPLACE TABLE ${catalog}.${schema_ingestion}.stage_pharmacy (
    ISSUER_ID STRING,
    PLAN_ID STRING,
    MEMB_ID_CD STRING,
    AGE_YR STRING,
    MEMB_GENDER_CD STRING,
    PROD_ID_CD STRING,
    POP_ID STRING,
    CLM_ID_CD STRING,
    ADJ_SEQ_NUM STRING,
    CLM_LN_NUM STRING,
    TRCBLT_FIELD_CD STRING,
    HOME_PLAN_ID_CD STRING,
    SERV_DT STRING,
    CLM_PAID_DT STRING,
    CLM_PMT_STS_CD STRING,
    BILL_PROV_ID_CD STRING,
    NPI_BILL_PROV_ID_CD STRING,
    PRSCRB_PROV_ID_CD STRING,
    NPI_PRSCRB_PROV_ID_CD STRING,
    PROD_SERV_ID_CD STRING,
    REIMB_TP_CD STRING,
    QTY_DSPNSD_VAL STRING,
    DAYS_SUPPLY_CNT STRING,
    ALLOWED_AMT STRING,
    PRDC_DED_AMT STRING,
    COPAY_COIN_AMT STRING,
    PMT_AMT STRING,
    VOID_IND STRING,
    DSPNSN_STS_CD STRING,
    ADDCT_DT STRING,
    RX_NUMBER STRING,
    FILL_NUMBER STRING,
    PRESCRIBED_DT STRING,
    MEDICARE_CVRG_CD STRING,
    PHARMACY_ID STRING,
    GENERIC_IND STRING,
    SPCLT_DRUG_IND STRING,
    MAIL_ORDER_IND STRING,
    SOURCE_LOAD_MONTH STRING,
    CREATED_DATE TIMESTAMP,
    CREATED_BY STRING,
    UPDATED_DATE TIMESTAMP,
    UPDATED_BY STRING,
    VALIDATED_TIMESTAMP TIMESTAMP)
USING DELTA
TBLPROPERTIES( 'delta.columnMapping.mode' = 'name', 'delta.enableIcebergCompatV2' = 'true',
    'delta.universalFormat.enabledFormats' = 'iceberg')PARTITIONED BY (SOURCE_LOAD_MONTH);

CREATE OR REPLACE TABLE ${catalog}.${schema_ingestion}.stage_health_events (
    HOME_PLAN_ID_CD STRING, MEMB_ID_CD STRING, PROGRAM_ID STRING, EVENT_ID STRING,
    COND_CAT STRING, COND_VER STRING, PROCESS_DATE STRING, PROG_START_DT STRING,
    PROG_END_DT STRING, RECORD_ID STRING, RECORD_SUB_ID STRING, PERCENT_WEIGHT STRING,
    SOURCE_LOAD_MONTH STRING, CREATED_DATE TIMESTAMP, CREATED_BY STRING, UPDATED_DATE TIMESTAMP,
    UPDATED_BY STRING, VALIDATED_TIMESTAMP TIMESTAMP)
USING DELTA TBLPROPERTIES( 'delta.columnMapping.mode' = 'name',
    'delta.enableIcebergCompatV2' = 'true', 'delta.universalFormat.enabledFormats' = 'iceberg')
PARTITIONED BY (SOURCE_LOAD_MONTH);

CREATE OR REPLACE TABLE ${catalog}.${schema_ingestion}.stage_provider (
    HOME_PLAN_ID_CD STRING, BHI_PROV_ID STRING, PROVIDER_ID STRING, ALT_PROV_ID STRING,
    CON_PROV_ID STRING, PROV_SPCLT_CD STRING, PLAN_PROV_SPCLT_CD STRING, CMS_SPCLT_CD STRING,
    PROV_TYPE STRING, PROV_NET_IND STRING, OOA_IND STRING, PROV_DOE_NM STRING,
    PROV_NM_LAST STRING, PROV_NM_FIRST STRING, PROV_STREET1 STRING, PROV_STREET2 STRING,
    PROV_CITY STRING, PROV_COUNTY_CD STRING, PROV_STATE STRING, PROV_ZIP STRING,
    PROV_PHONE STRING, PROV_EMAIL STRING, PROV_NPI STRING, PROV_DEA STRING,
    SEG1_ID STRING, SEG2_ID STRING, SEG3_ID STRING, SEG4_ID STRING,
    SEG5_ID STRING, SEG6_ID STRING, SEG7_ID STRING, SEG8_ID STRING,
    SEG9_ID STRING, SEG10_ID STRING, PROV_ARRANGEMENT_ID_1 STRING, PROV_ARRANGEMENT_NM_1 STRING,
    PROV_ARRANGEMENT_TYPE_CD_1 STRING, PROV_ARRANGEMENT_START_DT_1 STRING, PROV_ARRANGEMENT_END_DT_1 STRING, PROV_ARRANGEMENT_ID_2 STRING,
    PROV_ARRANGEMENT_NM_2 STRING, PROV_ARRANGEMENT_TYPE_CD_2 STRING, PROV_ARRANGEMENT_START_DT_2 STRING, PROV_ARRANGEMENT_END_DT_2 STRING,
    PROV_TAXONOMY_CD STRING, MEDICARE_PROV_ID STRING, SOURCE_LOAD_MONTH STRING, CREATED_DATE TIMESTAMP,
    CREATED_BY STRING, UPDATED_DATE TIMESTAMP, UPDATED_BY STRING, VALIDATED_TIMESTAMP TIMESTAMP)
USING DELTA TBLPROPERTIES( 'delta.columnMapping.mode' = 'name', 'delta.enableIcebergCompatV2' = 'true',
    'delta.universalFormat.enabledFormats' = 'iceberg') PARTITIONED BY (SOURCE_LOAD_MONTH);

CREATE OR REPLACE TABLE ${catalog}.${schema_ingestion}.stage_location (
    HOME_PLAN_ID_CD STRING, BILL_PROV_ID STRING, LOCATION_ID STRING, LOCATION_ADDRESS_ID STRING,
    LOCATION_NAME STRING, LOCATION_PEER_GROUP STRING, LOCATION_STREET1 STRING, LOCATION_STREET2 STRING,
    LOCATION_CITY STRING, LOCATION_COUNTY_CD STRING, LOCATION_STATE STRING, LOCATION_ZIP STRING,
    LOCATION_PHONE STRING, LOCATION_EMAIL STRING, SEG1_ID STRING, SEG2_ID STRING,
    SEG3_ID STRING, SEG4_ID STRING, SEG5_ID STRING, SEG6_ID STRING,
    SEG7_ID STRING, SEG8_ID STRING, SEG9_ID STRING, SEG10_ID STRING,
    SOURCE_LOAD_MONTH STRING, CREATED_DATE TIMESTAMP, CREATED_BY STRING, UPDATED_DATE TIMESTAMP,
    UPDATED_BY STRING, VALIDATED_TIMESTAMP TIMESTAMP)
USING DELTA TBLPROPERTIES( 'delta.columnMapping.mode' = 'name', 'delta.enableIcebergCompatV2' = 'true',
    'delta.universalFormat.enabledFormats' = 'iceberg') PARTITIONED BY (SOURCE_LOAD_MONTH);

CREATE OR REPLACE TABLE ${catalog}.${schema_ingestion}.stage_designated_provider (
    MEMB_ID_CD STRING, PROV_ID STRING, HOME_PLAN_ID_CD STRING, START_DATE STRING,
    END_DATE STRING, PROV_ARRANGEMENT_PROGRAM_ID STRING, SEG1_ID STRING, SEG2_ID STRING,
    SOURCE_LOAD_MONTH STRING, CREATED_DATE TIMESTAMP, CREATED_BY STRING, UPDATED_DATE TIMESTAMP,
    UPDATED_BY STRING, VALIDATED_TIMESTAMP TIMESTAMP)
USING DELTA TBLPROPERTIES( 'delta.columnMapping.mode' = 'name',
    'delta.enableIcebergCompatV2' = 'true', 'delta.universalFormat.enabledFormats' = 'iceberg')
PARTITIONED BY (SOURCE_LOAD_MONTH);

CREATE OR REPLACE TABLE ${catalog}.${schema_ingestion}.stage_quality_events (
    HOME_PLAN_ID_CD STRING, MEMB_ID_CD STRING, EVENT_CD STRING, EVENT_DT STRING,
    EVENT_PROV_ID_CD STRING, CLM_ID_CD STRING, CLM_LN_NUM STRING, TRCBLT_FIELD_CD STRING,
    SOURCE_LOAD_MONTH STRING, CREATED_DATE TIMESTAMP, CREATED_BY STRING, UPDATED_DATE TIMESTAMP,
    UPDATED_BY STRING, VALIDATED_TIMESTAMP TIMESTAMP)
USING DELTA TBLPROPERTIES( 'delta.columnMapping.mode' = 'name', 'delta.enableIcebergCompatV2' = 'true',
    'delta.universalFormat.enabledFormats' = 'iceberg')PARTITIONED BY (SOURCE_LOAD_MONTH);

CREATE OR REPLACE TABLE ${catalog}.${schema_ingestion}.stage_lab (
    HOME_PLAN_ID_CD STRING, MEMB_ID_CD STRING, CLM_ID_CD STRING, LOINC_CD STRING,
    SERV_DT STRING, LAB_ID STRING, LAB_RESULT_CD STRING, LAB_RESULT_VAL STRING,
    LAB_RESULT_FLAG_CD STRING, TRCBLT_FIELD_CD STRING, ORDERING_PROV_ID STRING, ORDERING_PROV_NPI STRING,
    ORDERING_PROV_NM_LAST STRING, ORDERING_PROV_NM_FIRST STRING, ORDERING_PROV_ZIP STRING, SOURCE_LOAD_MONTH STRING,
    CREATED_DATE TIMESTAMP, CREATED_BY STRING, UPDATED_DATE TIMESTAMP, UPDATED_BY STRING,
    VALIDATED_TIMESTAMP TIMESTAMP)
USING DELTA TBLPROPERTIES( 'delta.columnMapping.mode' = 'name', 'delta.enableIcebergCompatV2' = 'true',
    'delta.universalFormat.enabledFormats' = 'iceberg') PARTITIONED BY (SOURCE_LOAD_MONTH);

CREATE OR REPLACE TABLE ${catalog}.${schema_ingestion}.stage_mmr(
    CONTRACT_NUMBER STRING, RUN_DATE STRING, PAYMENT_DATE STRING, BENEFICIARY_ID STRING,
    SURNAME STRING, FIRST_INITIAL STRING, GENDER_CODE STRING, DATE_OF_BIRTH STRING,
    STATE_AND_COUNTY_CODE STRING, OUT_OF_AREA_INDICATOR STRING, PART_A_ENTITLEMENT STRING, PART_B_ENTITLEMENT STRING,
    HOSPICE STRING, ESRD STRING, AGED_DISABLED_MSP STRING, NEW_MEDICARE_BENEFICIARY_INDICATOR STRING,
    LTI_FLAG STRING, MEDICAID_INDICATOR STRING, DEFAULT_RISK_FACTOR_CODE STRING, RISK_ADJUSTMENT_FACTOR_A STRING,
    RISK_ADJUSTMENT_FACTOR_B STRING, NUMBER_OF_PAYMT_ADJUSTMT_MONTHS_PART_A STRING, NUMBER_OF_PAYMT_ADJUSTMT_MONTHS_PART_B STRING, ADJUSTMENT_REASON_CODE STRING,
    PAYMT_ADJUSTSTMT_START_DATE STRING, PAYMT_ADJUSTMENT_END_DATE STRING, MONTHLY_PAYMT_ADJUSTSTMT_AMOUNT_RATE_A STRING, MONTHLY_PAYMT_ADJUSTMT_AMOUNT_RATE_B STRING,
    LIS_PREMIUM_SUBSIDY STRING, ESRD_MSP_FLAG STRING, MEDICATION_THERAPY_MANAGEMENT_MTM_ADD_ON STRING, PART_D_MANUFACTURER_DISCOUNT STRING,
    MEDICAID_STATUS STRING, RISK_ADJUSTMENT_AGE_GROUP_RAAG STRING, PLAN_BENEFIT_PACKAGE_ID STRING, RISK_ADJUSTMENT_FACTOR_TYPE_CODE STRING,
    FRAILTY_INDICATOR STRING, ORIGINAL_REASON_FOR_ENTITLEMENT_CODE_OREC STRING, SEGMENT_NUMBER STRING, EGHP_FLAG STRING,
    PART_C_BASIC_PREMIUM_PART_A_AMOUNT STRING, PART_C_BASIC_PREMIUM_PART_B_AMOUNT STRING, REBATE_FOR_PART_A_COST_SHARING_REDUCTION STRING, REBATE_FOR_PART_B_COST_SHARING_REDUCTION STRING,
    REBATE_FOR_OTHER_PART_A_MANDATORY_SUPPLEMENTAL_BENEFITS STRING, REBATE_FOR_OTHER_PART_B_MANDATORY_SUPPLEMENTAL_BENEFITS STRING, REBATE_FOR_PART_B_PREMIUM_REDUCTION_PART_A_AMOUNT STRING,
    REBATE_FOR_PART_B_PREMIUM_REDUCTION_PART_B_AMOUNT STRING,
    REBATE_FOR_PART_D_SUPPLEMENTAL_BENEFITS_PART_A_AMOUNT STRING, REBATE_FOR_PART_D_SUPPLEMENTAL_BENEFITS_PART_B_AMOUNT STRING, TOTAL_PART_A_MA_PAYMENT STRING, TOTAL_PART_B_MA_PAYMENT STRING,
    TOTAL_MA_PAYMENT_AMOUNT STRING, PART_D_RA_FACTOR STRING, PART_D_LOW_INCOME_INDICATOR STRING, PART_D_LOW_INCOME_MULTIPLIER STRING,
    PART_D_LONG_TERM_INSTITUTIONAL_INDICATOR STRING, PART_D_LONG_TERM_INSTITUTIONAL_MULTIPLIER STRING, REBATE_FOR_PART_D_BASIC_PREMIUM_REDUCTION STRING, PART_D_BASIC_PREMIUM_AMOUNT STRING,
    PART_D_DIRECT_SUBSIDY_MONTHLY_PAYMENT_AMOUNT STRING, REINSURANCE_SUBSIDY_AMOUNT STRING, LOW_INCOME_SUBSIDY_COST_SHARING_AMOUNT STRING, TOTAL_PART_D_PAYMENT STRING,
    NUMBER_OF_PAYMT_ADJUSTMT_MONTHS_PART_D STRING, PACE_PREMIUM_ADD_ON STRING, PACE_COST_SHARING_CD_ON STRING, PART_C_FRAILTY_SCORE_FACTOR STRING,
    MSP_FACTOR STRING, HSP_REDUCTION_ADJUSTMENT_AMOUNT_PART_A STRING, HSP_REDUCTION_ADJUSTMENT_AMOUNT_PART_B STRING, MEDICAID_DUAL_STATUS_CODE STRING,
    PART_D_COVERAGE_GAP_DISCOUNT_AMOUNT STRING, PART_D_RISK_ADJUSTMENT_FACTOR_TYPE STRING, DEFAULT_PART_D_RISK_ADJUSTMENT_FACTOR_CODE STRING,
    PART_A_BTCG_ADJUSTED_MONTHLY_RATE_AMOUNT_FOR_PYMT_ADJ STRING,
    PART_B_RISK_ADJUSTED_MONTHLY_RATE_AMOUNT_FOR_PYMT_ADJ STRING, PART_D_DIRECT_SUBSIDY_MONTHLY_RATE_AMOUNT_FOR_PYMT_ADJ STRING, CLEANUP_ID STRING, PLAN_NAME STRING,
    SOURCE_LOAD_MONTH STRING, DATA_CYCLE_ID STRING, HOME_PLAN_ID STRING, SUBM_BID STRING,
    PROCESS_IND_YN VARCHAR(2) DEFAULT 'N', CREATED_DATE TIMESTAMP, CREATED_BY STRING, UPDATED_DATE TIMESTAMP, UPDATED_BY STRING,
    VALIDATED_TIMESTAMP TIMESTAMP)
USING delta TBLPROPERTIES( 'delta.columnMapping.mode' = 'name', 'delta.enableIcebergCompatV2' = 'true',
    'delta.feature.allowColumnDefaults' = 'supported', 'delta.universalFormat.enabledFormats' = 'iceberg')
PARTITIONED BY (SOURCE_LOAD_MONTH);

CREATE OR REPLACE TABLE ${catalog}.${schema_ingestion}.stage_medicare_mao_header (
    RECORD_TYPE STRING, REPORT_ID STRING, CONTRACT_ID STRING, REPORT_DATE STRING,
    REPORT_DESC STRING, SUB_FILE_TYPE STRING, PHASE STRING, VERSION STRING,
    PLAN_NAME STRING, SOURCE_LOAD_MONTH STRING, CREATED_BY STRING, CREATED_DATE TIMESTAMP,
    UPDATED_BY STRING, UPDATED_DATE TIMESTAMP)
USING DELTA TBLPROPERTIES( 'delta.columnMapping.mode' = 'name',
    'delta.enableIcebergCompatV2' = 'true', 'delta.universalFormat.enabledFormats' = 'iceberg');

CREATE OR REPLACE TABLE ${catalog}.${schema_ingestion}.stage_medicare_mao_trailer (
    RECORD_TYPE STRING, REPORT_ID STRING, CONTRACT_ID STRING, NUMRECS STRING,
    PLAN_NAME STRING, SOURCE_LOAD_MONTH STRING, CREATED_DATE TIMESTAMP, CREATED_BY STRING,
    UPDATED_BY STRING, UPDATED_DATE TIMESTAMP)
USING DELTA TBLPROPERTIES( 'delta.columnMapping.mode' = 'name',
    'delta.enableIcebergCompatV2' = 'true', 'delta.universalFormat.enabledFormats' = 'iceberg');

CREATE OR REPLACE TABLE ${catalog}.${schema_ingestion}.stage_medicare_mao (
    RECORD_TYPE STRING, REPORT_ID STRING, CONTRACT_ID STRING, MBI STRING,
    ICN STRING, ENCOUNTER_TYPE STRING, ENCOUNTER_ICN STRING, ALLOWED_STATUS STRING,
    SUBMIT_DATE STRING, DOS_FROM STRING, DOS_THRU STRING, SERVICE_TYPE STRING,
    ALLOWED_FLAG STRING, REASON_CODE STRING, ICD_TYPE STRING, DIAG_CODE_01 STRING,
    DIAG_FLAG_01 STRING, DIAG_CODE_02 STRING, DIAG_FLAG_02 STRING, DIAG_CODE_03 STRING,
    DIAG_FLAG_03 STRING, DIAG_CODE_04 STRING, DIAG_FLAG_04 STRING, DIAG_CODE_05 STRING,
    DIAG_FLAG_05 STRING, DIAG_CODE_06 STRING, DIAG_FLAG_06 STRING, DIAG_CODE_07 STRING,
    DIAG_FLAG_07 STRING, DIAG_CODE_08 STRING, DIAG_FLAG_08 STRING, DIAG_CODE_09 STRING,
    DIAG_FLAG_09 STRING, DIAG_CODE_10 STRING, DIAG_FLAG_10 STRING, DIAG_CODE_11 STRING,
    DIAG_FLAG_11 STRING, DIAG_CODE_12 STRING, DIAG_FLAG_12 STRING, DIAG_CODE_13 STRING,
    DIAG_FLAG_13 STRING, DIAG_CODE_14 STRING, DIAG_FLAG_14 STRING, DIAG_CODE_15 STRING,
    DIAG_FLAG_15 STRING, DIAG_CODE_16 STRING, DIAG_FLAG_16 STRING, DIAG_CODE_17 STRING,
    DIAG_FLAG_17 STRING, DIAG_CODE_18 STRING, DIAG_FLAG_18 STRING, DIAG_CODE_19 STRING,
    DIAG_FLAG_19 STRING, DIAG_CODE_20 STRING, DIAG_FLAG_20 STRING, DIAG_CODE_21 STRING,
    DIAG_FLAG_21 STRING, DIAG_CODE_22 STRING, DIAG_FLAG_22 STRING, DIAG_CODE_23 STRING,
    DIAG_FLAG_23 STRING, DIAG_CODE_24 STRING, DIAG_FLAG_24 STRING, DIAG_CODE_25 STRING,
    DIAG_FLAG_25 STRING, DIAG_CODE_26 STRING, DIAG_FLAG_26 STRING, DIAG_CODE_27 STRING,
    DIAG_FLAG_27 STRING, DIAG_CODE_28 STRING, DIAG_FLAG_28 STRING, DIAG_CODE_29 STRING,
    DIAG_FLAG_29 STRING, DIAG_CODE_30 STRING, DIAG_FLAG_30 STRING, DIAG_CODE_31 STRING,
    DIAG_FLAG_31 STRING, DIAG_CODE_32 STRING, DIAG_FLAG_32 STRING, DIAG_CODE_33 STRING,
    DIAG_FLAG_33 STRING, DIAG_CODE_34 STRING, DIAG_FLAG_34 STRING, DIAG_CODE_35 STRING,
    DIAG_FLAG_35 STRING, DIAG_CODE_36 STRING, DIAG_FLAG_36 STRING, DIAG_CODE_37 STRING,
    DIAG_FLAG_37 STRING, DIAG_CODE_38 STRING, DIAG_FLAG_38 STRING, PLAN_NAME STRING,
    SOURCE_LOAD_MONTH STRING, DATA_CYCLE_ID STRING, HOME_PLAN_ID STRING, SUBM_BID STRING,
    PROCESS_IND_YN VARCHAR(2) DEFAULT 'N', CREATED_BY STRING, CREATED_DATE TIMESTAMP, UPDATED_BY STRING,
    UPDATED_DATE TIMESTAMP)
USING DELTA TBLPROPERTIES( 'delta.columnMapping.mode' = 'name', 'delta.enableIcebergCompatV2' = 'true',
    'delta.feature.allowColumnDefaults' = 'supported', 'delta.universalFormat.enabledFormats' = 'iceberg');

CREATE OR REPLACE TABLE ${catalog}.${schema_ingestion}.stage_medicare_mor_partc_header (
    FID STRING NOT NULL, RECORD_TYPE_CODE STRING NOT NULL, CONTRACT_NUMBER STRING NOT NULL, RUN_DATE STRING,
    PAYMENT_YEAR_MONTH STRING, PLAN_NAME STRING, SOURCE_LOAD_MONTH STRING, CREATED_BY STRING,
    CREATED_DATE TIMESTAMP, UPDATED_BY STRING, UPDATED_DATE TIMESTAMP)
USING DELTA TBLPROPERTIES( 'delta.columnMapping.mode' = 'name', 'delta.enableIcebergCompatV2' = 'true',
    'delta.universalFormat.enabledFormats' = 'iceberg');

CREATE OR REPLACE TABLE ${catalog}.${schema_ingestion}.stage_medicare_mor_partc_trailer (
    FID STRING NOT NULL, RECORD_TYPE_CODE STRING NOT NULL, CONTRACT_NUMBER STRING NOT NULL, TOTAL_RECORD_COUNT STRING NOT NULL,
    PLAN_NAME STRING, SOURCE_LOAD_MONTH STRING, CREATED_BY STRING, CREATED_DATE TIMESTAMP,
    UPDATED_BY STRING, UPDATED_DATE TIMESTAMP)
USING DELTA TBLPROPERTIES( 'delta.columnMapping.mode' = 'name',
    'delta.enableIcebergCompatV2' = 'true', 'delta.universalFormat.enabledFormats' = 'iceberg');
