CREATE TABLE IF NOT EXISTS ${catalog}.${schema_ingestion}.stage_member (
    HOME_PLAN_ID_CD STRING, MEMB_ID_CD STRING, BHT_MEMB_ID STRING, DEID_MEMB_ID STRING,
    PERSON_ID_CD STRING, ALT_MEM_ID STRING, MBRS_NM_LAST STRING, MBRS_NM_FIRST STRING,
    MBRS_STREET1 STRING, MBRS_STREET2 STRING, MBRS_CITY STRING, MBRS_STATE STRING,
    MBRS_CENT_COUNTY_CD STRING, MBRS_CENT_ZIP_CD STRING, MBRS_PRIM_EMAIL STRING,
    MBRS_PREF_CONTACT STRING, MEMB_BRTH_DT STRING, MEMB_GENDER_CD STRING, MEMB_CREDT_CD STRING,
    MEMB_SMOKING_STS STRING, MEMB_DEATH_DT STRING,
    SEG1_ID STRING,SEG2_ID STRING, SEG3_ID STRING,SEG4_ID STRING,SEG5_ID STRING,
    MBRS_NM_MIDDLE STRING, MBRS_CRNT_PRIM_ZIP_PLUSFOUR STRING, SOURCE_LOAD_MONTH STRING, CREATED_DATE TIMESTAMP,
    CREATED_BY STRING, UPDATED_DATE TIMESTAMP, UPDATED_BY STRING, VALIDATED_TIMESTAMP TIMESTAMP)
USING DELTA TBLPROPERTIES( 'delta.columnMapping.mode' = 'name') PARTITIONED BY (SOURCE_LOAD_MONTH);

CREATE TABLE IF NOT EXISTS ${catalog}.${schema_ingestion}.stage_member_enrollment_history (
    HOME_PLAN_ID_CD STRING, MEMB_ID_CD STRING, BHT_MEMB_ID STRING, CONTRACT_BEGIN_DT STRING,
    CONTRACT_END_DT STRING, POD_ID STRING, ACCT_CD STRING, GRP_CD STRING,
    SUBGRP_CD STRING, PROD_ID_CD STRING, SOURCE_LOAD_MONTH STRING, CREATED_DATE TIMESTAMP,
    CREATED_BY STRING, UPDATED_DATE TIMESTAMP, UPDATED_BY STRING, VALIDATED_TIMESTAMP TIMESTAMP)
USING DELTA
TBLPROPERTIES(
    'delta.columnMapping.mode' = 'name') PARTITIONED BY (SOURCE_LOAD_MONTH);
