-- MA RA Reference Tables DDL

CREATE TABLE IF NOT EXISTS ${catalog}.${schema_reference}.time_periods (
    TIME_PERIOD BIGINT,
    BEGIN_DATE DATE,
    END_DATE DATE,
    TIME_PERIOD_TYPE_CD STRING,
    CREATED_DATE TIMESTAMP,
    CREATED_BY STRING,
    UPDATED_DATE TIMESTAMP,
    UPDATED_BY STRING
)
USING DELTA;

CREATE TABLE IF NOT EXISTS ${catalog}.${schema_reference}.ref_risk_model (
    MODEL_ID SMALLINT NOT NULL,
    MODEL_NAME STRING NOT NULL,
    PROGRAM_MODEL STRING,
    PROGRAM STRING,
    CREATED_DATE TIMESTAMP,
    CREATED_BY STRING,
    UPDATED_DATE TIMESTAMP,
    UPDATED_BY STRING
)
USING DELTA;

CREATE TABLE IF NOT EXISTS ${catalog}.${schema_reference}.ref_risk_variable (
    VARIABLE_ID INT NOT NULL,
    MODEL_ID SMALLINT NOT NULL,
    RAR_MODEL_VERSION_ID SMALLINT,
    VARIABLE_CODE STRING,
    VARIABLE_DESC STRING,
    MIN_AGE_LAST SMALLINT,
    MAX_AGE_LAST SMALLINT,
    GENDER STRING,
    HCC_FLAG STRING,
    ELIG_FLAG STRING,
    DEMO_FLAG STRING,
    AGESENDER_FLAG STRING,
    INCLUDE_IN_COUNTS STRING,
    CREATED_DATE TIMESTAMP,
    CREATED_BY STRING,
    UPDATED_DATE TIMESTAMP,
    UPDATED_BY STRING
)
USING DELTA;

CREATE TABLE IF NOT EXISTS ${catalog}.${schema_reference}.ref_risk_variable_detail (
    VARIABLE_ID INT NOT NULL,
    MODEL_ID SMALLINT NOT NULL,
    HCC_ID INT,
    RAR_MODEL_VERSION_ID SMALLINT,
    TYPE_ID TINYINT,
    CREATED_DATE TIMESTAMP,
    CREATED_BY STRING,
    UPDATED_DATE TIMESTAMP,
    UPDATED_BY STRING
)
USING DELTA;

CREATE TABLE IF NOT EXISTS ${catalog}.${schema_reference}.ref_method_metadata (
    METHOD_ID SMALLINT NOT NULL,
    PROGRAM_ID INT,
    PROGRAM_MODEL STRING,
    PROG_TYPE STRING,
    ICD_VER STRING,
    CLAIM_CD_TYPE STRING,
    CLAIM_CD STRING,
    CLAIM_CD_MODIFIER_TYPE STRING,
    CLAIM_CD_MODIFIER STRING,
    OJ_ID INT,
    SUBCO BIGINT,
    GENDER STRING,
    EXCLUSION_TYPE_1 STRING,
    EXCLUSION_1 STRING,
    EXCLUSION_TYPE_2 STRING,
    EXCLUSION_2 STRING,
    AGE_FIRST_START SMALLINT,
    AGE_FIRST_END SMALLINT,
    AGE_LAST_STAFF SMALLINT,
    AGE_LAST_END SMALLINT,
    MEDICAL_CONDITION_ID INT,
    QUALIFIED_CLAIM SMALLINT,
    BUNDLED_CHECK SMALLINT,
    EFFECTIVE_DATE DATE,
    EXPIRATION_DATE DATE,
    CREATED_DATE TIMESTAMP,
    CREATED_BY STRING,
    UPDATED_DATE TIMESTAMP,
    UPDATED_BY STRING
)
USING DELTA
PARTITIONED BY (METHOD_ID, PROGRAM_ID);

CREATE TABLE IF NOT EXISTS ${catalog}.${schema_reference}.version_weightage_risk_year (
    MODEL_PERIOD STRING,
    VERSION STRING,
    RAR_VERSION BIGINT,
    CREATED_DATE TIMESTAMP,
    CREATED_BY STRING,
    UPDATED_DATE TIMESTAMP,
    UPDATED_BY STRING
)
USING DELTA;

CREATE TABLE IF NOT EXISTS ${catalog}.${schema_reference}.adjustment_factors (
    VERSION STRING,
    NORMALIZATION_FACTOR DOUBLE,
    CODING_PATTERN_ADJUSTMENT DOUBLE,
    DEMOGRAPHIC_FACTOR DOUBLE,
    TIME_PERIOD INT,
    CREATED_DATE TIMESTAMP,
    CREATED_BY STRING,
    UPDATED_DATE TIMESTAMP,
    UPDATED_BY STRING
)
USING DELTA;

CREATE TABLE IF NOT EXISTS ${catalog}.${schema_reference}.coefficient_scores (
    VERSION STRING,
    MODEL STRING,
    NAME STRING,
    COEFFICIENT DOUBLE,
    SCORE DOUBLE,
    CREATED_DATE TIMESTAMP,
    CREATED_BY STRING,
    UPDATED_DATE TIMESTAMP,
    UPDATED_BY STRING
)
USING DELTA;

CREATE TABLE IF NOT EXISTS ${catalog}.${schema_reference}.community_model_rules (
    MODEL STRING,
    VERSION STRING,
    CONDITION STRING,
    SNCO_MCP STRING,
    SNCO_SUPPLEMENTAL_AMR STRING,
    CREATED_DATE TIMESTAMP,
    CREATED_BY STRING,
    UPDATED_DATE TIMESTAMP,
    UPDATED_BY STRING
)
USING DELTA;

CREATE TABLE IF NOT EXISTS ${catalog}.${schema_reference}.hierarchy_config (
    VERSION STRING,
    PARENT INT,
    CHILD STRING,
    HIERARCHY_NUM INT,
    CREATED_DATE TIMESTAMP,
    CREATED_BY STRING,
    UPDATED_DATE TIMESTAMP,
    UPDATED_BY STRING
)
USING DELTA;

-- DDL for ${catalog}.${schema_reference}.icd_hcc_mapping
CREATE TABLE IF NOT EXISTS ${catalog}.${schema_reference}.icd_hcc_mapping (
    DIAGNOSISCODE STRING,
    DESCRIPTION STRING,
    OM8_HCC_ERRD_MODEL_CATEGORY_V21 INT,
    OM8_HCC_ERRD_MODEL_CATEGORY_V24 INT,
    OM8_HCC_MODEL_CATEGORY_V22 INT,
    OM8_HCC_MODEL_CATEGORY_V24 INT,
    OM8_HCC_MODEL_CATEGORY_V28 INT,
    RARCC_MODEL_CATEGORY_V05 INT,
    RARCC_MODEL_CATEGORY_V03 INT,
    OM8_HCC_ERRD_MODEL_CATEGORY_V21_FOR_2025_PAYMENT_YEAR STRING,
    OM8_HCC_ERRD_MODEL_CATEGORY_V24_FOR_2025_PAYMENT_YEAR STRING,
    OM8_HCC_MODEL_CATEGORY_V22_FOR_2025_PAYMENT_YEAR STRING,
    OM8_HCC_MODEL_CATEGORY_V24_FOR_2025_PAYMENT_YEAR STRING,
    OM8_HCC_MODEL_CATEGORY_V28_FOR_2025_PAYMENT_YEAR STRING,
    RARCC_MODEL_CATEGORY_V05_FOR_2025_PAYMENT_YEAR STRING,
    RARCC_MODEL_CATEGORY_V03_FOR_2025_PAYMENT_YEAR STRING,
    CREATED_DATE TIMESTAMP,
    CREATED_BY STRING,
    UPDATED_DATE TIMESTAMP,
    UPDATED_BY STRING
)
USING DELTA;

CREATE TABLE IF NOT EXISTS ${catalog}.${schema_reference}.interaction_coefficients (
    MODEL STRING,
    VERSION STRING,
    INTERACTION_GROUP_PRIMARY STRING,
    INTERACTION_GROUP_SECONDARY STRING,
    SCORE DOUBLE,
    CREATED_DATE TIMESTAMP,
    CREATED_BY STRING,
    UPDATED_DATE TIMESTAMP,
    UPDATED_BY STRING
)
USING DELTA;

CREATE TABLE IF NOT EXISTS ${catalog}.${schema_reference}.procedure_codes (
    HCPCS_CPT_CODE STRING,
    DESCRIPTION STRING,
    EFFECTIVE_DATE DATE,
    CREATED_DATE TIMESTAMP,
    CREATED_BY STRING,
    UPDATED_DATE TIMESTAMP,
    UPDATED_BY STRING
)
USING DELTA;

CREATE TABLE IF NOT EXISTS ${catalog}.${schema_reference}.ref_risk_proc_qualifying (
    CPT_AND_HCPCS_CD STRING,
    EFFECTIVE_DATE DATE,
    MA_EFFECTIVE_DATE DATE,
    OM8_ELIGIBILITY_FLAG STRING,
    CREATED_DATE TIMESTAMP,
    CREATED_BY STRING,
    UPDATED_DATE TIMESTAMP,
    UPDATED_BY STRING
)
USING DELTA;

CREATE TABLE IF NOT EXISTS ${catalog}.${schema_reference}.ref_risk_hcc (
    OJ_ID INT,
    PROGRAM STRING,
    OJ_CODE STRING,
    OJ_DESCRIPTION STRING,
    CATEGORY_ID SMALLINT,
    Notes STRING,
    CREATED_DATE TIMESTAMP,
    CREATED_BY STRING,
    UPDATED_DATE TIMESTAMP,
    UPDATED_BY STRING
)
USING DELTA;

CREATE TABLE IF NOT EXISTS ${catalog}.${schema_reference}.ref_risk_subco (
    SUBCO BIGINT,
    SUBCO_DESCRIPTION STRING,
    CATEGORY_ID SMALLINT,
    OUTWORKSSTART INT,
    OUTWORKSEND INT,
    CHRONIC TINYINT,
    CREATED_DATE TIMESTAMP,
    CREATED_BY STRING,
    UPDATED_DATE TIMESTAMP,
    UPDATED_BY STRING
)
USING DELTA;

CREATE TABLE IF NOT EXISTS ${catalog}.${schema_reference}.ref_saa_model (
    RAR_MODEL_VERSION_ID SMALLINT,
    RAR_MODEL_VERSION STRING,
    RAR_MODEL_YEAR SMALLINT,
    MODEL_BENEFIT TINYINT,
    PROGRAM_MODEL STRING,
    VERSION_CODE STRING,
    CREATED_DATE TIMESTAMP,
    CREATED_BY STRING,
    UPDATED_DATE TIMESTAMP,
    UPDATED_BY STRING
)
USING DELTA;

CREATE TABLE IF NOT EXISTS ${catalog}.${schema_reference}.ref_visit_type_rhcc (
    VISIT_TYPE_ID SMALLINT,
    VISIT_TYPE_DESC STRING,
    RHCC_CD STRING,
    RHCC_CD_DESC STRING,
    HCPCS_CD STRING,
    HCPCS_CD_END_DT DATE,
    CREATED_DATE TIMESTAMP,
    CREATED_BY STRING,
    UPDATED_DATE TIMESTAMP,
    UPDATED_BY STRING
)
USING DELTA;

CREATE TABLE IF NOT EXISTS ${catalog}.${schema_reference}.ref_place_of_service_hob (
    TYPE_OF_BILL_CD STRING,
    PLACE_OF_SERVICE STRING,
    POS_DESC STRING,
    CREATED_DATE TIMESTAMP,
    CREATED_BY STRING,
    UPDATED_DATE TIMESTAMP,
    UPDATED_BY STRING
)
USING DELTA;

CREATE TABLE IF NOT EXISTS ${catalog}.${schema_reference}.ref_chronic_condition (
    RAR_MODEL_YEAR INT,
    RAR_MODEL_VERSION STRING,
    MODEL_VERSION STRING,
    CC_ID INT,
    CC_CODE STRING,
    CC_DESCRIPTION STRING,
    CHRONIC TINYINT,
    CREATED_DATE TIMESTAMP,
    CREATED_BY STRING,
    UPDATED_DATE TIMESTAMP,
    UPDATED_BY STRING
)
USING DELTA;

CREATE TABLE IF NOT EXISTS ${catalog}.${schema_reference}.ref_bid_mapping (
    PREFIX STRING,
    STARTING_SERIES STRING,
    CLAIM_TYPE STRING,
    CLAIM_SOURCE STRING,
    CREATED_DATE TIMESTAMP,
    CREATED_BY STRING,
    UPDATED_DATE TIMESTAMP,
    UPDATED_BY STRING
)
USING DELTA;

CREATE TABLE IF NOT EXISTS ${catalog}.${schema_reference}.ref_mor_health_event_confidence (
    CHRONIC TINYINT,
    CURRENT_YEAR TINYINT,
    PRIOR_YEAR TINYINT,
    RECORD_YEAR_PRIOR INT,
    CREATED_DATE TIMESTAMP,
    CREATED_BY STRING,
    UPDATED_DATE TIMESTAMP,
    UPDATED_BY STRING
)
USING DELTA;

CREATE TABLE IF NOT EXISTS ${catalog}.${schema_reference}.ref_home_plan (
    HOME_PLAN_ID_CD STRING NOT NULL,
    HOME_PLAN_DESCRIPTION STRING,
    HOLDING_COMPANY_CODE STRING,
    HOLDING_COMPANY_DESCRIPTION STRING,
    IS_ACTIVE_PLAN BOOLEAN NOT NULL,
    IS_SUPPLEMENTAL_PLAN BOOLEAN NOT NULL,
    EFFECTIVE_DATE DATE,
    EXPIRATION_DATE DATE,
    CREATED_DATE TIMESTAMP,
    CREATED_BY STRING,
    UPDATED_DATE TIMESTAMP,
    UPDATED_BY STRING
)
USING DELTA;

CREATE TABLE IF NOT EXISTS ${catalog}.${schema_reference}.ref_home_plan_contract (
    HOME_PLAN_ID_CD STRING NOT NULL,
    HOME_PLAN_DESCRIPTION STRING,
    CONTRACT_ID STRING NOT NULL,
    CONTRACT_DESCRIPTION STRING,
    CONTRACT_START_DATE DATE,
    CONTRACT_END_DATE DATE,
    IS_ACTIVE BOOLEAN NOT NULL,
    HSI_VMARK_REQUIRED BOOLEAN NOT NULL,
    CREATED_DATE TIMESTAMP,
    CREATED_BY STRING,
    UPDATED_DATE TIMESTAMP,
    UPDATED_BY STRING
)
USING DELTA;

CREATE TABLE IF NOT EXISTS ${catalog}.${schema_reference}.ref_claim_type (
    CLAIM_TP_CD STRING,
    CLAIM_TYPE_CHG STRING NOT NULL,
    CLAIM_TYPE_DESC STRING,
    MA_PROC_TYPE STRING,
    CLAIM_CD BIGINT,
    CREATED_DATE TIMESTAMP,
    CREATED_BY STRING,
    UPDATED_DATE TIMESTAMP,
    UPDATED_BY STRING
)
USING DELTA;

CREATE TABLE IF NOT EXISTS ${catalog}.${schema_reference}.ref_method_frequency (
    METHOD_ID SMALLINT NOT NULL,
    PROGRAM STRING NOT NULL,
    PROGRAM_MODEL STRING,
    CLAIM_CD_TYPE STRING,
    CLAIM_CD STRING,
    CLAIM_CD_MODIFIER_TYPE STRING,
    CLAIM_CD_MODIFIER STRING,
    SUBCO BIGINT,
    FREQUENCY INT,
    PERCENT_WEIGHT DECIMAL(18,6),
    CREATED_DATE TIMESTAMP,
    CREATED_BY STRING,
    UPDATED_DATE TIMESTAMP,
    UPDATED_BY STRING
)
USING DELTA;

CREATE TABLE IF NOT EXISTS ${catalog}.${schema_reference}.ref_method_metadata_codegroups (
    RISK_CD INT,
    CLAIM_CD_TYPE STRING NOT NULL,
    CLAIM_CD STRING NOT NULL,
    CODE STRING NOT NULL,
    ICD_VER STRING,
    CREATED_DATE TIMESTAMP,
    CREATED_BY STRING,
    UPDATED_DATE TIMESTAMP,
    UPDATED_BY STRING
)
USING DELTA
PARTITIONED BY (ICD_VER);

CREATE TABLE IF NOT EXISTS ${catalog}.${schema_reference}.ref_risk_csf (
    OBR_INDICATOR STRING NOT NULL,
    OBR_DESCRIPTION STRING,
    CREATED_DATE TIMESTAMP,
    CREATED_BY STRING,
    UPDATED_DATE TIMESTAMP,
    UPDATED_BY STRING
)
USING DELTA;

CREATE TABLE IF NOT EXISTS ${catalog}.${schema_reference}.ref_risk_metal (
    METAL_ID SMALLINT NOT NULL,
    METAL STRING,
    METAL_DESCRIPTION STRING,
    CREATED_DATE TIMESTAMP,
    CREATED_BY STRING,
    UPDATED_DATE TIMESTAMP,
    UPDATED_BY STRING
)
USING DELTA;

CREATE TABLE IF NOT EXISTS ${catalog}.${schema_reference}.ref_method_prior_year (
    LAST_DK_COVOYANCE INT NOT NULL,
    DK_FREQUENCY_MIN INT NOT NULL,
    DK_FREQUENCY_MAX INT,
    PERCENT_WEIGHT DECIMAL(18,6) NOT NULL,
    CREATED_DATE TIMESTAMP,
    CREATED_BY STRING,
    UPDATED_DATE TIMESTAMP,
    UPDATED_BY STRING
)
USING DELTA
PARTITIONED BY (LAST_DK_COVOYANCE);

CREATE TABLE IF NOT EXISTS ${catalog}.${schema_reference}.ref_risk_type_detail (
    RAR_MODEL_VERSION STRING,
    RISK_TYPE_ID STRING,
    RISK_TYPE_DESC STRING,
    RISK_TYPE_DETAIL_ID STRING,
    RISK_TYPE_DETAIL_DESC STRING,
    NOTES STRING,
    CREATED_DATE TIMESTAMP,
    CREATED_BY STRING,
    UPDATED_DATE TIMESTAMP,
    UPDATED_BY STRING
)
USING DELTA;

CREATE TABLE IF NOT EXISTS ${catalog}.${schema_reference}.ref_method (
    METHOD_ID SMALLINT NOT NULL,
    METHOD_DESCRIPTION STRING,
    PROGRAM STRING,
    NOTES STRING,
    CREATED_DATE TIMESTAMP,
    CREATED_BY STRING,
    UPDATED_DATE TIMESTAMP,
    UPDATED_BY STRING
)
USING DELTA;

CREATE TABLE IF NOT EXISTS ${catalog}.${schema_reference}.ref_interaction_sources (
    RISK_MODEL_TYPE STRING,
    RISK_MODEL_VERSION STRING,
    RAR_MODEL_SEGMENT STRING,
    MODEL_SEGMENT STRING,
    RISK_MODEL_SEGMENT_TYPE STRING,
    INTERACTION_TYPE STRING,
    INTERACTION_NAME STRING,
    INTERACTION_DESC STRING,
    INTERACTION_MOC1 STRING,
    INTERACTION_MOC2 STRING,
    SCORE DOUBLE,
    CREATED_DATE TIMESTAMP,
    CREATED_BY STRING,
    UPDATED_DATE TIMESTAMP,
    UPDATED_BY STRING
)
USING DELTA;

CREATE TABLE IF NOT EXISTS ${catalog}.${schema_reference}.ref_interaction_scores (
    RISK_MODEL_TYPE STRING,
    RISK_MODEL_VERSION STRING,
    RAR_MODEL_SEGMENT STRING,
    RISK_MODEL_SEGMENT STRING,
    INTERACTION_TYPE STRING,
    INTERACTION_NAME STRING,
    INTERACTION_DESC STRING,
    INTERACTION_MOC1 STRING,
    INTERACTION_MOC2 STRING,
    SCORE DOUBLE,
    CREATED_DATE TIMESTAMP,
    CREATED_BY STRING,
    UPDATED_DATE TIMESTAMP,
    UPDATED_BY STRING
)
USING DELTA;

CREATE TABLE IF NOT EXISTS ${catalog}.${schema_reference}.ref_diag_chronic_condition (
    RAR_MODEL_YEAR INT,
    RAR_MODEL_VERSION STRING,
    OJ_CODE STRING,
    OJ_DESCRIPTION STRING,
    DIAG_CODE STRING,
    DIAG_DESCRIPTION STRING,
    EFFECTIVE_DATE DATE,
    EXPIRATION DATE,
    CHRONIC TINYINT,
    CREATED_DATE TIMESTAMP,
    CREATED_BY STRING,
    UPDATED_DATE TIMESTAMP,
    UPDATED_BY STRING
)
USING DELTA;