CREATE TABLE IF NOT EXISTS ${catalog}.${schema_transformation}.designated_primary_provider (
    DESIGNATED_PRIMARY_PROVIDER_BID BIGINT GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1) NOT NULL,
    HOME_PLAN_ID_CD VARCHAR(3) NOT NULL,
    MEMBER_BID BIGINT NOT NULL,
    MEMB_ID_CD VARCHAR(22) NOT NULL,
    PROVIDER_BID BIGINT NOT NULL,
    PROV_ID VARCHAR(27),
    SEG1_ID VARCHAR(60),
    SEG2_ID VARCHAR(60),
    LOAD_DATE TIMESTAMP NOT NULL,
    SOURCE_LOAD_MONTH VARCHAR(7) NOT NULL,
    CREATED_DATE TIMESTAMP,
    CREATED_BY VARCHAR(255),
    UPDATED_DATE TIMESTAMP,
    UPDATED_BY VARCHAR(255)
)
USING DELTA
TBLPROPERTIES(
    'delta.columnMapping.mode' = 'name')
PARTITIONED BY (SOURCE_LOAD_MONTH, HOME_PLAN_ID_CD);

CREATE TABLE IF NOT EXISTS ${catalog}.${schema_transformation}.facility_detail (
    FACILITY_BID BIGINT NOT NULL,
    CLM_ID_CD VARCHAR(50) NOT NULL,
    CLM_LN_NUM DECIMAL(3,0),
    ADJ_SEQ_NUM DECIMAL(8,0),
    HOME_PLAN_ID_CD VARCHAR(3) NOT NULL,
    BHI_PROV_ID VARCHAR(27),
    PROC_MOD_CD1 VARCHAR(2),
    PROC_MOD_CD2 VARCHAR(2),
    PROC_MOD_CD3 VARCHAR(2),
    PROC_MOD_CD4 VARCHAR(2),
    REIMBTP_CD VARCHAR(5),
    REV_CD VARCHAR(4),
    REV_DESC VARCHAR(100),
    SERV_FROM_DT DATE,
    SERV_END_DT DATE,
    ALLWD_AMT DECIMAL(10,2),
    PMT_AMT DECIMAL(10,2),
    SOURCE VARCHAR(50),
    LOAD_DATE TIMESTAMP NOT NULL,
    SOURCE_LOAD_MONTH VARCHAR(7) NOT NULL,
    CREATED_DATE TIMESTAMP,
    CREATED_BY VARCHAR(255),
    UPDATED_DATE TIMESTAMP,
    UPDATED_BY VARCHAR(255),
    VALIDATED_TIMESTAMP TIMESTAMP
)
USING DELTA
TBLPROPERTIES(
    'delta.columnMapping.mode' = 'name')
PARTITIONED BY (SOURCE_LOAD_MONTH, HOME_PLAN_ID_CD);
